package stdgo.math.big_test;
import stdgo.StdGoTypes;
import stdgo.Error;
import stdgo.Go;
import stdgo.GoString;
import stdgo.Pointer;
import stdgo.Slice;
import stdgo.GoArray;
import stdgo.GoMap;
import stdgo.Chan;
var _tests : Slice<stdgo.testing.Testing.InternalTest> = ((new Slice<stdgo.testing.Testing.InternalTest>(
((new stdgo.testing.Testing.InternalTest(((("TestFunVV" : GoString))), stdgo.math.big.Big.testFunVV) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFunVW" : GoString))), stdgo.math.big.Big.testFunVW) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFunVWExt" : GoString))), stdgo.math.big.Big.testFunVWExt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestShiftOverlap" : GoString))), stdgo.math.big.Big.testShiftOverlap) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue31084" : GoString))), stdgo.math.big.Big.testIssue31084) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue42838" : GoString))), stdgo.math.big.Big.testIssue42838) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFunVWW" : GoString))), stdgo.math.big.Big.testFunVWW) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMulWW" : GoString))), stdgo.math.big.Big.testMulWW) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMulAddWWW" : GoString))), stdgo.math.big.Big.testMulAddWWW) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestDivWW" : GoString))), stdgo.math.big.Big.testDivWW) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMulBits" : GoString))), stdgo.math.big.Big.testMulBits) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestNormBits" : GoString))), stdgo.math.big.Big.testNormBits) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFromBits" : GoString))), stdgo.math.big.Big.testFromBits) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestCalibrate" : GoString))), stdgo.math.big.Big.testCalibrate) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestDecimalString" : GoString))), stdgo.math.big.Big.testDecimalString) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestDecimalInit" : GoString))), stdgo.math.big.Big.testDecimalInit) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestDecimalRounding" : GoString))), stdgo.math.big.Big.testDecimalRounding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatZeroValue" : GoString))), stdgo.math.big.Big.testFloatZeroValue) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetPrec" : GoString))), stdgo.math.big.Big.testFloatSetPrec) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatMinPrec" : GoString))), stdgo.math.big.Big.testFloatMinPrec) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSign" : GoString))), stdgo.math.big.Big.testFloatSign) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatMantExp" : GoString))), stdgo.math.big.Big.testFloatMantExp) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatMantExpAliasing" : GoString))), stdgo.math.big.Big.testFloatMantExpAliasing) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetMantExp" : GoString))), stdgo.math.big.Big.testFloatSetMantExp) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatPredicates" : GoString))), stdgo.math.big.Big.testFloatPredicates) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatIsInt" : GoString))), stdgo.math.big.Big.testFloatIsInt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatRound" : GoString))), stdgo.math.big.Big.testFloatRound) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatRound24" : GoString))), stdgo.math.big.Big.testFloatRound24) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetUint64" : GoString))), stdgo.math.big.Big.testFloatSetUint64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetInt64" : GoString))), stdgo.math.big.Big.testFloatSetInt64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetFloat64" : GoString))), stdgo.math.big.Big.testFloatSetFloat64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetInt" : GoString))), stdgo.math.big.Big.testFloatSetInt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetRat" : GoString))), stdgo.math.big.Big.testFloatSetRat) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetInf" : GoString))), stdgo.math.big.Big.testFloatSetInf) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatUint64" : GoString))), stdgo.math.big.Big.testFloatUint64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatInt64" : GoString))), stdgo.math.big.Big.testFloatInt64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatFloat32" : GoString))), stdgo.math.big.Big.testFloatFloat32) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatFloat64" : GoString))), stdgo.math.big.Big.testFloatFloat64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatInt" : GoString))), stdgo.math.big.Big.testFloatInt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatRat" : GoString))), stdgo.math.big.Big.testFloatRat) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatAbs" : GoString))), stdgo.math.big.Big.testFloatAbs) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatNeg" : GoString))), stdgo.math.big.Big.testFloatNeg) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatInc" : GoString))), stdgo.math.big.Big.testFloatInc) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatAdd" : GoString))), stdgo.math.big.Big.testFloatAdd) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatAddRoundZero" : GoString))), stdgo.math.big.Big.testFloatAddRoundZero) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatAdd32" : GoString))), stdgo.math.big.Big.testFloatAdd32) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatAdd64" : GoString))), stdgo.math.big.Big.testFloatAdd64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue20490" : GoString))), stdgo.math.big.Big.testIssue20490) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatMul" : GoString))), stdgo.math.big.Big.testFloatMul) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatMul64" : GoString))), stdgo.math.big.Big.testFloatMul64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue6866" : GoString))), stdgo.math.big.Big.testIssue6866) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatQuo" : GoString))), stdgo.math.big.Big.testFloatQuo) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatQuoSmoke" : GoString))), stdgo.math.big.Big.testFloatQuoSmoke) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatArithmeticSpecialValues" : GoString))), stdgo.math.big.Big.testFloatArithmeticSpecialValues) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatArithmeticOverflow" : GoString))), stdgo.math.big.Big.testFloatArithmeticOverflow) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatArithmeticRounding" : GoString))), stdgo.math.big.Big.testFloatArithmeticRounding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatCmpSpecialValues" : GoString))), stdgo.math.big.Big.testFloatCmpSpecialValues) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSetFloat64String" : GoString))), stdgo.math.big.Big.testFloatSetFloat64String) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloat64Text" : GoString))), stdgo.math.big.Big.testFloat64Text) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatText" : GoString))), stdgo.math.big.Big.testFloatText) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatFormat" : GoString))), stdgo.math.big.Big.testFloatFormat) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatScan" : GoString))), stdgo.math.big.Big.testFloatScan) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatGobEncoding" : GoString))), stdgo.math.big.Big.testFloatGobEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatCorruptGob" : GoString))), stdgo.math.big.Big.testFloatCorruptGob) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatJSONEncoding" : GoString))), stdgo.math.big.Big.testFloatJSONEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestHilbert" : GoString))), stdgo.math.big.Big.testHilbert) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSignZ" : GoString))), stdgo.math.big.Big.testSignZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSetZ" : GoString))), stdgo.math.big.Big.testSetZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestAbsZ" : GoString))), stdgo.math.big.Big.testAbsZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSumZZ" : GoString))), stdgo.math.big.Big.testSumZZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestProdZZ" : GoString))), stdgo.math.big.Big.testProdZZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMul" : GoString))), stdgo.math.big.Big.testMul) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMulRangeZ" : GoString))), stdgo.math.big.Big.testMulRangeZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBinomial" : GoString))), stdgo.math.big.Big.testBinomial) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestDivisionSigns" : GoString))), stdgo.math.big.Big.testDivisionSigns) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBits" : GoString))), stdgo.math.big.Big.testBits) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSetBytes" : GoString))), stdgo.math.big.Big.testSetBytes) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBytes" : GoString))), stdgo.math.big.Big.testBytes) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestQuo" : GoString))), stdgo.math.big.Big.testQuo) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestQuoStepD6" : GoString))), stdgo.math.big.Big.testQuoStepD6) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBitLen" : GoString))), stdgo.math.big.Big.testBitLen) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestExp" : GoString))), stdgo.math.big.Big.testExp) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestGcd" : GoString))), stdgo.math.big.Big.testGcd) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRsh" : GoString))), stdgo.math.big.Big.testRsh) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRshSelf" : GoString))), stdgo.math.big.Big.testRshSelf) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestLsh" : GoString))), stdgo.math.big.Big.testLsh) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestLshSelf" : GoString))), stdgo.math.big.Big.testLshSelf) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestLshRsh" : GoString))), stdgo.math.big.Big.testLshRsh) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestCmpAbs" : GoString))), stdgo.math.big.Big.testCmpAbs) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIntCmpSelf" : GoString))), stdgo.math.big.Big.testIntCmpSelf) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestInt64" : GoString))), stdgo.math.big.Big.testInt64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestUint64" : GoString))), stdgo.math.big.Big.testUint64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBitSet" : GoString))), stdgo.math.big.Big.testBitSet) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestTrailingZeroBits" : GoString))), stdgo.math.big.Big.testTrailingZeroBits) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBitwise" : GoString))), stdgo.math.big.Big.testBitwise) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestNot" : GoString))), stdgo.math.big.Big.testNot) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestModInverse" : GoString))), stdgo.math.big.Big.testModInverse) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestModSqrt" : GoString))), stdgo.math.big.Big.testModSqrt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestJacobi" : GoString))), stdgo.math.big.Big.testJacobi) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestJacobiPanic" : GoString))), stdgo.math.big.Big.testJacobiPanic) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue2607" : GoString))), stdgo.math.big.Big.testIssue2607) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSqrt" : GoString))), stdgo.math.big.Big.testSqrt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue22830" : GoString))), stdgo.math.big.Big.testIssue22830) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFillBytes" : GoString))), stdgo.math.big.Big.testFillBytes) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIntText" : GoString))), stdgo.math.big.Big.testIntText) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestAppendText" : GoString))), stdgo.math.big.Big.testAppendText) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestGetString" : GoString))), stdgo.math.big.Big.testGetString) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSetString" : GoString))), stdgo.math.big.Big.testSetString) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFormat" : GoString))), stdgo.math.big.Big.testFormat) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestScan" : GoString))), stdgo.math.big.Big.testScan) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIntGobEncoding" : GoString))), stdgo.math.big.Big.testIntGobEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestGobEncodingNilIntInSlice" : GoString))), stdgo.math.big.Big.testGobEncodingNilIntInSlice) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIntJSONEncoding" : GoString))), stdgo.math.big.Big.testIntJSONEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIntXMLEncoding" : GoString))), stdgo.math.big.Big.testIntXMLEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestLinkerGC" : GoString))), stdgo.math.big.Big.testLinkerGC) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestCmp" : GoString))), stdgo.math.big.Big.testCmp) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSet" : GoString))), stdgo.math.big.Big.testSet) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFunNN" : GoString))), stdgo.math.big.Big.testFunNN) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMulRangeN" : GoString))), stdgo.math.big.Big.testMulRangeN) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMulUnbalanced" : GoString))), stdgo.math.big.Big.testMulUnbalanced) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestNLZ" : GoString))), stdgo.math.big.Big.testNLZ) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestShiftLeft" : GoString))), stdgo.math.big.Big.testShiftLeft) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestShiftRight" : GoString))), stdgo.math.big.Big.testShiftRight) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestModW" : GoString))), stdgo.math.big.Big.testModW) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMontgomery" : GoString))), stdgo.math.big.Big.testMontgomery) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestExpNN" : GoString))), stdgo.math.big.Big.testExpNN) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFibo" : GoString))), stdgo.math.big.Big.testFibo) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestBit" : GoString))), stdgo.math.big.Big.testBit) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSticky" : GoString))), stdgo.math.big.Big.testSticky) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSqr" : GoString))), stdgo.math.big.Big.testSqr) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestNatDiv" : GoString))), stdgo.math.big.Big.testNatDiv) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue37499" : GoString))), stdgo.math.big.Big.testIssue37499) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue42552" : GoString))), stdgo.math.big.Big.testIssue42552) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMaxBase" : GoString))), stdgo.math.big.Big.testMaxBase) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestString" : GoString))), stdgo.math.big.Big.testString) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestScanBase" : GoString))), stdgo.math.big.Big.testScanBase) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestScanPi" : GoString))), stdgo.math.big.Big.testScanPi) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestScanPiParallel" : GoString))), stdgo.math.big.Big.testScanPiParallel) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestStringPowers" : GoString))), stdgo.math.big.Big.testStringPowers) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestProbablyPrime" : GoString))), stdgo.math.big.Big.testProbablyPrime) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestMillerRabinPseudoprimes" : GoString))), stdgo.math.big.Big.testMillerRabinPseudoprimes) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestLucasPseudoprimes" : GoString))), stdgo.math.big.Big.testLucasPseudoprimes) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestZeroRat" : GoString))), stdgo.math.big.Big.testZeroRat) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatSign" : GoString))), stdgo.math.big.Big.testRatSign) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatCmp" : GoString))), stdgo.math.big.Big.testRatCmp) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIsInt" : GoString))), stdgo.math.big.Big.testIsInt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatAbs" : GoString))), stdgo.math.big.Big.testRatAbs) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatNeg" : GoString))), stdgo.math.big.Big.testRatNeg) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatInv" : GoString))), stdgo.math.big.Big.testRatInv) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatBin" : GoString))), stdgo.math.big.Big.testRatBin) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue820" : GoString))), stdgo.math.big.Big.testIssue820) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatSetFrac64Rat" : GoString))), stdgo.math.big.Big.testRatSetFrac64Rat) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue2379" : GoString))), stdgo.math.big.Big.testIssue2379) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue3521" : GoString))), stdgo.math.big.Big.testIssue3521) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloat32Distribution" : GoString))), stdgo.math.big.Big.testFloat32Distribution) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloat64Distribution" : GoString))), stdgo.math.big.Big.testFloat64Distribution) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestSetFloat64NonFinite" : GoString))), stdgo.math.big.Big.testSetFloat64NonFinite) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIsFinite" : GoString))), stdgo.math.big.Big.testIsFinite) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatSetInt64" : GoString))), stdgo.math.big.Big.testRatSetInt64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatSetUint64" : GoString))), stdgo.math.big.Big.testRatSetUint64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue34919" : GoString))), stdgo.math.big.Big.testIssue34919) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestDenomRace" : GoString))), stdgo.math.big.Big.testDenomRace) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestScanExponent" : GoString))), stdgo.math.big.Big.testScanExponent) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatSetString" : GoString))), stdgo.math.big.Big.testRatSetString) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatScan" : GoString))), stdgo.math.big.Big.testRatScan) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatString" : GoString))), stdgo.math.big.Big.testFloatString) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloat32SpecialCases" : GoString))), stdgo.math.big.Big.testFloat32SpecialCases) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloat64SpecialCases" : GoString))), stdgo.math.big.Big.testFloat64SpecialCases) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue31184" : GoString))), stdgo.math.big.Big.testIssue31184) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestIssue45910" : GoString))), stdgo.math.big.Big.testIssue45910) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatGobEncoding" : GoString))), stdgo.math.big.Big.testRatGobEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestGobEncodingNilRatInSlice" : GoString))), stdgo.math.big.Big.testGobEncodingNilRatInSlice) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatJSONEncoding" : GoString))), stdgo.math.big.Big.testRatJSONEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestRatXMLEncoding" : GoString))), stdgo.math.big.Big.testRatXMLEncoding) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSqrt64" : GoString))), stdgo.math.big.Big.testFloatSqrt64) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSqrt" : GoString))), stdgo.math.big.Big.testFloatSqrt) : stdgo.testing.Testing.InternalTest)),
((new stdgo.testing.Testing.InternalTest(((("TestFloatSqrtSpecial" : GoString))), stdgo.math.big.Big.testFloatSqrtSpecial) : stdgo.testing.Testing.InternalTest))) : Slice<stdgo.testing.Testing.InternalTest>));
var _benchmarks : Slice<stdgo.testing.Testing.InternalBenchmark> = ((new Slice<stdgo.testing.Testing.InternalBenchmark>(
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkAddVV" : GoString))), stdgo.math.big.Big.benchmarkAddVV) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkSubVV" : GoString))), stdgo.math.big.Big.benchmarkSubVV) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkAddVW" : GoString))), stdgo.math.big.Big.benchmarkAddVW) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkAddVWext" : GoString))), stdgo.math.big.Big.benchmarkAddVWext) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkSubVW" : GoString))), stdgo.math.big.Big.benchmarkSubVW) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkSubVWext" : GoString))), stdgo.math.big.Big.benchmarkSubVWext) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkMulAddVWW" : GoString))), stdgo.math.big.Big.benchmarkMulAddVWW) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkAddMulVVW" : GoString))), stdgo.math.big.Big.benchmarkAddMulVVW) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkDivWVW" : GoString))), stdgo.math.big.Big.benchmarkDivWVW) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkNonZeroShifts" : GoString))), stdgo.math.big.Big.benchmarkNonZeroShifts) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkDecimalConversion" : GoString))), stdgo.math.big.Big.benchmarkDecimalConversion) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkFloatString" : GoString))), stdgo.math.big.Big.benchmarkFloatString) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkFloatAdd" : GoString))), stdgo.math.big.Big.benchmarkFloatAdd) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkFloatSub" : GoString))), stdgo.math.big.Big.benchmarkFloatSub) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkParseFloatSmallExp" : GoString))), stdgo.math.big.Big.benchmarkParseFloatSmallExp) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkParseFloatLargeExp" : GoString))), stdgo.math.big.Big.benchmarkParseFloatLargeExp) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10x10" : GoString))), stdgo.math.big.Big.benchmarkGCD10x10) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10x100" : GoString))), stdgo.math.big.Big.benchmarkGCD10x100) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10x1000" : GoString))), stdgo.math.big.Big.benchmarkGCD10x1000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10x10000" : GoString))), stdgo.math.big.Big.benchmarkGCD10x10000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10x100000" : GoString))), stdgo.math.big.Big.benchmarkGCD10x100000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD100x100" : GoString))), stdgo.math.big.Big.benchmarkGCD100x100) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD100x1000" : GoString))), stdgo.math.big.Big.benchmarkGCD100x1000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD100x10000" : GoString))), stdgo.math.big.Big.benchmarkGCD100x10000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD100x100000" : GoString))), stdgo.math.big.Big.benchmarkGCD100x100000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD1000x1000" : GoString))), stdgo.math.big.Big.benchmarkGCD1000x1000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD1000x10000" : GoString))), stdgo.math.big.Big.benchmarkGCD1000x10000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD1000x100000" : GoString))), stdgo.math.big.Big.benchmarkGCD1000x100000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10000x10000" : GoString))), stdgo.math.big.Big.benchmarkGCD10000x10000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD10000x100000" : GoString))), stdgo.math.big.Big.benchmarkGCD10000x100000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkGCD100000x100000" : GoString))), stdgo.math.big.Big.benchmarkGCD100000x100000) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkHilbert" : GoString))), stdgo.math.big.Big.benchmarkHilbert) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkBinomial" : GoString))), stdgo.math.big.Big.benchmarkBinomial) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkQuoRem" : GoString))), stdgo.math.big.Big.benchmarkQuoRem) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkExp" : GoString))), stdgo.math.big.Big.benchmarkExp) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkExp2" : GoString))), stdgo.math.big.Big.benchmarkExp2) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkBitset" : GoString))), stdgo.math.big.Big.benchmarkBitset) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkBitsetNeg" : GoString))), stdgo.math.big.Big.benchmarkBitsetNeg) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkBitsetOrig" : GoString))), stdgo.math.big.Big.benchmarkBitsetOrig) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkBitsetNegOrig" : GoString))), stdgo.math.big.Big.benchmarkBitsetNegOrig) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkModSqrt225_Tonelli" : GoString))), stdgo.math.big.Big.benchmarkModSqrt225_Tonelli) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkModSqrt225_3Mod4" : GoString))), stdgo.math.big.Big.benchmarkModSqrt225_3Mod4) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkModSqrt231_Tonelli" : GoString))), stdgo.math.big.Big.benchmarkModSqrt231_Tonelli) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkModSqrt231_5Mod8" : GoString))), stdgo.math.big.Big.benchmarkModSqrt231_5Mod8) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkModInverse" : GoString))), stdgo.math.big.Big.benchmarkModInverse) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkSqrt" : GoString))), stdgo.math.big.Big.benchmarkSqrt) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkIntSqr" : GoString))), stdgo.math.big.Big.benchmarkIntSqr) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkDiv" : GoString))), stdgo.math.big.Big.benchmarkDiv) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkMul" : GoString))), stdgo.math.big.Big.benchmarkMul) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkNatMul" : GoString))), stdgo.math.big.Big.benchmarkNatMul) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkZeroShifts" : GoString))), stdgo.math.big.Big.benchmarkZeroShifts) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkExp3Power" : GoString))), stdgo.math.big.Big.benchmarkExp3Power) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkFibo" : GoString))), stdgo.math.big.Big.benchmarkFibo) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkNatSqr" : GoString))), stdgo.math.big.Big.benchmarkNatSqr) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkNatSetBytes" : GoString))), stdgo.math.big.Big.benchmarkNatSetBytes) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkScanPi" : GoString))), stdgo.math.big.Big.benchmarkScanPi) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkStringPiParallel" : GoString))), stdgo.math.big.Big.benchmarkStringPiParallel) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkScan" : GoString))), stdgo.math.big.Big.benchmarkScan) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkString" : GoString))), stdgo.math.big.Big.benchmarkString) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkLeafSize" : GoString))), stdgo.math.big.Big.benchmarkLeafSize) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkProbablyPrime" : GoString))), stdgo.math.big.Big.benchmarkProbablyPrime) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkRatCmp" : GoString))), stdgo.math.big.Big.benchmarkRatCmp) : stdgo.testing.Testing.InternalBenchmark)),
((new stdgo.testing.Testing.InternalBenchmark(((("BenchmarkFloatSqrt" : GoString))), stdgo.math.big.Big.benchmarkFloatSqrt) : stdgo.testing.Testing.InternalBenchmark))) : Slice<stdgo.testing.Testing.InternalBenchmark>));
var _fuzzTargets : Slice<stdgo.testing.Testing.InternalFuzzTarget> = ((new Slice<stdgo.testing.Testing.InternalFuzzTarget>() : Slice<stdgo.testing.Testing.InternalFuzzTarget>));
var _examples : Slice<stdgo.testing.Testing.InternalExample> = ((new Slice<stdgo.testing.Testing.InternalExample>(
((new stdgo.testing.Testing.InternalExample(((("Example_eConvergents" : GoString))), stdgo.math.big_test.Big_test.example_eConvergents, ((("2/1           = 2.00000000\n3/1           = 3.00000000\n8/3           = 2.66666667\n11/4          = 2.75000000\n19/7          = 2.71428571\n87/32         = 2.71875000\n106/39        = 2.71794872\n193/71        = 2.71830986\n1264/465      = 2.71827957\n1457/536      = 2.71828358\n2721/1001     = 2.71828172\n23225/8544    = 2.71828184\n25946/9545    = 2.71828182\n49171/18089   = 2.71828183\n517656/190435 = 2.71828183\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleRat_SetString" : GoString))), stdgo.math.big_test.Big_test.exampleRat_SetString, ((("3.142\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleInt_SetString" : GoString))), stdgo.math.big_test.Big_test.exampleInt_SetString, ((("420\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleFloat_SetString" : GoString))), stdgo.math.big_test.Big_test.exampleFloat_SetString, ((("3.14159\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleRat_Scan" : GoString))), stdgo.math.big_test.Big_test.exampleRat_Scan, ((("3/2\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleInt_Scan" : GoString))), stdgo.math.big_test.Big_test.exampleInt_Scan, ((("18446744073709551617\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleFloat_Scan" : GoString))), stdgo.math.big_test.Big_test.exampleFloat_Scan, ((("1.19282e+99\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("Example_fibonacci" : GoString))), stdgo.math.big_test.Big_test.example_fibonacci, ((("1344719667586153181419716641724567886890850696275767987106294472017884974410332069524504824747437757\nfalse\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("Example_sqrt2" : GoString))), stdgo.math.big_test.Big_test.example_sqrt2, ((("sqrt(2) = 1.41421356237309504880168872420969807856967187537695\nerror = 0.000000e+00\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleFloat_Add" : GoString))), stdgo.math.big_test.Big_test.exampleFloat_Add, ((("x = 1000 (0x.fap+10, prec = 64, acc = Exact)\ny = 2.718281828 (0x.adf85458248cd8p+2, prec = 53, acc = Exact)\nz = 1002.718282 (0x.faadf854p+10, prec = 32, acc = Below)\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleFloat_shift" : GoString))), stdgo.math.big_test.Big_test.exampleFloat_shift, ((("0.015625\n0.03125\n0.0625\n0.125\n0.25\n0.5\n1\n2\n4\n8\n16\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleFloat_Cmp" : GoString))), stdgo.math.big_test.Big_test.exampleFloat_Cmp, ((("   x     y  cmp\n---------------\n-Inf  -Inf    0\n-Inf  -1.2   -1\n-Inf    -0   -1\n-Inf     0   -1\n-Inf   1.2   -1\n-Inf  +Inf   -1\n\n-1.2  -Inf    1\n-1.2  -1.2    0\n-1.2    -0   -1\n-1.2     0   -1\n-1.2   1.2   -1\n-1.2  +Inf   -1\n\n  -0  -Inf    1\n  -0  -1.2    1\n  -0    -0    0\n  -0     0    0\n  -0   1.2   -1\n  -0  +Inf   -1\n\n   0  -Inf    1\n   0  -1.2    1\n   0    -0    0\n   0     0    0\n   0   1.2   -1\n   0  +Inf   -1\n\n 1.2  -Inf    1\n 1.2  -1.2    1\n 1.2    -0    1\n 1.2     0    1\n 1.2   1.2    0\n 1.2  +Inf   -1\n\n+Inf  -Inf    1\n+Inf  -1.2    1\n+Inf    -0    1\n+Inf     0    1\n+Inf   1.2    1\n+Inf  +Inf    0\n" : GoString))), false) : stdgo.testing.Testing.InternalExample)),
((new stdgo.testing.Testing.InternalExample(((("ExampleRoundingMode" : GoString))), stdgo.math.big_test.Big_test.exampleRoundingMode, ((("   x  ToNearestEven  ToNearestAway  ToZero  AwayFromZero  ToNegativeInf  ToPositiveInf\n 2.6              3              3       2             3              2              3\n 2.5              2              3       2             3              2              3\n 2.1              2              2       2             3              2              3\n-2.1             -2             -2      -2            -3             -3             -2\n-2.5             -2             -3      -2            -3             -3             -2\n-2.6             -3             -3      -2            -3             -3             -2\n" : GoString))), false) : stdgo.testing.Testing.InternalExample))) : Slice<stdgo.testing.Testing.InternalExample>));
function main():Void {
        var _m:Ref<stdgo.testing.Testing.M> = stdgo.testing.Testing.mainStart(((new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        stdgo.os.Os.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo.testing.internal.testdeps.Testdeps.importPath = ((("math/big" : GoString)));
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
