package stdgo.testing.internal.testdeps;
@:invalid var __go2hxdoc__package : Dynamic;
@:invalid var _matchPat : Dynamic;
@:invalid var _matchRe : Dynamic;
@:invalid var importPath : Dynamic;
@:invalid var _log : Dynamic;
@:invalid typedef TestDeps = Dynamic;
@:invalid typedef T_testLog = Dynamic;
@:invalid typedef TestDeps_asInterface = Dynamic;
@:invalid typedef TestDeps_static_extension = Dynamic;
@:invalid typedef T_testLog_asInterface = Dynamic;
@:invalid typedef T_testLog_static_extension = Dynamic;
