package _internal.bytes_test;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.bytes.Bytes;
var _indexTests : stdgo.Slice<_internal.bytes_test.Bytes_test_BinOpTest.BinOpTest> = (new stdgo.Slice<_internal.bytes_test.Bytes_test_BinOpTest.BinOpTest>(55, 55, ...[
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__(), (0 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(stdgo.Go.str()?.__copy__(), ("a" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(stdgo.Go.str()?.__copy__(), ("foo" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fo" : stdgo.GoString), ("foo" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("foo" : stdgo.GoString), ("baz" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("foo" : stdgo.GoString), ("foo" : stdgo.GoString), (0 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("oofofoofooo" : stdgo.GoString), ("f" : stdgo.GoString), (2 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("oofofoofooo" : stdgo.GoString), ("foo" : stdgo.GoString), (4 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("barfoobarfoo" : stdgo.GoString), ("foo" : stdgo.GoString), (3 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("foo" : stdgo.GoString), stdgo.Go.str()?.__copy__(), (0 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("foo" : stdgo.GoString), ("o" : stdgo.GoString), (1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("abcABCabc" : stdgo.GoString), ("A" : stdgo.GoString), (3 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(stdgo.Go.str()?.__copy__(), ("a" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("x" : stdgo.GoString), ("a" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("x" : stdgo.GoString), ("x" : stdgo.GoString), (0 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("abc" : stdgo.GoString), ("a" : stdgo.GoString), (0 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("abc" : stdgo.GoString), ("b" : stdgo.GoString), (1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("abc" : stdgo.GoString), ("c" : stdgo.GoString), (2 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("abc" : stdgo.GoString), ("x" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("barfoobarfooyyyzzzyyyzzzyyyzzzyyyxxxzzzyyy" : stdgo.GoString), ("x" : stdgo.GoString), (33 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofooofoboo" : stdgo.GoString), ("oo" : stdgo.GoString), (7 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofoboo" : stdgo.GoString), ("ob" : stdgo.GoString), (11 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofoboo" : stdgo.GoString), ("boo" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofoboo" : stdgo.GoString), ("oboo" : stdgo.GoString), (11 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoooboo" : stdgo.GoString), ("fooo" : stdgo.GoString), (8 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofoboo" : stdgo.GoString), ("foboo" : stdgo.GoString), (10 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofoboo" : stdgo.GoString), ("fofob" : stdgo.GoString), (8 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffof" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffof" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofo" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofo" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofoo" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofoo" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofoob" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofoob" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofooba" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofooba" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofoobar" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofoobar" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofoobarf" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofoobarf" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofoobarfo" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofoobarfo" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foffofoobarfoo" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("foffofoobarfoo" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("ofoffofoobarfoo" : stdgo.GoString), (12 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("ofoffofoobarfoo" : stdgo.GoString), (11 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("fofoffofoobarfoo" : stdgo.GoString), (11 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofofofoffofoobarfoo" : stdgo.GoString), ("fofoffofoobarfoo" : stdgo.GoString), (10 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("fofofofofoofofoffofoobarfoo" : stdgo.GoString), ("foobars" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("foofyfoobarfoobar" : stdgo.GoString), ("y" : stdgo.GoString), (4 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("oooooooooooooooooooooo" : stdgo.GoString), ("r" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("oxoxoxoxoxoxoxoxoxoxoxoy" : stdgo.GoString), ("oy" : stdgo.GoString), (22 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("oxoxoxoxoxoxoxoxoxoxoxox" : stdgo.GoString), ("oy" : stdgo.GoString), (-1 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest),
(new _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest(("000000000000000000000000000000000000000000000000000000000000000000000001" : stdgo.GoString), ("0000000000000000000000000000000000000000000000000000000000000000001" : stdgo.GoString), (5 : stdgo.GoInt)) : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest)].concat([for (i in 55 ... (55 > 55 ? 55 : 55 : stdgo.GoInt).toBasic()) ({} : _internal.bytes_test.Bytes_test_BinOpTest.BinOpTest)])) : stdgo.Slice<_internal.bytes_test.Bytes_test_BinOpTest.BinOpTest>);
