package _internal.bytes_test;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.bytes.Bytes;
var _trimNilTests : stdgo.Slice<_internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest> = (new stdgo.Slice<_internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest>(29, 29, ...[
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(2, 2, ...[(97 : stdgo.GoUInt8), (97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("ab" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(2, 2, ...[(97 : stdgo.GoUInt8), (98 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("ab" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("Trim" : stdgo.GoString), (("☺" : stdgo.GoString) : stdgo.Slice<stdgo.GoUInt8>), ("☺" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(2, 2, ...[(97 : stdgo.GoUInt8), (97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("ab" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(2, 2, ...[(97 : stdgo.GoUInt8), (98 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("ab" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimLeft" : stdgo.GoString), (("☺" : stdgo.GoString) : stdgo.Slice<stdgo.GoUInt8>), ("☺" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(2, 2, ...[(97 : stdgo.GoUInt8), (97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("ab" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(2, 2, ...[(97 : stdgo.GoUInt8), (98 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("ab" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimRight" : stdgo.GoString), (("☺" : stdgo.GoString) : stdgo.Slice<stdgo.GoUInt8>), ("☺" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimPrefix" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimPrefix" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimPrefix" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimPrefix" : stdgo.GoString), (("☺" : stdgo.GoString) : stdgo.Slice<stdgo.GoUInt8>), ("☺" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimSuffix" : stdgo.GoString), (null : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (null : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimSuffix" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), stdgo.Go.str()?.__copy__(), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimSuffix" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[(97 : stdgo.GoUInt8)]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>), ("a" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest),
(new _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest(("TrimSuffix" : stdgo.GoString), (("☺" : stdgo.GoString) : stdgo.Slice<stdgo.GoUInt8>), ("☺" : stdgo.GoString), (new stdgo.Slice<stdgo.GoUInt8>(0, 0, ...[]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>)) : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest)].concat([for (i in 29 ... (29 > 29 ? 29 : 29 : stdgo.GoInt).toBasic()) ({} : _internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest)])) : stdgo.Slice<_internal.bytes_test.Bytes_test_TrimNilTest.TrimNilTest>);
