package _internal.sort_test;
import stdgo._internal.sort.Sort;
import stdgo._internal.sort.Sort;
var _data : stdgo.Slice<stdgo.GoInt> = {
        var s = new stdgo.Slice<stdgo.GoInt>(14, 0).__setNumber32__();
        s[0] = (-10 : stdgo.GoInt);
        s[1] = (-5 : stdgo.GoInt);
        s[2] = (0 : stdgo.GoInt);
        s[3] = (1 : stdgo.GoInt);
        s[4] = (2 : stdgo.GoInt);
        s[5] = (3 : stdgo.GoInt);
        s[6] = (5 : stdgo.GoInt);
        s[7] = (7 : stdgo.GoInt);
        s[8] = (11 : stdgo.GoInt);
        s[9] = (100 : stdgo.GoInt);
        s[10] = (100 : stdgo.GoInt);
        s[11] = (100 : stdgo.GoInt);
        s[12] = (1000 : stdgo.GoInt);
        s[13] = (10000 : stdgo.GoInt);
        s;
    };
