package stdgo._internal.html.template;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.internal.godebug.Godebug;
import stdgo._internal.regexp.Regexp;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.text.template.parse.Parse;
import stdgo._internal.html.Html;
import stdgo._internal.text.template.Template;
import stdgo._internal.encoding.json.Json;
import stdgo._internal.path.filepath.Filepath;
import stdgo._internal.io.fs.Fs;
import stdgo._internal.os.Os;
import stdgo._internal.path.Path;
import stdgo._internal.strconv.Strconv;
var _jsRegexpReplacementTable : stdgo.Slice<stdgo.GoString> = {
        var s = new stdgo.Slice<stdgo.GoString>(126, 0).__setString__();
        s[0] = ("\\u0000" : stdgo.GoString);
        s[9] = ("\\t" : stdgo.GoString);
        s[10] = ("\\n" : stdgo.GoString);
        s[11] = ("\\u000b" : stdgo.GoString);
        s[12] = ("\\f" : stdgo.GoString);
        s[13] = ("\\r" : stdgo.GoString);
        s[34] = ("\\u0022" : stdgo.GoString);
        s[36] = ("\\$" : stdgo.GoString);
        s[38] = ("\\u0026" : stdgo.GoString);
        s[39] = ("\\u0027" : stdgo.GoString);
        s[40] = ("\\(" : stdgo.GoString);
        s[41] = ("\\)" : stdgo.GoString);
        s[42] = ("\\*" : stdgo.GoString);
        s[43] = ("\\u002b" : stdgo.GoString);
        s[45] = ("\\-" : stdgo.GoString);
        s[46] = ("\\." : stdgo.GoString);
        s[47] = ("\\/" : stdgo.GoString);
        s[60] = ("\\u003c" : stdgo.GoString);
        s[62] = ("\\u003e" : stdgo.GoString);
        s[63] = ("\\?" : stdgo.GoString);
        s[91] = ("\\[" : stdgo.GoString);
        s[92] = ("\\\\" : stdgo.GoString);
        s[93] = ("\\]" : stdgo.GoString);
        s[94] = ("\\^" : stdgo.GoString);
        s[123] = ("\\{" : stdgo.GoString);
        s[124] = ("\\|" : stdgo.GoString);
        s[125] = ("\\}" : stdgo.GoString);
        s;
    };
