package stdgo._internal.internal.xcoff;
import stdgo._internal.os.Os;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.debug.dwarf.Dwarf;
@:keep @:follow @:using(stdgo._internal.internal.xcoff.Xcoff_LoaderHeader32_static_extension.LoaderHeader32_static_extension) typedef LoaderHeader32Pointer = stdgo.Pointer<stdgo._internal.internal.xcoff.Xcoff_LoaderHeader32.LoaderHeader32>;
