package stdgo._internal.slices_test;
import stdgo._internal.slices.Slices;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>(43, 43, ...[
(new stdgo._internal.testing.Testing.InternalTest(("TestEqual" : stdgo.GoString), stdgo._internal.slices.Slices.testEqual) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEqualFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testEqualFunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCompare" : stdgo.GoString), stdgo._internal.slices.Slices.testCompare) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCompareFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testCompareFunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIndex" : stdgo.GoString), stdgo._internal.slices.Slices.testIndex) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIndexFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testIndexFunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestContains" : stdgo.GoString), stdgo._internal.slices.Slices.testContains) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestContainsFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testContainsFunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInsert" : stdgo.GoString), stdgo._internal.slices.Slices.testInsert) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInsertOverlap" : stdgo.GoString), stdgo._internal.slices.Slices.testInsertOverlap) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDelete" : stdgo.GoString), stdgo._internal.slices.Slices.testDelete) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDeleteFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testDeleteFunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDeletePanics" : stdgo.GoString), stdgo._internal.slices.Slices.testDeletePanics) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestClone" : stdgo.GoString), stdgo._internal.slices.Slices.testClone) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCompact" : stdgo.GoString), stdgo._internal.slices.Slices.testCompact) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCompactFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testCompactFunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestGrow" : stdgo.GoString), stdgo._internal.slices.Slices.testGrow) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestClip" : stdgo.GoString), stdgo._internal.slices.Slices.testClip) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestReverse" : stdgo.GoString), stdgo._internal.slices.Slices.testReverse) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestReplace" : stdgo.GoString), stdgo._internal.slices.Slices.testReplace) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestReplacePanics" : stdgo.GoString), stdgo._internal.slices.Slices.testReplacePanics) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestReplaceOverlap" : stdgo.GoString), stdgo._internal.slices.Slices.testReplaceOverlap) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestRotate" : stdgo.GoString), stdgo._internal.slices.Slices.testRotate) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInsertGrowthRate" : stdgo.GoString), stdgo._internal.slices.Slices.testInsertGrowthRate) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestReplaceGrowthRate" : stdgo.GoString), stdgo._internal.slices.Slices.testReplaceGrowthRate) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInference" : stdgo.GoString), stdgo._internal.slices.Slices.testInference) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIntSorts" : stdgo.GoString), stdgo._internal.slices.Slices.testIntSorts) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStringSorts" : stdgo.GoString), stdgo._internal.slices.Slices.testStringSorts) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStructSorts" : stdgo.GoString), stdgo._internal.slices.Slices.testStructSorts) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSortIntSlice" : stdgo.GoString), stdgo._internal.slices.Slices.testSortIntSlice) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSortFuncIntSlice" : stdgo.GoString), stdgo._internal.slices.Slices.testSortFuncIntSlice) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSortFloat64Slice" : stdgo.GoString), stdgo._internal.slices.Slices.testSortFloat64Slice) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSortFloat64SliceWithNaNs" : stdgo.GoString), stdgo._internal.slices.Slices.testSortFloat64SliceWithNaNs) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSortStringSlice" : stdgo.GoString), stdgo._internal.slices.Slices.testSortStringSlice) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSortLarge_Random" : stdgo.GoString), stdgo._internal.slices.Slices.testSortLarge_Random) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStability" : stdgo.GoString), stdgo._internal.slices.Slices.testStability) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMinMax" : stdgo.GoString), stdgo._internal.slices.Slices.testMinMax) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMinMaxNaNs" : stdgo.GoString), stdgo._internal.slices.Slices.testMinMaxNaNs) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMinMaxPanics" : stdgo.GoString), stdgo._internal.slices.Slices.testMinMaxPanics) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestBinarySearch" : stdgo.GoString), stdgo._internal.slices.Slices.testBinarySearch) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestBinarySearchInts" : stdgo.GoString), stdgo._internal.slices.Slices.testBinarySearchInts) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestBinarySearchFloats" : stdgo.GoString), stdgo._internal.slices.Slices.testBinarySearchFloats) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestBinarySearchFunc" : stdgo.GoString), stdgo._internal.slices.Slices.testBinarySearchFunc) : stdgo._internal.testing.Testing.InternalTest)].concat([for (i in 43 ... (43 > 43 ? 43 : 43 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>(21, 21, ...[
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkEqualFunc_Large" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkEqualFunc_Large) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkIndex_Large" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkIndex_Large) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkIndexFunc_Large" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkIndexFunc_Large) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCompact" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkCompact) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCompact_Large" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkCompact_Large) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCompactFunc_Large" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkCompactFunc_Large) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkReplace" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkReplace) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSortInts" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSortInts) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSlicesSortInts" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSlicesSortInts) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSlicesSortInts_Sorted" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSlicesSortInts_Sorted) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSlicesSortInts_Reversed" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSlicesSortInts_Reversed) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkIntsAreSorted" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkIntsAreSorted) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkIsSorted" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkIsSorted) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSortStrings" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSortStrings) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSortStrings_Sorted" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSortStrings_Sorted) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSlicesSortStrings" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSlicesSortStrings) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSlicesSortStrings_Sorted" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSlicesSortStrings_Sorted) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSortStructs" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSortStructs) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSortFuncStructs" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkSortFuncStructs) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkBinarySearchFloats" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkBinarySearchFloats) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkBinarySearchFuncStruct" : stdgo.GoString), stdgo._internal.slices.Slices.benchmarkBinarySearchFuncStruct) : stdgo._internal.testing.Testing.InternalBenchmark)].concat([for (i in 21 ... (21 > 21 ? 21 : 21 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>(26, 26, ...[
(new stdgo._internal.testing.Testing.InternalExample(("ExampleBinarySearch" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleBinarySearch, ("Vera: 2 true\nBill: 1 false\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleBinarySearchFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleBinarySearchFunc, ("Bob: 1 true\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCompact" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleCompact, ("[0 1 2 3 5 8]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCompactFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleCompactFunc, ("[bob alice Vera]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCompare" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleCompare, ("Equal: 0\nV < X: -1\nV > C: 1\n3 > 2: 1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCompareFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleCompareFunc, ("1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleContainsFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleContainsFunc, ("Has a negative: true\nHas an odd number: false\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleDelete" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleDelete, ("[a e]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleDeleteFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleDeleteFunc, ("[0 2 8]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleEqual" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleEqual, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleEqualFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleEqualFunc, ("true\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleIndex" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleIndex, ("2\n-1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleIndexFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleIndexFunc, ("First negative at index 2\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleInsert" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleInsert, ("[Alice Bill Billie Bob Vera Zac]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleIsSorted" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleIsSorted, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleIsSortedFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleIsSortedFunc, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleMax" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleMax, ("42\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleMaxFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleMaxFunc, ("Alice\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleMin" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleMin, ("-10\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleMinFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleMinFunc, ("Bob\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleReplace" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleReplace, ("[Alice Bill Billie Cat Zac]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleReverse" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleReverse, ("[VERA Bob alice]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSort" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleSort, ("[-10 0 8 42]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSortFunc_caseInsensitive" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleSortFunc_caseInsensitive, ("[alice Bob VERA]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSortFunc_multiField" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleSortFunc_multiField, ("[{Alice 20} {Alice 55} {Bob 24} {Gopher 13}]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSortStableFunc" : stdgo.GoString), stdgo._internal.slices_test.Slices_test.exampleSortStableFunc, ("[{Alice 20} {Alice 55} {Bob 24} {Gopher 13}]\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample)].concat([for (i in 26 ... (26 > 26 ? 26 : 26 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo._internal.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        Sys.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo._internal.testing.internal.testdeps.Testdeps.importPath = ("slices" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
