package stdgo._internal.net.mail;
import stdgo._internal.errors.Errors;
import stdgo._internal.net.textproto.Textproto;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.io.Io;
import stdgo._internal.strings.Strings;
import stdgo._internal.time.Time;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.log.Log;
@:keep @:follow @:using(stdgo._internal.net.mail.Mail_AddressParser_static_extension.AddressParser_static_extension) typedef AddressParserPointer = stdgo.Pointer<stdgo._internal.net.mail.Mail_AddressParser.AddressParser>;
