package stdgo._internal.internal.abi;
var _kindNames : stdgo.Slice<stdgo.GoString> = {
        var s = new stdgo.Slice<stdgo.GoString>(27, 0).__setString__();
        s[0] = ("invalid" : stdgo.GoString);
        s[1] = ("bool" : stdgo.GoString);
        s[2] = ("int" : stdgo.GoString);
        s[3] = ("int8" : stdgo.GoString);
        s[4] = ("int16" : stdgo.GoString);
        s[5] = ("int32" : stdgo.GoString);
        s[6] = ("int64" : stdgo.GoString);
        s[7] = ("uint" : stdgo.GoString);
        s[8] = ("uint8" : stdgo.GoString);
        s[9] = ("uint16" : stdgo.GoString);
        s[10] = ("uint32" : stdgo.GoString);
        s[11] = ("uint64" : stdgo.GoString);
        s[12] = ("uintptr" : stdgo.GoString);
        s[13] = ("float32" : stdgo.GoString);
        s[14] = ("float64" : stdgo.GoString);
        s[15] = ("complex64" : stdgo.GoString);
        s[16] = ("complex128" : stdgo.GoString);
        s[17] = ("array" : stdgo.GoString);
        s[18] = ("chan" : stdgo.GoString);
        s[19] = ("func" : stdgo.GoString);
        s[20] = ("interface" : stdgo.GoString);
        s[21] = ("map" : stdgo.GoString);
        s[22] = ("ptr" : stdgo.GoString);
        s[23] = ("slice" : stdgo.GoString);
        s[24] = ("string" : stdgo.GoString);
        s[25] = ("struct" : stdgo.GoString);
        s[26] = ("unsafe.Pointer" : stdgo.GoString);
        s;
    };
