package _internal.testing.iotest_dot_test;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest>(15, 15, ...[
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestWriteLogger" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testWriteLogger.testWriteLogger) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestWriteLogger_errorOnWrite" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testWriteLogger_errorOnWrite.testWriteLogger_errorOnWrite) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestReadLogger" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testReadLogger.testReadLogger) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestReadLogger_errorOnRead" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testReadLogger_errorOnRead.testReadLogger_errorOnRead) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestOneByteReader_nonEmptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testOneByteReader_nonEmptyReader.testOneByteReader_nonEmptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestOneByteReader_emptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testOneByteReader_emptyReader.testOneByteReader_emptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestHalfReader_nonEmptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testHalfReader_nonEmptyReader.testHalfReader_nonEmptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestHalfReader_emptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testHalfReader_emptyReader.testHalfReader_emptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestTimeOutReader_nonEmptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testTimeOutReader_nonEmptyReader.testTimeOutReader_nonEmptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestTimeOutReader_emptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testTimeOutReader_emptyReader.testTimeOutReader_emptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDataErrReader_nonEmptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testDataErrReader_nonEmptyReader.testDataErrReader_nonEmptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDataErrReader_emptyReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testDataErrReader_emptyReader.testDataErrReader_emptyReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestErrReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testErrReader.testErrReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestStringsReader" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testStringsReader.testStringsReader) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestTruncateWriter" : stdgo.GoString), stdgo._internal.testing.iotest.Iotest_testTruncateWriter.testTruncateWriter) : stdgo._internal.testing.Testing_InternalTest.InternalTest)].concat([for (i in 15 ... (15 > 15 ? 15 : 15 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_InternalTest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest>);
