package stdgo._internal.crypto.internal.nistec.fiat;
function _p521Selectznz(_out1:stdgo.Ref<stdgo.GoArray<stdgo.GoUInt64>>, _arg1:stdgo._internal.crypto.internal.nistec.fiat.Fiat_t_p521uint1.T_p521Uint1, _arg2:stdgo.Ref<stdgo.GoArray<stdgo.GoUInt64>>, _arg3:stdgo.Ref<stdgo.GoArray<stdgo.GoUInt64>>):Void {
        var _x1:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x1__pointer__ = stdgo.Go.pointer(_x1);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x1__pointer__, _arg1, _arg2[(0 : stdgo.GoInt)], _arg3[(0 : stdgo.GoInt)]);
        var _x2:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x2__pointer__ = stdgo.Go.pointer(_x2);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x2__pointer__, _arg1, _arg2[(1 : stdgo.GoInt)], _arg3[(1 : stdgo.GoInt)]);
        var _x3:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x3__pointer__ = stdgo.Go.pointer(_x3);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x3__pointer__, _arg1, _arg2[(2 : stdgo.GoInt)], _arg3[(2 : stdgo.GoInt)]);
        var _x4:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x4__pointer__ = stdgo.Go.pointer(_x4);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x4__pointer__, _arg1, _arg2[(3 : stdgo.GoInt)], _arg3[(3 : stdgo.GoInt)]);
        var _x5:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x5__pointer__ = stdgo.Go.pointer(_x5);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x5__pointer__, _arg1, _arg2[(4 : stdgo.GoInt)], _arg3[(4 : stdgo.GoInt)]);
        var _x6:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x6__pointer__ = stdgo.Go.pointer(_x6);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x6__pointer__, _arg1, _arg2[(5 : stdgo.GoInt)], _arg3[(5 : stdgo.GoInt)]);
        var _x7:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x7__pointer__ = stdgo.Go.pointer(_x7);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x7__pointer__, _arg1, _arg2[(6 : stdgo.GoInt)], _arg3[(6 : stdgo.GoInt)]);
        var _x8:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x8__pointer__ = stdgo.Go.pointer(_x8);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x8__pointer__, _arg1, _arg2[(7 : stdgo.GoInt)], _arg3[(7 : stdgo.GoInt)]);
        var _x9:stdgo.GoUInt64 = (0 : stdgo.GoUInt64);
        var _x9__pointer__ = stdgo.Go.pointer(_x9);
        stdgo._internal.crypto.internal.nistec.fiat.Fiat__p521cmovznzu64._p521CmovznzU64(_x9__pointer__, _arg1, _arg2[(8 : stdgo.GoInt)], _arg3[(8 : stdgo.GoInt)]);
        _out1[(0 : stdgo.GoInt)] = _x1;
        _out1[(1 : stdgo.GoInt)] = _x2;
        _out1[(2 : stdgo.GoInt)] = _x3;
        _out1[(3 : stdgo.GoInt)] = _x4;
        _out1[(4 : stdgo.GoInt)] = _x5;
        _out1[(5 : stdgo.GoInt)] = _x6;
        _out1[(6 : stdgo.GoInt)] = _x7;
        _out1[(7 : stdgo.GoInt)] = _x8;
        _out1[(8 : stdgo.GoInt)] = _x9;
    }
