package stdgo.time_test;

import stdgo.StdGoTypes;
import stdgo.Error;
import stdgo.Go;
import stdgo.GoString;
import stdgo.Pointer;
import stdgo.Slice;
import stdgo.GoArray;
import stdgo.GoMap;
import stdgo.Chan;

var _tests:Slice<stdgo.testing.Testing.InternalTest> = (new Slice<stdgo.testing.Testing.InternalTest>(0, 0,
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNextStdChunk") : GoString),
		stdgo.time_test.Time_test.testNextStdChunk) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestRFC3339Conversion") : GoString),
		stdgo.time_test.Time_test.testRFC3339Conversion) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFormat") : GoString), stdgo.time_test.Time_test.testFormat) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestGoString") : GoString), stdgo.time_test.Time_test.testGoString) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFormatSingleDigits") : GoString),
		stdgo.time_test.Time_test.testFormatSingleDigits) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFormatShortYear") : GoString),
		stdgo.time_test.Time_test.testFormatShortYear) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParse") : GoString), stdgo.time_test.Time_test.testParse) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseDayOutOfRange") : GoString),
		stdgo.time_test.Time_test.testParseDayOutOfRange) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseInLocation") : GoString),
		stdgo.time_test.Time_test.testParseInLocation) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLoadLocationZipFile") : GoString),
		stdgo.time_test.Time_test.testLoadLocationZipFile) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestRubyParse") : GoString),
		stdgo.time_test.Time_test.testRubyParse) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFormatAndParse") : GoString),
		stdgo.time_test.Time_test.testFormatAndParse) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseTimeZone") : GoString),
		stdgo.time_test.Time_test.testParseTimeZone) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseErrors") : GoString),
		stdgo.time_test.Time_test.testParseErrors) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNoonIs12PM") : GoString),
		stdgo.time_test.Time_test.testNoonIs12PM) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMidnightIs12AM") : GoString),
		stdgo.time_test.Time_test.testMidnightIs12AM) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("Test12PMIsNoon") : GoString),
		stdgo.time_test.Time_test.test12PMIsNoon) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("Test12AMIsMidnight") : GoString),
		stdgo.time_test.Time_test.test12AMIsMidnight) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMissingZone") : GoString),
		stdgo.time_test.Time_test.testMissingZone) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMinutesInTimeZone") : GoString),
		stdgo.time_test.Time_test.testMinutesInTimeZone) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseSecondsInTimeZone") : GoString),
		stdgo.time_test.Time_test.testParseSecondsInTimeZone) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFormatSecondsInTimeZone") : GoString),
		stdgo.time_test.Time_test.testFormatSecondsInTimeZone) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestUnderscoreTwoThousand") : GoString),
		stdgo.time_test.Time_test.testUnderscoreTwoThousand) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestStd0xParseError") : GoString),
		stdgo.time_test.Time_test.testStd0xParseError) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseMonthOutOfRange") : GoString),
		stdgo.time_test.Time_test.testParseMonthOutOfRange) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseYday") : GoString),
		stdgo.time_test.Time_test.testParseYday) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestQuote") : GoString), stdgo.time_test.Time_test.testQuote) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFormatFractionalSecondSeparators") : GoString),
		stdgo.time_test.Time_test.testFormatFractionalSecondSeparators) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseFractionalSecondsLongerThanNineDigits") : GoString),
		stdgo.time_test.Time_test.testParseFractionalSecondsLongerThanNineDigits) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestHasMonotonicClock") : GoString),
		stdgo.time_test.Time_test.testHasMonotonicClock) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMonotonicAdd") : GoString),
		stdgo.time_test.Time_test.testMonotonicAdd) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMonotonicSub") : GoString),
		stdgo.time_test.Time_test.testMonotonicSub) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMonotonicOverflow") : GoString),
		stdgo.time_test.Time_test.testMonotonicOverflow) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMonotonicString") : GoString),
		stdgo.time_test.Time_test.testMonotonicString) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestSleep") : GoString), stdgo.time_test.Time_test.testSleep) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAfterFunc") : GoString),
		stdgo.time_test.Time_test.testAfterFunc) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAfterStress") : GoString),
		stdgo.time_test.Time_test.testAfterStress) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAfter") : GoString), stdgo.time_test.Time_test.testAfter) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAfterTick") : GoString),
		stdgo.time_test.Time_test.testAfterTick) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAfterStop") : GoString),
		stdgo.time_test.Time_test.testAfterStop) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAfterQueuing") : GoString),
		stdgo.time_test.Time_test.testAfterQueuing) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimerStopStress") : GoString),
		stdgo.time_test.Time_test.testTimerStopStress) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestSleepZeroDeadlock") : GoString),
		stdgo.time_test.Time_test.testSleepZeroDeadlock) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestReset") : GoString), stdgo.time_test.Time_test.testReset) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestOverflowSleep") : GoString),
		stdgo.time_test.Time_test.testOverflowSleep) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestIssue5745") : GoString),
		stdgo.time_test.Time_test.testIssue5745) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestOverflowPeriodRuntimeTimer") : GoString),
		stdgo.time_test.Time_test.testOverflowPeriodRuntimeTimer) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestZeroTimerResetPanics") : GoString),
		stdgo.time_test.Time_test.testZeroTimerResetPanics) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestZeroTimerStopPanics") : GoString),
		stdgo.time_test.Time_test.testZeroTimerStopPanics) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestZeroTimer") : GoString),
		stdgo.time_test.Time_test.testZeroTimer) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimerModifiedEarlier") : GoString),
		stdgo.time_test.Time_test.testTimerModifiedEarlier) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAdjustTimers") : GoString),
		stdgo.time_test.Time_test.testAdjustTimers) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTicker") : GoString), stdgo.time_test.Time_test.testTicker) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTickerStopWithDirectInitialization") : GoString),
		stdgo.time_test.Time_test.testTickerStopWithDirectInitialization) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTeardown") : GoString), stdgo.time_test.Time_test.testTeardown) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTick") : GoString), stdgo.time_test.Time_test.testTick) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNewTickerLtZeroDuration") : GoString),
		stdgo.time_test.Time_test.testNewTickerLtZeroDuration) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTickerResetLtZeroDuration") : GoString),
		stdgo.time_test.Time_test.testTickerResetLtZeroDuration) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestZoneData") : GoString), stdgo.time_test.Time_test.testZoneData) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestSecondsToUTC") : GoString),
		stdgo.time_test.Time_test.testSecondsToUTC) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNanosecondsToUTC") : GoString),
		stdgo.time_test.Time_test.testNanosecondsToUTC) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestSecondsToLocalTime") : GoString),
		stdgo.time_test.Time_test.testSecondsToLocalTime) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNanosecondsToLocalTime") : GoString),
		stdgo.time_test.Time_test.testNanosecondsToLocalTime) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestSecondsToUTCAndBack") : GoString),
		stdgo.time_test.Time_test.testSecondsToUTCAndBack) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNanosecondsToUTCAndBack") : GoString),
		stdgo.time_test.Time_test.testNanosecondsToUTCAndBack) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestUnixMilli") : GoString),
		stdgo.time_test.Time_test.testUnixMilli) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestUnixMicro") : GoString),
		stdgo.time_test.Time_test.testUnixMicro) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTruncateRound") : GoString),
		stdgo.time_test.Time_test.testTruncateRound) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestISOWeek") : GoString), stdgo.time_test.Time_test.testISOWeek) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestYearDay") : GoString), stdgo.time_test.Time_test.testYearDay) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationString") : GoString),
		stdgo.time_test.Time_test.testDurationString) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDate") : GoString), stdgo.time_test.Time_test.testDate) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAddDate") : GoString), stdgo.time_test.Time_test.testAddDate) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDaysIn") : GoString), stdgo.time_test.Time_test.testDaysIn) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestAddToExactSecond") : GoString),
		stdgo.time_test.Time_test.testAddToExactSecond) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimeGob") : GoString), stdgo.time_test.Time_test.testTimeGob) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestInvalidTimeGob") : GoString),
		stdgo.time_test.Time_test.testInvalidTimeGob) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNotGobEncodableTime") : GoString),
		stdgo.time_test.Time_test.testNotGobEncodableTime) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimeJSON") : GoString), stdgo.time_test.Time_test.testTimeJSON) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestInvalidTimeJSON") : GoString),
		stdgo.time_test.Time_test.testInvalidTimeJSON) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestNotJSONEncodableTime") : GoString),
		stdgo.time_test.Time_test.testNotJSONEncodableTime) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseDuration") : GoString),
		stdgo.time_test.Time_test.testParseDuration) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseDurationErrors") : GoString),
		stdgo.time_test.Time_test.testParseDurationErrors) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestParseDurationRoundTrip") : GoString),
		stdgo.time_test.Time_test.testParseDurationRoundTrip) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLocationRace") : GoString),
		stdgo.time_test.Time_test.testLocationRace) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestCountMallocs") : GoString),
		stdgo.time_test.Time_test.testCountMallocs) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLoadFixed") : GoString),
		stdgo.time_test.Time_test.testLoadFixed) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestSub") : GoString), stdgo.time_test.Time_test.testSub) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationNanoseconds") : GoString),
		stdgo.time_test.Time_test.testDurationNanoseconds) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationMicroseconds") : GoString),
		stdgo.time_test.Time_test.testDurationMicroseconds) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationMilliseconds") : GoString),
		stdgo.time_test.Time_test.testDurationMilliseconds) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationSeconds") : GoString),
		stdgo.time_test.Time_test.testDurationSeconds) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationMinutes") : GoString),
		stdgo.time_test.Time_test.testDurationMinutes) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationHours") : GoString),
		stdgo.time_test.Time_test.testDurationHours) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationTruncate") : GoString),
		stdgo.time_test.Time_test.testDurationTruncate) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationRound") : GoString),
		stdgo.time_test.Time_test.testDurationRound) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDurationAbs") : GoString),
		stdgo.time_test.Time_test.testDurationAbs) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestDefaultLoc") : GoString),
		stdgo.time_test.Time_test.testDefaultLoc) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMarshalBinaryZeroTime") : GoString),
		stdgo.time_test.Time_test.testMarshalBinaryZeroTime) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMarshalBinaryVersion2") : GoString),
		stdgo.time_test.Time_test.testMarshalBinaryVersion2) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestZeroMonthString") : GoString),
		stdgo.time_test.Time_test.testZeroMonthString) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestWeekdayString") : GoString),
		stdgo.time_test.Time_test.testWeekdayString) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestReadFileLimit") : GoString),
		stdgo.time_test.Time_test.testReadFileLimit) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestConcurrentTimerReset") : GoString),
		stdgo.time_test.Time_test.testConcurrentTimerReset) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestConcurrentTimerResetStop") : GoString),
		stdgo.time_test.Time_test.testConcurrentTimerResetStop) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimeIsDST") : GoString),
		stdgo.time_test.Time_test.testTimeIsDST) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimeAddSecOverflow") : GoString),
		stdgo.time_test.Time_test.testTimeAddSecOverflow) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTimeWithZoneTransition") : GoString),
		stdgo.time_test.Time_test.testTimeWithZoneTransition) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestZoneBounds") : GoString),
		stdgo.time_test.Time_test.testZoneBounds) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestEmbeddedTZData") : GoString),
		stdgo.time_test.Time_test.testEmbeddedTZData) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestEnvVarUsage") : GoString),
		stdgo.time_test.Time_test.testEnvVarUsage) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestBadLocationErrMsg") : GoString),
		stdgo.time_test.Time_test.testBadLocationErrMsg) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLoadLocationValidatesNames") : GoString),
		stdgo.time_test.Time_test.testLoadLocationValidatesNames) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestVersion3") : GoString), stdgo.time_test.Time_test.testVersion3) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestFirstZone") : GoString),
		stdgo.time_test.Time_test.testFirstZone) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLocationNames") : GoString),
		stdgo.time_test.Time_test.testLocationNames) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLoadLocationFromTZData") : GoString),
		stdgo.time_test.Time_test.testLoadLocationFromTZData) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestEarlyLocation") : GoString),
		stdgo.time_test.Time_test.testEarlyLocation) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestMalformedTZData") : GoString),
		stdgo.time_test.Time_test.testMalformedTZData) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestLoadLocationFromTZDataSlim") : GoString),
		stdgo.time_test.Time_test.testLoadLocationFromTZDataSlim) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTzset") : GoString), stdgo.time_test.Time_test.testTzset) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTzsetName") : GoString),
		stdgo.time_test.Time_test.testTzsetName) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTzsetOffset") : GoString),
		stdgo.time_test.Time_test.testTzsetOffset) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest((Go.str("TestTzsetRule") : GoString),
		stdgo.time_test.Time_test.testTzsetRule) : stdgo.testing.Testing.InternalTest)) : Slice<stdgo.testing.Testing.InternalTest>);

var _benchmarks:Slice<stdgo.testing.Testing.InternalBenchmark> = (new Slice<stdgo.testing.Testing.InternalBenchmark>(0, 0,
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkAfterFunc") : GoString),
		stdgo.time_test.Time_test.benchmarkAfterFunc) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkAfter") : GoString),
		stdgo.time_test.Time_test.benchmarkAfter) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkStop") : GoString),
		stdgo.time_test.Time_test.benchmarkStop) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkSimultaneousAfterFunc") : GoString),
		stdgo.time_test.Time_test.benchmarkSimultaneousAfterFunc) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkStartStop") : GoString),
		stdgo.time_test.Time_test.benchmarkStartStop) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkReset") : GoString),
		stdgo.time_test.Time_test.benchmarkReset) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkSleep") : GoString),
		stdgo.time_test.Time_test.benchmarkSleep) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkParallelTimerLatency") : GoString),
		stdgo.time_test.Time_test.benchmarkParallelTimerLatency) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkStaggeredTickerLatency") : GoString),
		stdgo.time_test.Time_test.benchmarkStaggeredTickerLatency) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkTicker") : GoString),
		stdgo.time_test.Time_test.benchmarkTicker) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkTickerReset") : GoString),
		stdgo.time_test.Time_test.benchmarkTickerReset) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkTickerResetNaive") : GoString),
		stdgo.time_test.Time_test.benchmarkTickerResetNaive) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkNow") : GoString),
		stdgo.time_test.Time_test.benchmarkNow) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkNowUnixNano") : GoString),
		stdgo.time_test.Time_test.benchmarkNowUnixNano) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkNowUnixMilli") : GoString),
		stdgo.time_test.Time_test.benchmarkNowUnixMilli) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkNowUnixMicro") : GoString),
		stdgo.time_test.Time_test.benchmarkNowUnixMicro) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkFormat") : GoString),
		stdgo.time_test.Time_test.benchmarkFormat) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkFormatNow") : GoString),
		stdgo.time_test.Time_test.benchmarkFormatNow) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkMarshalJSON") : GoString),
		stdgo.time_test.Time_test.benchmarkMarshalJSON) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkMarshalText") : GoString),
		stdgo.time_test.Time_test.benchmarkMarshalText) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkParse") : GoString),
		stdgo.time_test.Time_test.benchmarkParse) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkParseDuration") : GoString),
		stdgo.time_test.Time_test.benchmarkParseDuration) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkHour") : GoString),
		stdgo.time_test.Time_test.benchmarkHour) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkSecond") : GoString),
		stdgo.time_test.Time_test.benchmarkSecond) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkYear") : GoString),
		stdgo.time_test.Time_test.benchmarkYear) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkDay") : GoString),
		stdgo.time_test.Time_test.benchmarkDay) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark((Go.str("BenchmarkISOWeek") : GoString),
		stdgo.time_test.Time_test.benchmarkISOWeek) : stdgo.testing.Testing.InternalBenchmark)) : Slice<stdgo.testing.Testing.InternalBenchmark>);

var _fuzzTargets:Slice<stdgo.testing.Testing.InternalFuzzTarget> = (new Slice<stdgo.testing.Testing.InternalFuzzTarget>(0,
	0) : Slice<stdgo.testing.Testing.InternalFuzzTarget>);

var _examples:Slice<stdgo.testing.Testing.InternalExample> = (new Slice<stdgo.testing.Testing.InternalExample>(0, 0,
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Round") : GoString), stdgo.time_test.Time_test.exampleDuration_Round,
		(Go.str("d.Round(   1ns) = 1h15m30.918273645s\nd.Round(   1µs) = 1h15m30.918274s\nd.Round(   1ms) = 1h15m30.918s\nd.Round(    1s) = 1h15m31s\nd.Round(    2s) = 1h15m30s\nd.Round(  1m0s) = 1h16m0s\nd.Round( 10m0s) = 1h20m0s\nd.Round(1h0m0s) = 1h0m0s\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_String") : GoString), stdgo.time_test.Time_test.exampleDuration_String,
		(Go.str("1h2m0.3s\n300ms\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Truncate") : GoString), stdgo.time_test.Time_test.exampleDuration_Truncate,
		(Go.str("d.Truncate(   1ns) = 1h15m30.918273645s\nd.Truncate(   1µs) = 1h15m30.918273s\nd.Truncate(   1ms) = 1h15m30.918s\nd.Truncate(    1s) = 1h15m30s\nd.Truncate(    2s) = 1h15m30s\nd.Truncate(  1m0s) = 1h15m0s\nd.Truncate( 10m0s) = 1h10m0s\nd.Truncate(1h0m0s) = 1h0m0s\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleParseDuration") : GoString), stdgo.time_test.Time_test.exampleParseDuration,
		(Go.str("10h0m0s\n1h10m10s\nThere are 4210 seconds in 1h10m10s.\nThere are 1000 nanoseconds in 1µs.\nThere are 1.00e-06 seconds in 1µs.\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Hours") : GoString), stdgo.time_test.Time_test.exampleDuration_Hours,
		(Go.str("I\'ve got 4.5 hours of work left.\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Microseconds") : GoString), stdgo.time_test.Time_test.exampleDuration_Microseconds,
		(Go.str("One second is 1000000 microseconds.\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Milliseconds") : GoString), stdgo.time_test.Time_test.exampleDuration_Milliseconds,
		(Go.str("One second is 1000 milliseconds.\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Minutes") : GoString), stdgo.time_test.Time_test.exampleDuration_Minutes,
		(Go.str("The movie is 90 minutes long.\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Nanoseconds") : GoString), stdgo.time_test.Time_test.exampleDuration_Nanoseconds,
		(Go.str("One microsecond is 1000 nanoseconds.\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDuration_Seconds") : GoString), stdgo.time_test.Time_test.exampleDuration_Seconds,
		(Go.str("Take off in t-90 seconds.\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleDate") : GoString), stdgo.time_test.Time_test.exampleDate,
		(Go.str("Go launched at 2009-11-10 15:00:00 -0800 PST\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Format") : GoString), stdgo.time_test.Time_test.exampleTime_Format,
		(Go.str("default format: 2015-02-25 11:06:39 -0800 PST\nUnix format: Wed Feb 25 11:06:39 PST 2015\nSame, in UTC: Wed Feb 25 19:06:39 UTC 2015\nin Shanghai with seconds: 2015-02-26T03:06:39 +080000\nin Shanghai with colon seconds: 2015-02-26T03:06:39 +08:00:00\n\nFormats:\n\nBasic full date  \"Mon Jan 2 15:04:05 MST 2006\" gives \"Wed Feb 25 11:06:39 PST 2015\"\nBasic short date \"2006/01/02\" gives \"2015/02/25\"\nAM/PM            \"3PM==3pm==15h\" gives \"11AM==11am==11h\"\nNo fraction      \"Mon Jan _2 15:04:05 MST 2006\" gives \"Wed Feb 25 11:06:39 PST 2015\"\n0s for fraction  \"15:04:05.00000\" gives \"11:06:39.12340\"\n9s for fraction  \"15:04:05.99999999\" gives \"11:06:39.1234\"\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Format_pad") : GoString), stdgo.time_test.Time_test.exampleTime_Format_pad,
		(Go.str("Unix             \"Mon Jan _2 15:04:05 MST 2006\" gives \"Sat Mar  7 11:06:39 PST 2015\"\nNo pad           \"<2>\" gives \"<7>\"\nSpaces           \"<_2>\" gives \"< 7>\"\nZeros            \"<02>\" gives \"<07>\"\nSuppressed pad   \"04:05\" gives \"06:39\"\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_GoString") : GoString), stdgo.time_test.Time_test.exampleTime_GoString,
		(Go.str("time.Date(2009, time.November, 10, 23, 0, 0, 0, time.UTC)\ntime.Date(2009, time.November, 10, 23, 1, 0, 0, time.UTC)\ntime.Date(2009, time.December, 10, 23, 1, 0, 0, time.UTC)\ntime.Date(2013, time.February, 3, 19, 54, 0, 0, time.UTC)\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleParse") : GoString), stdgo.time_test.Time_test.exampleParse,
		(Go.str("2013-02-03 19:54:00 -0800 PST\n2013-02-03 00:00:00 +0000 UTC\n2006-01-02 15:04:05 +0000 UTC\n2006-01-02 15:04:05 +0700 +0700\nerror parsing time \"2006-01-02T15:04:05Z07:00\": extra text: \"07:00\"\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleParseInLocation") : GoString), stdgo.time_test.Time_test.exampleParseInLocation,
		(Go.str("2012-07-09 05:02:00 +0200 CEST\n2012-07-09 00:00:00 +0200 CEST\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleUnix") : GoString), stdgo.time_test.Time_test.exampleUnix,
		(Go.str("1257894000\n2009-11-10 23:00:00 +0000 UTC\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleUnixMicro") : GoString), stdgo.time_test.Time_test.exampleUnixMicro,
		(Go.str("1257894000000000\n2009-11-10 23:00:00 +0000 UTC\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleUnixMilli") : GoString), stdgo.time_test.Time_test.exampleUnixMilli,
		(Go.str("1257894000000\n2009-11-10 23:00:00 +0000 UTC\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Unix") : GoString), stdgo.time_test.Time_test.exampleTime_Unix,
		(Go.str("2001-09-09 01:46:40 +0000 UTC\n2001-09-09 01:46:40 +0000 UTC\n2001-09-09 01:46:40 +0000 UTC\n1000000000\n1000000000000000000\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Round") : GoString), stdgo.time_test.Time_test.exampleTime_Round,
		(Go.str("t.Round(   1ns) = 12:15:30.918273645\nt.Round(   1µs) = 12:15:30.918274\nt.Round(   1ms) = 12:15:30.918\nt.Round(    1s) = 12:15:31\nt.Round(    2s) = 12:15:30\nt.Round(  1m0s) = 12:16:00\nt.Round( 10m0s) = 12:20:00\nt.Round(1h0m0s) = 12:00:00\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Truncate") : GoString), stdgo.time_test.Time_test.exampleTime_Truncate,
		(Go.str("t.Truncate(  1ns) = 12:15:30.918273645\nt.Truncate(  1µs) = 12:15:30.918273\nt.Truncate(  1ms) = 12:15:30.918\nt.Truncate(   1s) = 12:15:30\nt.Truncate(   2s) = 12:15:30\nt.Truncate( 1m0s) = 12:15:00\nt.Truncate(10m0s) = 12:10:00\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleLoadLocation") : GoString), stdgo.time_test.Time_test.exampleLoadLocation,
		(Go.str("2018-08-30 05:00:00 -0700 PDT\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleLocation") : GoString), stdgo.time_test.Time_test.exampleLocation,
		(Go.str("true\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Add") : GoString), stdgo.time_test.Time_test.exampleTime_Add,
		(Go.str("start = 2009-01-01 12:00:00 +0000 UTC\nstart.Add(time.Second * 10) = 2009-01-01 12:00:10 +0000 UTC\nstart.Add(time.Minute * 10) = 2009-01-01 12:10:00 +0000 UTC\nstart.Add(time.Hour * 10) = 2009-01-01 22:00:00 +0000 UTC\nstart.Add(time.Hour * 24 * 10) = 2009-01-11 12:00:00 +0000 UTC\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_AddDate") : GoString), stdgo.time_test.Time_test.exampleTime_AddDate,
		(Go.str("oneDayLater: start.AddDate(0, 0, 1) = 2009-01-02 00:00:00 +0000 UTC\noneMonthLater: start.AddDate(0, 1, 0) = 2009-02-01 00:00:00 +0000 UTC\noneYearLater: start.AddDate(1, 0, 0) = 2010-01-01 00:00:00 +0000 UTC\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_After") : GoString), stdgo.time_test.Time_test.exampleTime_After,
		(Go.str("year3000.After(year2000) = true\nyear2000.After(year3000) = false\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Before") : GoString), stdgo.time_test.Time_test.exampleTime_Before,
		(Go.str("year2000.Before(year3000) = true\nyear3000.Before(year2000) = false\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Date") : GoString), stdgo.time_test.Time_test.exampleTime_Date,
		(Go.str("year = 2000\nmonth = February\nday = 1\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Day") : GoString), stdgo.time_test.Time_test.exampleTime_Day,
		(Go.str("day = 1\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Equal") : GoString), stdgo.time_test.Time_test.exampleTime_Equal,
		(Go.str("datesEqualUsingEqualOperator = false\ndatesEqualUsingFunction = true\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_String") : GoString), stdgo.time_test.Time_test.exampleTime_String,
		(Go.str("withNanoseconds = 2000-02-01 12:13:14.000000015 +0000 UTC\nwithoutNanoseconds = 2000-02-01 12:13:14 +0000 UTC\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_Sub") : GoString), stdgo.time_test.Time_test.exampleTime_Sub,
		(Go.str("difference = 12h0m0s\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleTime_AppendFormat") : GoString), stdgo.time_test.Time_test.exampleTime_AppendFormat,
		(Go.str("Time: 11:00AM\n") : GoString), false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample((Go.str("ExampleFixedZone") : GoString), stdgo.time_test.Time_test.exampleFixedZone,
		(Go.str("The time is: 10 Nov 09 23:00 UTC-8\n") : GoString),
		false) : stdgo.testing.Testing.InternalExample)) : Slice<stdgo.testing.Testing.InternalExample>);

function main():Void {
	var _m = stdgo.testing.Testing.mainStart({
		final __self__ = new stdgo.testing.internal.testdeps.Testdeps.TestDeps_wrapper((new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps));
		__self__.checkCorpus = #if !macro function(__0:Slice<AnyInterface>,
				__1:Slice<stdgo.reflect.Reflect.Type>):stdgo.Error return
				(new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps).checkCorpus(__0,
					__1) #else null #end;
		__self__.coordinateFuzzing = #if !macro function(__0:Duration, __1:GoInt64, __2:Duration, __3:GoInt64, __4:GoInt, __5:Slice<{
			var parent:GoString;
			var path:GoString;
			var data:Slice<GoUInt8>;
			var values:Slice<AnyInterface>;
			var generation:GoInt;
			var isSeed:Bool;
		}>,
				__6:Slice<stdgo.reflect.Reflect.Type>, __7:GoString,
				__8:GoString):stdgo.Error return (new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps)
				.coordinateFuzzing(__0, __1, __2, __3, __4, __5, __6, __7, __8) #else null #end;
		__self__.importPath = #if !macro function():GoString return
			(new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps).importPath() #else null #end;
		__self__.matchString = #if !macro function(_name:GoString, _source:GoString):{var _0:Bool; var _1:stdgo.Error;}
			return (new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps).matchString(_name,
				_source) #else null #end;
		__self__.readCorpus = #if !macro function(__0:GoString, __1:Slice<stdgo.reflect.Reflect.Type>):{var _0:Slice<{
			var parent:GoString;
			var path:GoString;
			var data:Slice<GoUInt8>;
			var values:Slice<AnyInterface>;
			var generation:GoInt;
			var isSeed:Bool;
		}>; var _1:stdgo.Error;}
			return (new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps).readCorpus(__0,
				__1) #else null #end;
		__self__.resetCoverage = #if !macro function():Void(new stdgo.testing.internal.testdeps.Testdeps.TestDeps()
			:stdgo.testing.internal.testdeps.Testdeps.TestDeps).resetCoverage() #else null #end;
		__self__.runFuzzWorker = #if !macro function(__0:({
			var parent:GoString;
			var path:GoString;
			var data:Slice<GoUInt8>;
			var values:Slice<AnyInterface>;
			var generation:GoInt;
			var isSeed:Bool;
		}) -> stdgo.Error):stdgo.Error return (new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps)
			.runFuzzWorker(__0) #else null #end;
		__self__.setPanicOnExit0 = #if !macro function(__0:Bool):Void(new stdgo.testing.internal.testdeps.Testdeps.TestDeps()
			:stdgo.testing.internal.testdeps.Testdeps.TestDeps).setPanicOnExit0(__0) #else null #end;
		__self__.snapshotCoverage = #if !macro function():Void(new stdgo.testing.internal.testdeps.Testdeps.TestDeps()
			:stdgo.testing.internal.testdeps.Testdeps.TestDeps).snapshotCoverage() #else null #end;
		__self__.startCPUProfile = #if !macro function(_w:stdgo.io.Io.Writer):stdgo.Error return
			(new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps).startCPUProfile(_w) #else null #end;
		__self__.startTestLog = #if !macro function(_w:stdgo.io.Io.Writer):Void(new stdgo.testing.internal.testdeps.Testdeps.TestDeps()
			:stdgo.testing.internal.testdeps.Testdeps.TestDeps).startTestLog(_w) #else null #end;
		__self__.stopCPUProfile = #if !macro function():Void(new stdgo.testing.internal.testdeps.Testdeps.TestDeps()
			:stdgo.testing.internal.testdeps.Testdeps.TestDeps).stopCPUProfile() #else null #end;
		__self__.stopTestLog = #if !macro function():stdgo.Error return
			(new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps).stopTestLog() #else null #end;
		__self__.writeProfileTo = #if !macro function(__0:GoString, __1:stdgo.io.Io.Writer,
				__2:GoInt):stdgo.Error return (new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps)
				.writeProfileTo(__0, __1, __2) #else null #end;
		__self__;
	}, _tests, _benchmarks, _fuzzTargets, _examples);
	Sys.exit(_m.run());
}

@:keep var _ = {
	try {
		stdgo.testing.internal.testdeps.Testdeps.importPath = (Go.str("time") : GoString);
	} catch (__exception__)
		if (__exception__.message != "__return__")
			throw __exception__;
	true;
};
