package stdgo._internal.net.textproto;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.net.Net;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
@:keep @:follow @:using(stdgo._internal.net.textproto.Textproto_T_sequencer_static_extension.T_sequencer_static_extension) typedef T_sequencerPointer = stdgo.Pointer<stdgo._internal.net.textproto.Textproto_T_sequencer.T_sequencer>;
