package stdgo.crypto.internal.nistec.fiat;
typedef T_p521NonMontgomeryDomainFieldElement = stdgo._internal.crypto.internal.nistec.fiat.Fiat_T_p521NonMontgomeryDomainFieldElement.T_p521NonMontgomeryDomainFieldElement;
