package stdgo.crypto.internal.nistec.fiat;
typedef T_p384MontgomeryDomainFieldElement = stdgo._internal.crypto.internal.nistec.fiat.Fiat_T_p384MontgomeryDomainFieldElement.T_p384MontgomeryDomainFieldElement;
