package stdgo._internal.math.big;
import stdgo._internal.strings.Strings;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.flag.Flag;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.testing.Testing;
import stdgo._internal.math.Math;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.encoding.gob.Gob;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.io.Io;
import stdgo._internal.encoding.json.Json;
import stdgo._internal.testing.quick.Quick;
import stdgo._internal.encoding.hex.Hex;
import stdgo._internal.encoding.xml.Xml;
import stdgo._internal.path.filepath.Filepath;
import stdgo._internal.os.Os;
import stdgo._internal.os.exec.Exec;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.sort.Sort;
var _prodVWW : stdgo.Slice<stdgo._internal.math.big.Big_T_argVWW.T_argVWW> = (new stdgo.Slice<stdgo._internal.math.big.Big_T_argVWW.T_argVWW>(23, 23, ...[
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW() : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (0u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (0u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (1u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(992u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (1u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(22793u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (23u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(22800u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (23u32 : stdgo._internal.math.big.Big_Word.Word), (7u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (22793u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (23u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(7u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (22793u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (23u32 : stdgo._internal.math.big.Big_Word.Word), (7u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(7893475u32 : stdgo._internal.math.big.Big_Word.Word), (7395495u32 : stdgo._internal.math.big.Big_Word.Word), (798547395u32 : stdgo._internal.math.big.Big_Word.Word), (68943u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(7893475u32 : stdgo._internal.math.big.Big_Word.Word), (7395495u32 : stdgo._internal.math.big.Big_Word.Word), (798547395u32 : stdgo._internal.math.big.Big_Word.Word), (68943u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (0u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (894375984u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (894375984u32 : stdgo._internal.math.big.Big_Word.Word), (991u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-2u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (2u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (1u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (2u32 : stdgo._internal.math.big.Big_Word.Word), (1u32 : stdgo._internal.math.big.Big_Word.Word), (1u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-128u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (128u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (127u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-64u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(1, 1, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (128u32 : stdgo._internal.math.big.Big_Word.Word), (64u32 : stdgo._internal.math.big.Big_Word.Word), (127u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(-128u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (128u32 : stdgo._internal.math.big.Big_Word.Word), (0u32 : stdgo._internal.math.big.Big_Word.Word), (127u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW),
(new stdgo._internal.math.big.Big_T_argVWW.T_argVWW((new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(-64u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (new stdgo.Slice<stdgo._internal.math.big.Big_Word.Word>(4, 4, ...[(-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word), (-1u32 : stdgo._internal.math.big.Big_Word.Word)]).__setNumber32__() : stdgo._internal.math.big.Big_T_nat.T_nat), (128u32 : stdgo._internal.math.big.Big_Word.Word), (64u32 : stdgo._internal.math.big.Big_Word.Word), (127u32 : stdgo._internal.math.big.Big_Word.Word)) : stdgo._internal.math.big.Big_T_argVWW.T_argVWW)].concat([for (i in 23 ... (23 > 23 ? 23 : 23 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.math.big.Big_T_argVWW.T_argVWW)])) : stdgo.Slice<stdgo._internal.math.big.Big_T_argVWW.T_argVWW>);
