package stdgo._internal.math.big;
function testFloatSqrtSpecial(_t:stdgo.Ref<stdgo._internal.testing.Testing_t_.T_>):Void {
        for (__8 => _test in (new stdgo.Slice<stdgo._internal.math.big.Big_t__struct_69.T__struct_69>(3, 3, ...[({ _x : stdgo._internal.math.big.Big_newfloat.newFloat((0 : stdgo.GoFloat64)), _want : stdgo._internal.math.big.Big_newfloat.newFloat((0 : stdgo.GoFloat64)) } : stdgo._internal.math.big.Big_t__struct_69.T__struct_69), ({ _x : stdgo._internal.math.big.Big_newfloat.newFloat((0 : stdgo.GoFloat64)), _want : stdgo._internal.math.big.Big_newfloat.newFloat((0 : stdgo.GoFloat64)) } : stdgo._internal.math.big.Big_t__struct_69.T__struct_69), ({ _x : stdgo._internal.math.big.Big_newfloat.newFloat(stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))), _want : stdgo._internal.math.big.Big_newfloat.newFloat(stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))) } : stdgo._internal.math.big.Big_t__struct_69.T__struct_69)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({ _x : (null : stdgo.Ref<stdgo._internal.math.big.Big_float_.Float_>), _want : (null : stdgo.Ref<stdgo._internal.math.big.Big_float_.Float_>) } : stdgo._internal.math.big.Big_t__struct_69.T__struct_69)])) : stdgo.Slice<stdgo._internal.math.big.Big_t__struct_69.T__struct_69>)) {
            var _got = @:check2r (stdgo.Go.setRef(({} : stdgo._internal.math.big.Big_float_.Float_)) : stdgo.Ref<stdgo._internal.math.big.Big_float_.Float_>).sqrt(_test._x);
            if ((((@:checkr _got ?? throw "null pointer dereference")._neg != (@:checkr _test._want ?? throw "null pointer dereference")._neg) || ((@:checkr _got ?? throw "null pointer dereference")._form != (@:checkr _test._want ?? throw "null pointer dereference")._form) : Bool)) {
                @:check2r _t.errorf(("Sqrt(%v) = %v (neg: %v); want %v (neg: %v)" : stdgo.GoString), stdgo.Go.toInterface(stdgo.Go.asInterface(_test._x)), stdgo.Go.toInterface(stdgo.Go.asInterface(_got)), stdgo.Go.toInterface((@:checkr _got ?? throw "null pointer dereference")._neg), stdgo.Go.toInterface(stdgo.Go.asInterface(_test._want)), stdgo.Go.toInterface((@:checkr _test._want ?? throw "null pointer dereference")._neg));
            };
        };
    }
