package stdgo._internal.math.big;
var _scanTests : stdgo.Slice<stdgo._internal.math.big.Big_t__struct_51.T__struct_51> = (new stdgo.Slice<stdgo._internal.math.big.Big_t__struct_51.T__struct_51>(15, 15, ...[
({ _input : ("1010" : stdgo.GoString), _format : ("%b" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("0b1010" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("12" : stdgo.GoString), _format : ("%o" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("012" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("10" : stdgo.GoString), _format : ("%d" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("10" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("a" : stdgo.GoString), _format : ("%x" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("0xa" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("A" : stdgo.GoString), _format : ("%X" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("-A" : stdgo.GoString), _format : ("%X" : stdgo.GoString), _output : ("-10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("+0b1011001" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("89" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("0xA" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("10" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("0 " : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("0" : stdgo.GoString), _remaining : (1 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("2+3" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("2" : stdgo.GoString), _remaining : (2 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51),
({ _input : ("0XABC 12" : stdgo.GoString), _format : ("%v" : stdgo.GoString), _output : ("2748" : stdgo.GoString), _remaining : (3 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51)].concat([for (i in 15 ... (15 > 15 ? 15 : 15 : stdgo.GoInt).toBasic()) ({ _input : ("" : stdgo.GoString), _format : ("" : stdgo.GoString), _output : ("" : stdgo.GoString), _remaining : (0 : stdgo.GoInt) } : stdgo._internal.math.big.Big_t__struct_51.T__struct_51)])) : stdgo.Slice<stdgo._internal.math.big.Big_t__struct_51.T__struct_51>);
