package _internal.regexp.syntax_dot_test;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest>(11, 11, ...[
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestParseSimple" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testParseSimple.testParseSimple) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestParseFoldCase" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testParseFoldCase.testParseFoldCase) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestParseLiteral" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testParseLiteral.testParseLiteral) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestParseMatchNL" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testParseMatchNL.testParseMatchNL) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestParseNoMatchNL" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testParseNoMatchNL.testParseNoMatchNL) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestFoldConstants" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testFoldConstants.testFoldConstants) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestAppendRangeCollapse" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testAppendRangeCollapse.testAppendRangeCollapse) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestParseInvalidRegexps" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testParseInvalidRegexps.testParseInvalidRegexps) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestToStringEquivalentParse" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testToStringEquivalentParse.testToStringEquivalentParse) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestCompile" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testCompile.testCompile) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestSimplify" : stdgo.GoString), stdgo._internal.regexp.syntax.Syntax_testSimplify.testSimplify) : stdgo._internal.testing.Testing_InternalTest.InternalTest)].concat([for (i in 11 ... (11 > 11 ? 11 : 11 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_InternalTest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest>);
