package _internal.regexp.syntax_dot_test;
function main():Void {
        var _m = stdgo._internal.testing.Testing_mainStart.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps_TestDeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps_TestDeps.TestDeps)), _internal.regexp.syntax_dot_test.Syntax_dot_test__tests._tests, _internal.regexp.syntax_dot_test.Syntax_dot_test__benchmarks._benchmarks, _internal.regexp.syntax_dot_test.Syntax_dot_test__fuzzTargets._fuzzTargets, _internal.regexp.syntax_dot_test.Syntax_dot_test__examples._examples);
        Sys.exit(_m.run());
    }
@:keep var __init_go2hx__ = {
        try {
            var __tmp__0 = stdgo._internal.regexp.syntax.Syntax__anyRuneNotNL._anyRuneNotNL, __tmp__1 = stdgo._internal.regexp.syntax.Syntax__anyRune._anyRune, __tmp__2 = stdgo._internal.regexp.syntax.Syntax___Op_index_0.__Op_index_0, __tmp__3 = stdgo._internal.regexp.syntax.Syntax__anyTable._anyTable, __tmp__4 = stdgo._internal.regexp.syntax.Syntax__code1._code1, __tmp__5 = stdgo._internal.regexp.syntax.Syntax__code2._code2, __tmp__6 = stdgo._internal.regexp.syntax.Syntax__code3._code3, __tmp__7 = stdgo._internal.regexp.syntax.Syntax__perlGroup._perlGroup, __tmp__8 = stdgo._internal.regexp.syntax.Syntax__code4._code4, __tmp__9 = stdgo._internal.regexp.syntax.Syntax__code5._code5, __tmp__10 = stdgo._internal.regexp.syntax.Syntax__code6._code6, __tmp__11 = stdgo._internal.regexp.syntax.Syntax__code7._code7, __tmp__12 = stdgo._internal.regexp.syntax.Syntax__code8._code8, __tmp__13 = stdgo._internal.regexp.syntax.Syntax__code9._code9, __tmp__14 = stdgo._internal.regexp.syntax.Syntax__code10._code10, __tmp__15 = stdgo._internal.regexp.syntax.Syntax__code11._code11, __tmp__16 = stdgo._internal.regexp.syntax.Syntax__code12._code12, __tmp__17 = stdgo._internal.regexp.syntax.Syntax__code13._code13, __tmp__18 = stdgo._internal.regexp.syntax.Syntax__code14._code14, __tmp__19 = stdgo._internal.regexp.syntax.Syntax__code15._code15, __tmp__20 = stdgo._internal.regexp.syntax.Syntax__code16._code16, __tmp__21 = stdgo._internal.regexp.syntax.Syntax__code17._code17, __tmp__22 = stdgo._internal.regexp.syntax.Syntax__posixGroup._posixGroup, __tmp__23 = stdgo._internal.regexp.syntax.Syntax__instOpNames._instOpNames, __tmp__24 = stdgo._internal.regexp.syntax.Syntax__foldcaseTests._foldcaseTests, __tmp__25 = stdgo._internal.regexp.syntax.Syntax__literalTests._literalTests, __tmp__26 = stdgo._internal.regexp.syntax.Syntax__matchnlTests._matchnlTests, __tmp__27 = stdgo._internal.regexp.syntax.Syntax__nomatchnlTests._nomatchnlTests, __tmp__28 = stdgo._internal.regexp.syntax.Syntax__opNames._opNames, __tmp__29 = stdgo._internal.regexp.syntax.Syntax__parseTests._parseTests, __tmp__30 = stdgo._internal.regexp.syntax.Syntax__invalidRegexps._invalidRegexps, __tmp__31 = stdgo._internal.regexp.syntax.Syntax__onlyPerl._onlyPerl, __tmp__32 = stdgo._internal.regexp.syntax.Syntax__onlyPOSIX._onlyPOSIX, __tmp__33 = stdgo._internal.regexp.syntax.Syntax__compileTests._compileTests, __tmp__34 = stdgo._internal.regexp.syntax.Syntax__simplifyTests._simplifyTests;
            var __tmp__0 = _internal.regexp.syntax_dot_test.Syntax_dot_test__tests._tests, __tmp__1 = _internal.regexp.syntax_dot_test.Syntax_dot_test__benchmarks._benchmarks, __tmp__2 = _internal.regexp.syntax_dot_test.Syntax_dot_test__fuzzTargets._fuzzTargets, __tmp__3 = _internal.regexp.syntax_dot_test.Syntax_dot_test__examples._examples;
            stdgo._internal.testing.internal.testdeps.Testdeps_importPath.importPath = ("regexp/syntax" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
