package _internal.os_test;
import stdgo._internal.os.Os;
import stdgo._internal.os.Os;
import stdgo._internal.os.Os;
import stdgo._internal.os.Os;
import stdgo._internal.os.Os;
import stdgo._internal.os.Os;
import stdgo._internal.os.Os;
var _isExistTests : stdgo.Slice<_internal.os_test.Os_test_T_isExistTest.T_isExistTest> = (new stdgo.Slice<_internal.os_test.Os_test_T_isExistTest.T_isExistTest>(13, 13, ...[
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errInvalid.errInvalid } : stdgo._internal.io.fs.Fs_PathError.PathError)) : stdgo.Ref<stdgo._internal.io.fs.Fs_PathError.PathError>)), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errPermission.errPermission } : stdgo._internal.io.fs.Fs_PathError.PathError)) : stdgo.Ref<stdgo._internal.io.fs.Fs_PathError.PathError>)), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errExist.errExist } : stdgo._internal.io.fs.Fs_PathError.PathError)) : stdgo.Ref<stdgo._internal.io.fs.Fs_PathError.PathError>)), true, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errNotExist.errNotExist } : stdgo._internal.io.fs.Fs_PathError.PathError)) : stdgo.Ref<stdgo._internal.io.fs.Fs_PathError.PathError>)), false, true) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errClosed.errClosed } : stdgo._internal.io.fs.Fs_PathError.PathError)) : stdgo.Ref<stdgo._internal.io.fs.Fs_PathError.PathError>)), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errInvalid.errInvalid } : stdgo._internal.os.Os_LinkError.LinkError)) : stdgo.Ref<stdgo._internal.os.Os_LinkError.LinkError>)), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errPermission.errPermission } : stdgo._internal.os.Os_LinkError.LinkError)) : stdgo.Ref<stdgo._internal.os.Os_LinkError.LinkError>)), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errExist.errExist } : stdgo._internal.os.Os_LinkError.LinkError)) : stdgo.Ref<stdgo._internal.os.Os_LinkError.LinkError>)), true, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errNotExist.errNotExist } : stdgo._internal.os.Os_LinkError.LinkError)) : stdgo.Ref<stdgo._internal.os.Os_LinkError.LinkError>)), false, true) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errClosed.errClosed } : stdgo._internal.os.Os_LinkError.LinkError)) : stdgo.Ref<stdgo._internal.os.Os_LinkError.LinkError>)), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errNotExist.errNotExist } : stdgo._internal.os.Os_SyscallError.SyscallError)) : stdgo.Ref<stdgo._internal.os.Os_SyscallError.SyscallError>)), false, true) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest(stdgo.Go.asInterface((stdgo.Go.setRef(({ err : stdgo._internal.io.fs.Fs_errExist.errExist } : stdgo._internal.os.Os_SyscallError.SyscallError)) : stdgo.Ref<stdgo._internal.os.Os_SyscallError.SyscallError>)), true, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest),
(new _internal.os_test.Os_test_T_isExistTest.T_isExistTest((null : stdgo.Error), false, false) : _internal.os_test.Os_test_T_isExistTest.T_isExistTest)].concat([for (i in 13 ... (13 > 13 ? 13 : 13 : stdgo.GoInt).toBasic()) ({} : _internal.os_test.Os_test_T_isExistTest.T_isExistTest)])) : stdgo.Slice<_internal.os_test.Os_test_T_isExistTest.T_isExistTest>);
