package stdgo._internal.regexp;
var _subexpCases : stdgo.Slice<stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase> = (new stdgo.Slice<stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase>(11, 11, ...[
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase((stdgo.Go.str() : stdgo.GoString)?.__copy__(), (0 : stdgo.GoInt), (null : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase((".*" : stdgo.GoString), (0 : stdgo.GoInt), (null : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("abba" : stdgo.GoString), (0 : stdgo.GoInt), (null : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("ab(b)a" : stdgo.GoString), (1 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("ab(.*)a" : stdgo.GoString), (1 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("(.*)ab(.*)a" : stdgo.GoString), (2 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(3, 3, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("(.*)(ab)(.*)a" : stdgo.GoString), (3 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("(.*)((a)b)(.*)a" : stdgo.GoString), (4 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(5, 5, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("(.*)(\\(ab)(.*)a" : stdgo.GoString), (3 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("(.*)(\\(a\\)b)(.*)a" : stdgo.GoString), (3 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>), stdgo._internal.regexp.Regexp__emptysubexpindices._emptySubexpIndices) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase),
(new stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase(("(?P<foo>.*)(?P<bar>(a)b)(?P<foo>.*)a" : stdgo.GoString), (4 : stdgo.GoInt), (new stdgo.Slice<stdgo.GoString>(5, 5, ...[(stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("foo" : stdgo.GoString), ("bar" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("foo" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>), (new stdgo.Slice<stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex>(4, 4, ...[(new stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex((stdgo.Go.str() : stdgo.GoString)?.__copy__(), (-1 : stdgo.GoInt)) : stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex), (new stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex(("missing" : stdgo.GoString), (-1 : stdgo.GoInt)) : stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex), (new stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex(("foo" : stdgo.GoString), (1 : stdgo.GoInt)) : stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex), (new stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex(("bar" : stdgo.GoString), (2 : stdgo.GoInt)) : stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex)])) : stdgo.Slice<stdgo._internal.regexp.Regexp_t_subexpindex.T_subexpIndex>)) : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase)].concat([for (i in 11 ... (11 > 11 ? 11 : 11 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase)])) : stdgo.Slice<stdgo._internal.regexp.Regexp_t_subexpcase.T_subexpCase>);
