package stdgo._internal.regexp;
import stdgo._internal.strings.Strings;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.regexp.syntax.Syntax;
import stdgo._internal.testing.Testing;
import stdgo._internal.os.Os;
import stdgo._internal.compress.bzip2.Bzip2;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.path.filepath.Filepath;
import stdgo._internal.io.Io;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.sort.Sort;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.bytes.Bytes;
var _run : stdgo.Slice<(stdgo.Ref<stdgo._internal.regexp.Regexp_Regexp.Regexp>, stdgo.Ref<stdgo._internal.regexp.Regexp_Regexp.Regexp>, stdgo.GoString) -> { var _0 : stdgo.Slice<stdgo.GoInt>; var _1 : stdgo.GoString; }> = (new stdgo.Slice<(stdgo.Ref<stdgo._internal.regexp.Regexp_Regexp.Regexp>, stdgo.Ref<stdgo._internal.regexp.Regexp_Regexp.Regexp>, stdgo.GoString) -> { var _0 : stdgo.Slice<stdgo.GoInt>; var _1 : stdgo.GoString; }>(4, 4, ...[stdgo._internal.regexp.Regexp__runFull._runFull, stdgo._internal.regexp.Regexp__runPartial._runPartial, stdgo._internal.regexp.Regexp__runFullLongest._runFullLongest, stdgo._internal.regexp.Regexp__runPartialLongest._runPartialLongest]) : stdgo.Slice<(stdgo.Ref<stdgo._internal.regexp.Regexp_Regexp.Regexp>, stdgo.Ref<stdgo._internal.regexp.Regexp_Regexp.Regexp>, stdgo.GoString) -> { var _0 : stdgo.Slice<stdgo.GoInt>; var _1 : stdgo.GoString; }>);
