package stdgo._internal.regexp;
var _literalPrefixTests : stdgo.Slice<stdgo._internal.regexp.Regexp_metatest.MetaTest> = (new stdgo.Slice<stdgo._internal.regexp.Regexp_metatest.MetaTest>(11, 11, ...[
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("^0^0$" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("0" : stdgo.GoString), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("^0^" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("^0$" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("0" : stdgo.GoString), true) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("$0^" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("$0$" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("^^0$$" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("^$^$" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("$$0^^" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("a\\x{fffd}b" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), ("a" : stdgo.GoString), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("\\x{fffd}b" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest),
(new stdgo._internal.regexp.Regexp_metatest.MetaTest(("�" : stdgo.GoString), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), (stdgo.Go.str() : stdgo.GoString)?.__copy__(), false) : stdgo._internal.regexp.Regexp_metatest.MetaTest)].concat([for (i in 11 ... (11 > 11 ? 11 : 11 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.regexp.Regexp_metatest.MetaTest)])) : stdgo.Slice<stdgo._internal.regexp.Regexp_metatest.MetaTest>);
