package stdgo._internal.math.cmplx;
var _acosSC : stdgo.Slice<stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0> = (new stdgo.Slice<stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0>(15, 15, ...[
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__zero._zero, stdgo._internal.math.cmplx.Cmplx__zero._zero), _want : new stdgo.GoComplex128((1.5707963267948966 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__zero._zero) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(-stdgo._internal.math.cmplx.Cmplx__zero._zero, stdgo._internal.math.cmplx.Cmplx__zero._zero), _want : new stdgo.GoComplex128((1.5707963267948966 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__zero._zero) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__zero._zero, stdgo._internal.math.cmplx.Cmplx__nan._nan), _want : new stdgo.GoComplex128((1.5707963267948966 : stdgo.GoFloat64), stdgo._internal.math.cmplx.Cmplx__nan._nan) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(-stdgo._internal.math.cmplx.Cmplx__zero._zero, stdgo._internal.math.cmplx.Cmplx__nan._nan), _want : new stdgo.GoComplex128((1.5707963267948966 : stdgo.GoFloat64), stdgo._internal.math.cmplx.Cmplx__nan._nan) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128((1 : stdgo.GoFloat64), stdgo._internal.math.cmplx.Cmplx__inf._inf), _want : new stdgo.GoComplex128((1.5707963267948966 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128((1 : stdgo.GoFloat64), stdgo._internal.math.cmplx.Cmplx__nan._nan), _want : stdgo._internal.math.cmplx.Cmplx_nan.naN() } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(-stdgo._internal.math.cmplx.Cmplx__inf._inf, (1 : stdgo.GoFloat64)), _want : new stdgo.GoComplex128((3.141592653589793 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__inf._inf, (1 : stdgo.GoFloat64)), _want : new stdgo.GoComplex128((0 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(-stdgo._internal.math.cmplx.Cmplx__inf._inf, stdgo._internal.math.cmplx.Cmplx__inf._inf), _want : new stdgo.GoComplex128((2.356194490192345 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__inf._inf, stdgo._internal.math.cmplx.Cmplx__inf._inf), _want : new stdgo.GoComplex128((0.7853981633974483 : stdgo.GoFloat64), -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__inf._inf, stdgo._internal.math.cmplx.Cmplx__nan._nan), _want : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__nan._nan, -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(-stdgo._internal.math.cmplx.Cmplx__inf._inf, stdgo._internal.math.cmplx.Cmplx__nan._nan), _want : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__nan._nan, stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__nan._nan, (1 : stdgo.GoFloat64)), _want : stdgo._internal.math.cmplx.Cmplx_nan.naN() } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__nan._nan, stdgo._internal.math.cmplx.Cmplx__inf._inf), _want : new stdgo.GoComplex128(stdgo._internal.math.cmplx.Cmplx__nan._nan, -stdgo._internal.math.cmplx.Cmplx__inf._inf) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0),
({ _in : stdgo._internal.math.cmplx.Cmplx_nan.naN(), _want : stdgo._internal.math.cmplx.Cmplx_nan.naN() } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0)].concat([for (i in 15 ... (15 > 15 ? 15 : 15 : stdgo.GoInt).toBasic()) ({ _in : new stdgo.GoComplex128(0, 0), _want : new stdgo.GoComplex128(0, 0) } : stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0)])) : stdgo.Slice<stdgo._internal.math.cmplx.Cmplx_t__struct_0.T__struct_0>);
