package stdgo._internal.encoding.json;
@:named @:using(stdgo._internal.encoding.json.Json_t_testanonymousfields___localname___myint_9005_static_extension.T_testAnonymousFields___localname___MyInt_9005_static_extension) typedef T_testAnonymousFields___localname___MyInt_9005 = stdgo.GoInt;
