package stdgo._internal.encoding.json;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.time.Time;
import stdgo._internal.strings.Strings;
import stdgo._internal.math.Math;
import stdgo._internal.regexp.Regexp;
import stdgo._internal.os.Os;
import stdgo._internal.compress.gzip.Gzip;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.unicode.utf16.Utf16;
import stdgo._internal.math.big.Big;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.encoding.base64.Base64;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.sort.Sort;
import stdgo._internal.runtime.debug.Debug;
import stdgo._internal.testing.Testing;
import stdgo._internal.log.Log;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.net.Net;
import stdgo._internal.net.http.httptest.Httptest;
import stdgo._internal.net.http.Http;
var _ifaceNumAsNumber : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface> = ({
        final x = new stdgo.GoMap.GoStringMap<stdgo.AnyInterface>();
        x.__defaultValue__ = () -> (null : stdgo.AnyInterface);
        x.set(("k1" : stdgo.GoString), stdgo.Go.toInterface(stdgo.Go.asInterface((("1" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))));
x.set(("k2" : stdgo.GoString), stdgo.Go.toInterface(("s" : stdgo.GoString)));
x.set(("k3" : stdgo.GoString), stdgo.Go.toInterface((new stdgo.Slice<stdgo.AnyInterface>(3, 3, ...[stdgo.Go.toInterface(stdgo.Go.asInterface((("1" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), stdgo.Go.toInterface(stdgo.Go.asInterface((("2.0" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), stdgo.Go.toInterface(stdgo.Go.asInterface((("3e-3" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number)))]) : stdgo.Slice<stdgo.AnyInterface>)));
x.set(("k4" : stdgo.GoString), stdgo.Go.toInterface(({
            final x = new stdgo.GoMap.GoStringMap<stdgo.AnyInterface>();
            x.__defaultValue__ = () -> (null : stdgo.AnyInterface);
            x.set(("kk1" : stdgo.GoString), stdgo.Go.toInterface(("s" : stdgo.GoString)));
x.set(("kk2" : stdgo.GoString), stdgo.Go.toInterface(stdgo.Go.asInterface((("2" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))));
            x;
        } : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>)));
        x;
    } : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>);
