package stdgo._internal.encoding.json;
var _encodeStringTests : stdgo.Slice<stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6> = (new stdgo.Slice<stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6>(32, 32, ...[
({ _in : (stdgo.Go.str(0) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0000\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(1) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0001\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(2) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0002\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(3) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0003\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(4) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0004\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(5) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0005\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(6) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0006\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\x07" : stdgo.GoString), _out : ("\"\\u0007\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\x08" : stdgo.GoString), _out : ("\"\\u0008\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\t" : stdgo.GoString), _out : ("\"\\t\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\n" : stdgo.GoString), _out : ("\"\\n\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\x0B" : stdgo.GoString), _out : ("\"\\u000b\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\x0C" : stdgo.GoString), _out : ("\"\\u000c\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : ("\r" : stdgo.GoString), _out : ("\"\\r\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(14) : stdgo.GoString)?.__copy__(), _out : ("\"\\u000e\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(15) : stdgo.GoString)?.__copy__(), _out : ("\"\\u000f\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(16) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0010\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(17) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0011\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(18) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0012\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(19) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0013\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(20) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0014\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(21) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0015\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(22) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0016\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(23) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0017\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(24) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0018\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(25) : stdgo.GoString)?.__copy__(), _out : ("\"\\u0019\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(26) : stdgo.GoString)?.__copy__(), _out : ("\"\\u001a\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(27) : stdgo.GoString)?.__copy__(), _out : ("\"\\u001b\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(28) : stdgo.GoString)?.__copy__(), _out : ("\"\\u001c\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(29) : stdgo.GoString)?.__copy__(), _out : ("\"\\u001d\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(30) : stdgo.GoString)?.__copy__(), _out : ("\"\\u001e\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6),
({ _in : (stdgo.Go.str(31) : stdgo.GoString)?.__copy__(), _out : ("\"\\u001f\"" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6)].concat([for (i in 32 ... (32 > 32 ? 32 : 32 : stdgo.GoInt).toBasic()) ({ _in : ("" : stdgo.GoString), _out : ("" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6)])) : stdgo.Slice<stdgo._internal.encoding.json.Json_t__struct_6.T__struct_6>);
