package stdgo._internal.encoding.json;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.errors.Errors;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.time.Time;
import stdgo._internal.strings.Strings;
import stdgo._internal.math.Math;
import stdgo._internal.regexp.Regexp;
import stdgo._internal.os.Os;
import stdgo._internal.compress.gzip.Gzip;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.unicode.utf16.Utf16;
import stdgo._internal.math.big.Big;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.encoding.base64.Base64;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.sort.Sort;
import stdgo._internal.runtime.debug.Debug;
import stdgo._internal.testing.Testing;
import stdgo._internal.log.Log;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.net.Net;
import stdgo._internal.net.http.httptest.Httptest;
import stdgo._internal.net.http.Http;
var _unmarshalTests : stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest> = (new stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest>(152, 152, ...[
({ _in : ("true" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(false)), _out : stdgo.Go.toInterface(true) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("1" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoInt))), _out : stdgo.Go.toInterface((1 : stdgo.GoInt)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("1.2" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((1.2 : stdgo.GoFloat64)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("-5" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoInt16))), _out : stdgo.Go.toInterface((-5 : stdgo.GoInt16)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("2" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((("" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((("2" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), _useNumber : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("2" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((("" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((("2" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("2" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.AnyInterface)) : stdgo.Ref<stdgo.AnyInterface>)), _out : stdgo.Go.toInterface((2 : stdgo.GoFloat64)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("2" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.AnyInterface)) : stdgo.Ref<stdgo.AnyInterface>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((("2" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), _useNumber : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"a\\u1234\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("aሴ" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"http:\\/\\/\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("http://" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"g-clef: \\uD834\\uDD1E\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("g-clef: 𝄞" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"invalid: \\uD834x\\uDD1E\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("invalid: �x�" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("null" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.AnyInterface)) : stdgo.Ref<stdgo.AnyInterface>)), _out : (null : stdgo.AnyInterface) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": [1,2,3], \"Y\": 4}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_.T_)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_.T_>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ y : (4 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_T_.T_))), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError(("array" : stdgo.GoString), stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.str())), (7i64 : stdgo.GoInt64), ("T" : stdgo.GoString), ("X" : stdgo.GoString)) : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": 23}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_.T_)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_.T_>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_T_.T_() : stdgo._internal.encoding.json.Json_T_.T_))), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError(("number" : stdgo.GoString), stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.str())), (8i64 : stdgo.GoInt64), ("T" : stdgo.GoString), ("X" : stdgo.GoString)) : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"x\": 1}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_tx.T_tx)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_tx.T_tx>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_T_tx.T_tx() : stdgo._internal.encoding.json.Json_T_tx.T_tx))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"x\": 1}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_tx.T_tx)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_tx.T_tx>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_T_tx.T_tx() : stdgo._internal.encoding.json.Json_T_tx.T_tx))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"x\": 1}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_tx.T_tx)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_tx.T_tx>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"x\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"S\": 23}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_W.W)) : stdgo.Ref<stdgo._internal.encoding.json.Json_W.W>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_W.W() : stdgo._internal.encoding.json.Json_W.W))), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError(("number" : stdgo.GoString), stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.str() : stdgo._internal.encoding.json.Json_SS.SS)))), (0i64 : stdgo.GoInt64), ("W" : stdgo.GoString), ("S" : stdgo.GoString)) : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"F1\":1,\"F2\":2,\"F3\":3}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_V.V)) : stdgo.Ref<stdgo._internal.encoding.json.Json_V.V>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ f1 : stdgo.Go.toInterface((1 : stdgo.GoFloat64)), f2 : (2 : stdgo.GoInt32), f3 : (("3" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number) } : stdgo._internal.encoding.json.Json_V.V))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"F1\":1,\"F2\":2,\"F3\":3}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_V.V)) : stdgo.Ref<stdgo._internal.encoding.json.Json_V.V>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ f1 : stdgo.Go.toInterface(stdgo.Go.asInterface((("1" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), f2 : (2 : stdgo.GoInt32), f3 : (("3" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number) } : stdgo._internal.encoding.json.Json_V.V))), _useNumber : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"k1\":1,\"k2\":\"s\",\"k3\":[1,2.0,3e-3],\"k4\":{\"kk1\":\"s\",\"kk2\":2}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.AnyInterface)) : stdgo.Ref<stdgo.AnyInterface>)), _out : stdgo.Go.toInterface(stdgo._internal.encoding.json.Json__ifaceNumAsFloat64._ifaceNumAsFloat64) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"k1\":1,\"k2\":\"s\",\"k3\":[1,2.0,3e-3],\"k4\":{\"kk1\":\"s\",\"kk2\":2}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.AnyInterface)) : stdgo.Ref<stdgo.AnyInterface>)), _out : stdgo.Go.toInterface(stdgo._internal.encoding.json.Json__ifaceNumAsNumber._ifaceNumAsNumber), _useNumber : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\n true " : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(false)), _out : stdgo.Go.toInterface(true) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\t 1 " : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoInt))), _out : stdgo.Go.toInterface((1 : stdgo.GoInt)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\r 1.2 " : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((1.2 : stdgo.GoFloat64)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\t -5 \n" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoInt16))), _out : stdgo.Go.toInterface((-5 : stdgo.GoInt16)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\t \"a\\u1234\" \n" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("aሴ" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"Y\": 1, \"Z\": 2}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_.T_)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_.T_>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ y : (1 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_T_.T_))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"Y\": 1, \"Z\": 2}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_.T_)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_.T_>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"Z\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"alpha\": \"abc\", \"alphabet\": \"xyz\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_U.U)) : stdgo.Ref<stdgo._internal.encoding.json.Json_U.U>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ alphabet : ("abc" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_U.U))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"alpha\": \"abc\", \"alphabet\": \"xyz\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_U.U)) : stdgo.Ref<stdgo._internal.encoding.json.Json_U.U>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"alphabet\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"alpha\": \"abc\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_U.U)) : stdgo.Ref<stdgo._internal.encoding.json.Json_U.U>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ alphabet : ("abc" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_U.U))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"alphabet\": \"xyz\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_U.U)) : stdgo.Ref<stdgo._internal.encoding.json.Json_U.U>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_U.U() : stdgo._internal.encoding.json.Json_U.U))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"alphabet\": \"xyz\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_U.U)) : stdgo.Ref<stdgo._internal.encoding.json.Json_U.U>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"alphabet\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": \"foo\", \"Y\"}" : stdgo.GoString), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'}\' after object key" : stdgo.GoString), (17i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[1, 2, 3+]" : stdgo.GoString), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'+\' after array element" : stdgo.GoString), (9i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\":12x}" : stdgo.GoString), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'x\' after object key:value pair" : stdgo.GoString), (8i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)), _useNumber : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[2, 3" : stdgo.GoString), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ _msg : ("unexpected end of JSON input" : stdgo.GoString), offset : (5i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"F3\": -}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_V.V)) : stdgo.Ref<stdgo._internal.encoding.json.Json_V.V>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ f3 : (("-" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number) } : stdgo._internal.encoding.json.Json_V.V))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ _msg : ("invalid character \'}\' in numeric literal" : stdgo.GoString), offset : (9i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(1, " 42")?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' looking for beginning of value" : stdgo.GoString), (1i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(" 42 ", 1)?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' after top-level value" : stdgo.GoString), (5i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(1, " true")?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' looking for beginning of value" : stdgo.GoString), (1i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(" false ", 1)?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' after top-level value" : stdgo.GoString), (8i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(1, " 1.2")?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' looking for beginning of value" : stdgo.GoString), (1i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(" 3.4 ", 1)?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' after top-level value" : stdgo.GoString), (6i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(1, " \"string\"")?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' looking for beginning of value" : stdgo.GoString), (1i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str(" \"string\" ", 1)?.__copy__(), _err : stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError(("invalid character \'\\x01\' after top-level value" : stdgo.GoString), (11i64 : stdgo.GoInt64)) : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[1, 2, 3]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef(new stdgo.GoArray<stdgo.GoInt>(3, 3).__setNumber32__()) : stdgo.Ref<stdgo.GoArray<stdgo.GoInt>>)), _out : stdgo.Go.toInterface((new stdgo.GoArray<stdgo.GoInt>(3, 3, ...[(1 : stdgo.GoInt), (2 : stdgo.GoInt), (3 : stdgo.GoInt)]).__setNumber32__() : stdgo.GoArray<stdgo.GoInt>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[1, 2, 3]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef(new stdgo.GoArray<stdgo.GoInt>(1, 1).__setNumber32__()) : stdgo.Ref<stdgo.GoArray<stdgo.GoInt>>)), _out : stdgo.Go.toInterface((new stdgo.GoArray<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.GoArray<stdgo.GoInt>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[1, 2, 3]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef(new stdgo.GoArray<stdgo.GoInt>(5, 5).__setNumber32__()) : stdgo.Ref<stdgo.GoArray<stdgo.GoInt>>)), _out : stdgo.Go.toInterface((new stdgo.GoArray<stdgo.GoInt>(5, 5, ...[(1 : stdgo.GoInt), (2 : stdgo.GoInt), (3 : stdgo.GoInt), (0 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.GoArray<stdgo.GoInt>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[1, 2, 3]" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_MustNotUnmarshalJSON.MustNotUnmarshalJSON)) : stdgo.Ref<stdgo._internal.encoding.json.Json_MustNotUnmarshalJSON.MustNotUnmarshalJSON>))), _err : stdgo._internal.errors.Errors_new_.new_(("MustNotUnmarshalJSON was used" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo.AnyInterface>)) : stdgo.Ref<stdgo.Slice<stdgo.AnyInterface>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo.AnyInterface>(0, 0, ...[]) : stdgo.Slice<stdgo.AnyInterface>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("null" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo.AnyInterface>)) : stdgo.Ref<stdgo.Slice<stdgo.AnyInterface>>)), _out : stdgo.Go.toInterface((null : stdgo.Slice<stdgo.AnyInterface>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"T\":[]}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoStringMap<stdgo.AnyInterface>();
        x.__defaultValue__ = () -> (null : stdgo.AnyInterface);
        x.set(("T" : stdgo.GoString), stdgo.Go.toInterface((new stdgo.Slice<stdgo.AnyInterface>(0, 0, ...[]) : stdgo.Slice<stdgo.AnyInterface>)));
        x;
    } : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"T\":null}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoStringMap<stdgo.AnyInterface>();
        x.__defaultValue__ = () -> (null : stdgo.AnyInterface);
        x.set(("T" : stdgo.GoString), (null : stdgo.AnyInterface));
        x;
    } : stdgo.GoMap<stdgo.GoString, stdgo.AnyInterface>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__allValueIndent._allValueIndent?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_All.All)) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__allValue._allValue)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__allValueCompact._allValueCompact?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_All.All)) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__allValue._allValue)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__allValueIndent._allValueIndent?.__copy__(), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>)) : stdgo.Ref<stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__allValue._allValue) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__allValueCompact._allValueCompact?.__copy__(), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>)) : stdgo.Ref<stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__allValue._allValue) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__pallValueIndent._pallValueIndent?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_All.All)) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__pallValue._pallValue)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__pallValueCompact._pallValueCompact?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_All.All)) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__pallValue._pallValue)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__pallValueIndent._pallValueIndent?.__copy__(), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>)) : stdgo.Ref<stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__pallValue._pallValue) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo._internal.encoding.json.Json__pallValueCompact._pallValueCompact?.__copy__(), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>)) : stdgo.Ref<stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__pallValue._pallValue) : stdgo.Ref<stdgo._internal.encoding.json.Json_All.All>))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"T\":false}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__umtrue._umtrue)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"T\":false}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>)) : stdgo.Ref<stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__umtrue._umtrue) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[{\"T\":false}]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>>)), _out : stdgo.Go.toInterface(stdgo._internal.encoding.json.Json__umslice._umslice) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[{\"T\":false}]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>>)) : stdgo.Ref<stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>>>)), _out : stdgo.Go.toInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__umslice._umslice) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler>>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"M\":{\"T\":\"x:y\"}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_ustruct.T_ustruct)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_ustruct.T_ustruct>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__umstruct._umstruct)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"x:y\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__umtrueXY._umtrueXY)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"x:y\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>)) : stdgo.Ref<stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>>)), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__umtrueXY._umtrueXY) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"x:y\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>>)), _out : stdgo.Go.toInterface(stdgo._internal.encoding.json.Json__umsliceXY._umsliceXY) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"x:y\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>>)) : stdgo.Ref<stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>>>)), _out : stdgo.Go.toInterface((stdgo.Go.setRef(stdgo._internal.encoding.json.Json__umsliceXY._umsliceXY) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText>>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"M\":\"x:y\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_ustructText.T_ustructText)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_ustructText.T_ustructText>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(stdgo._internal.encoding.json.Json__umstructXY._umstructXY)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"-1\":\"a\",\"0\":\"b\",\"1\":\"c\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoInt, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoInt, stdgo.GoString>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoIntMap<stdgo.GoString>();
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        x.set((-1 : stdgo.GoInt), ("a" : stdgo.GoString));
x.set((0 : stdgo.GoInt), ("b" : stdgo.GoString));
x.set((1 : stdgo.GoInt), ("c" : stdgo.GoString));
        x;
    } : stdgo.GoMap<stdgo.GoInt, stdgo.GoString>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"0\":\"a\",\"10\":\"c\",\"9\":\"b\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8.T_u8, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8.T_u8, stdgo.GoString>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoIntMap<stdgo.GoString>();
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        x.set((0 : stdgo._internal.encoding.json.Json_T_u8.T_u8), ("a" : stdgo.GoString));
x.set((9 : stdgo._internal.encoding.json.Json_T_u8.T_u8), ("b" : stdgo.GoString));
x.set((10 : stdgo._internal.encoding.json.Json_T_u8.T_u8), ("c" : stdgo.GoString));
        x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8.T_u8, stdgo.GoString>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"-9223372036854775808\":\"min\",\"9223372036854775807\":\"max\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoInt64, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoInt64, stdgo.GoString>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoInt64Map<stdgo.GoString>();
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        x.set((-9223372036854775808i64 : stdgo.GoInt64), ("min" : stdgo.GoString));
x.set((9223372036854775807i64 : stdgo.GoInt64), ("max" : stdgo.GoString));
        x;
    } : stdgo.GoMap<stdgo.GoInt64, stdgo.GoString>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"18446744073709551615\":\"max\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoUInt64, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoUInt64, stdgo.GoString>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoUInt64Map<stdgo.GoString>();
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        x.set((-1i64 : stdgo.GoUInt64), ("max" : stdgo.GoString));
        x;
    } : stdgo.GoMap<stdgo.GoUInt64, stdgo.GoString>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"0\":false,\"10\":true}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoUIntptr, Bool>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoUIntptr, Bool>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoIntMap<Bool>();
        x.__defaultValue__ = () -> false;
        x.set((0 : stdgo.GoUIntptr), false);
x.set((10 : stdgo.GoUIntptr), true);
        x;
    } : stdgo.GoMap<stdgo.GoUIntptr, Bool>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"u2\":4}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8marshal.T_u8marshal, stdgo.GoInt>)) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8marshal.T_u8marshal, stdgo.GoInt>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoIntMap<stdgo.GoInt>();
        x.__defaultValue__ = () -> (0 : stdgo.GoInt);
        x.set((2 : stdgo._internal.encoding.json.Json_T_u8marshal.T_u8marshal), (4 : stdgo.GoInt));
        x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8marshal.T_u8marshal, stdgo.GoInt>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"2\":4}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8marshal.T_u8marshal, stdgo.GoInt>)) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_T_u8marshal.T_u8marshal, stdgo.GoInt>>)), _err : stdgo._internal.encoding.json.Json__errMissingU8Prefix._errMissingU8Prefix } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"abc\":\"abc\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoInt, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoInt, stdgo.GoString>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number abc" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt))), offset : (2i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"256\":\"abc\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoUInt8, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoUInt8, stdgo.GoString>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number 256" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoUInt8))), offset : (2i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"128\":\"abc\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoInt8, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoInt8, stdgo.GoString>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number 128" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt8))), offset : (2i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"-1\":\"abc\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoUInt8, stdgo.GoString>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoUInt8, stdgo.GoString>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number -1" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoUInt8))), offset : (2i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"F\":{\"a\":2,\"3\":4}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoString, stdgo.GoMap<stdgo.GoInt, stdgo.GoInt>>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoString, stdgo.GoMap<stdgo.GoInt, stdgo.GoInt>>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number a" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt))), offset : (7i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"F\":{\"a\":2,\"3\":4}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoString, stdgo.GoMap<stdgo.GoUInt, stdgo.GoInt>>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoString, stdgo.GoMap<stdgo.GoUInt, stdgo.GoInt>>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number a" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0u32 : stdgo.GoUInt))), offset : (7i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"x:y\":true}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((({
        final x:stdgo.GoMap.GoObjectMap<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText, Bool> = null;
        cast x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText, Bool>))) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText, Bool>>)), _out : stdgo.Go.toInterface(stdgo._internal.encoding.json.Json__ummapXY._ummapXY) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"x:y\":false,\"x:y\":true}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((({
        final x:stdgo.GoMap.GoObjectMap<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText, Bool> = null;
        cast x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText, Bool>))) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshalerText.T_unmarshalerText, Bool>>)), _out : stdgo.Go.toInterface(stdgo._internal.encoding.json.Json__ummapXY._ummapXY) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\n\t\t\t\"Level0\": 1,\n\t\t\t\"Level1b\": 2,\n\t\t\t\"Level1c\": 3,\n\t\t\t\"x\": 4,\n\t\t\t\"Level1a\": 5,\n\t\t\t\"LEVEL1B\": 6,\n\t\t\t\"e\": {\n\t\t\t\t\"Level1a\": 8,\n\t\t\t\t\"Level1b\": 9,\n\t\t\t\t\"Level1c\": 10,\n\t\t\t\t\"Level1d\": 11,\n\t\t\t\t\"x\": 12\n\t\t\t},\n\t\t\t\"Loop1\": 13,\n\t\t\t\"Loop2\": 14,\n\t\t\t\"X\": 15,\n\t\t\t\"Y\": 16,\n\t\t\t\"Z\": 17,\n\t\t\t\"Q\": 18\n\t\t}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_Top.Top)) : stdgo.Ref<stdgo._internal.encoding.json.Json_Top.Top>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ level0 : (1 : stdgo.GoInt), embed0 : ({ level1b : (2 : stdgo.GoInt), level1c : (3 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_Embed0.Embed0), embed0a : (stdgo.Go.setRef(({ level1a : (5 : stdgo.GoInt), level1b : (6 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_Embed0a.Embed0a)) : stdgo.Ref<stdgo._internal.encoding.json.Json_Embed0a.Embed0a>), embed0b : (stdgo.Go.setRef(({ level1a : (8 : stdgo.GoInt), level1b : (9 : stdgo.GoInt), level1c : (10 : stdgo.GoInt), level1d : (11 : stdgo.GoInt), level1e : (12 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_Embed0b.Embed0b)) : stdgo.Ref<stdgo._internal.encoding.json.Json_Embed0b.Embed0b>), loop : ({ loop1 : (13 : stdgo.GoInt), loop2 : (14 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_Loop.Loop), embed0p : ({ point : ({ x : (15 : stdgo.GoInt), y : (16 : stdgo.GoInt) } : stdgo._internal.image.Image_Point.Point) } : stdgo._internal.encoding.json.Json_Embed0p.Embed0p), embed0q : ({ point : ({ z : (17 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_Point.Point) } : stdgo._internal.encoding.json.Json_Embed0q.Embed0q), _embed : ({ q : (18 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_T_embed.T_embed) } : stdgo._internal.encoding.json.Json_Top.Top))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"hello\": 1}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_Ambig.Ambig)) : stdgo.Ref<stdgo._internal.encoding.json.Json_Ambig.Ambig>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ first : (1 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_Ambig.Ambig))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": 1,\"Y\":2}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_S5.S5)) : stdgo.Ref<stdgo._internal.encoding.json.Json_S5.S5>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ s8 : ({ s9 : ({ y : (2 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_S9.S9) } : stdgo._internal.encoding.json.Json_S8.S8) } : stdgo._internal.encoding.json.Json_S5.S5))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": 1,\"Y\":2}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_S5.S5)) : stdgo.Ref<stdgo._internal.encoding.json.Json_S5.S5>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"X\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": 1,\"Y\":2}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_S10.S10)) : stdgo.Ref<stdgo._internal.encoding.json.Json_S10.S10>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ s13 : ({ s8 : ({ s9 : ({ y : (2 : stdgo.GoInt) } : stdgo._internal.encoding.json.Json_S9.S9) } : stdgo._internal.encoding.json.Json_S8.S8) } : stdgo._internal.encoding.json.Json_S13.S13) } : stdgo._internal.encoding.json.Json_S10.S10))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"X\": 1,\"Y\":2}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_S10.S10)) : stdgo.Ref<stdgo._internal.encoding.json.Json_S10.S10>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"X\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"I\": 0, \"I\": null, \"J\": null}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_DoublePtr.DoublePtr)) : stdgo.Ref<stdgo._internal.encoding.json.Json_DoublePtr.DoublePtr>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface(({ i : (null : stdgo.Pointer<stdgo.Pointer<stdgo.GoInt>>), j : (null : stdgo.Pointer<stdgo.Pointer<stdgo.GoInt>>) } : stdgo._internal.encoding.json.Json_DoublePtr.DoublePtr))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str("\"hello", 255, "world\"")?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello�world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str("\"hello", 194, 194, "world\"")?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello��world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str("\"hello", 194, 255, "world\"")?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello��world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"hello\\ud800world\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello�world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"hello\\ud800\\ud800world\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello��world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"hello\\ud800\\ud800world\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello��world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : stdgo.Go.str("\"hello", 237, 160, 128, 237, 176, 128, "world\"")?.__copy__(), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer(("" : stdgo.GoString))), _out : stdgo.Go.toInterface(("hello������world" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"2009-11-10T23:00:00Z\": \"hello world\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((({
        final x:stdgo.GoMap.GoObjectMap<stdgo._internal.time.Time_Time.Time, stdgo.GoString> = null;
        cast x;
    } : stdgo.GoMap<stdgo._internal.time.Time_Time.Time, stdgo.GoString>))) : stdgo.Ref<stdgo.GoMap<stdgo._internal.time.Time_Time.Time, stdgo.GoString>>)), _out : stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoObjectMap<stdgo._internal.time.Time_Time.Time, stdgo.GoString>();
        x.t = new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.Reflect.GoType.named("stdgo._internal.time.Time_Time.Time", [], stdgo._internal.internal.reflect.Reflect.GoType.named("stdgo._internal.time.Time_Time.Time", [], stdgo._internal.internal.reflect.Reflect.GoType.invalidType, false, { get : () -> null }), false, { get : () -> null }));
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        x.set(stdgo._internal.time.Time_date.date((2009 : stdgo.GoInt), (11 : stdgo._internal.time.Time_Month.Month), (10 : stdgo.GoInt), (23 : stdgo.GoInt), (0 : stdgo.GoInt), (0 : stdgo.GoInt), (0 : stdgo.GoInt), stdgo._internal.time.Time_uTC.uTC), ("hello world" : stdgo.GoString));
        cast x;
    } : stdgo.GoMap<stdgo._internal.time.Time_Time.Time, stdgo.GoString>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"2009-11-10T23:00:00Z\": \"hello world\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((({
        final x:stdgo.GoMap.GoObjectMap<stdgo._internal.encoding.json.Json_Point.Point, stdgo.GoString> = null;
        cast x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_Point.Point, stdgo.GoString>))) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_Point.Point, stdgo.GoString>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("object" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoObjectMap<stdgo._internal.encoding.json.Json_Point.Point, stdgo.GoString>();
        x.t = new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.Reflect.GoType.named("stdgo._internal.encoding.json.Json_Point.Point", [], stdgo._internal.internal.reflect.Reflect.GoType.structType([{ name : "z", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.Reflect.GoType.basic(int_kind) }, optional : false }]), false, { get : () -> null }));
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        {};
        cast x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_Point.Point, stdgo.GoString>))), offset : (1i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"asdf\": \"hello world\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((({
        final x:stdgo.GoMap.GoObjectMap<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler, stdgo.GoString> = null;
        cast x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler, stdgo.GoString>))) : stdgo.Ref<stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler, stdgo.GoString>>)), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("object" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(({
        final x = new stdgo.GoMap.GoObjectMap<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler, stdgo.GoString>();
        x.t = new stdgo._internal.internal.reflect.Reflect._Type(stdgo._internal.internal.reflect.Reflect.GoType.named("stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler", [], stdgo._internal.internal.reflect.Reflect.GoType.structType([{ name : "t", embedded : false, tag : "", type : { get : () -> stdgo._internal.internal.reflect.Reflect.GoType.basic(bool_kind) }, optional : false }]), false, { get : () -> null }));
        x.__defaultValue__ = () -> ("" : stdgo.GoString);
        {};
        cast x;
    } : stdgo.GoMap<stdgo._internal.encoding.json.Json_T_unmarshaler.T_unmarshaler, stdgo.GoString>))), offset : (1i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"AQID\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON), (2 : stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON), (3 : stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON), (2 : stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON), (3 : stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalJSON.T_byteWithMarshalJSON>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"AQID\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText), (2 : stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText), (3 : stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText), (2 : stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText), (3 : stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithMarshalText.T_byteWithMarshalText>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"AQID\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON), (2 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON), (3 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON), (2 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON), (3 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalJSON.T_byteWithPtrMarshalJSON>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"AQID\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText), (2 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText), (3 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText), (2 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText), (3 : stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_byteWithPtrMarshalText.T_byteWithPtrMarshalText>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON), (2 : stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON), (3 : stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalJSON.T_intWithMarshalJSON>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText), (2 : stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText), (3 : stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithMarshalText.T_intWithMarshalText>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON), (2 : stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON), (3 : stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalJSON.T_intWithPtrMarshalJSON>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[\"Z01\",\"Z02\",\"Z03\"]" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText>)) : stdgo.Ref<stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText>>)), _out : stdgo.Go.toInterface((new stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText>(3, 3, ...[(1 : stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText), (2 : stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText), (3 : stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText)]).__setNumber32__() : stdgo.Slice<stdgo._internal.encoding.json.Json_T_intWithPtrMarshalText.T_intWithPtrMarshalText>)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("0.000001" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((1e-06 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("1e-7" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((1e-07 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("100000000000000000000" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((1e+20 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("1e+21" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((1e+21 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("-0.000001" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((-1e-06 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("-1e-7" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((-1e-07 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("-100000000000000000000" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((-1e+20 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("-1e+21" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((-1e+21 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("999999999999999900000" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((9.999999999999999e+20 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("9007199254740992" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((9.007199254740992e+15 : stdgo.GoFloat64)), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("9007199254740993" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((0 : stdgo.GoFloat64))), _out : stdgo.Go.toInterface((9.007199254740992e+15 : stdgo.GoFloat64)), _golden : false } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"V\": {\"F2\": \"hello\"}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_VOuter.VOuter)) : stdgo.Ref<stdgo._internal.encoding.json.Json_VOuter.VOuter>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("string" : stdgo.GoString), struct_ : ("V" : stdgo.GoString), field : ("V.F2" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt32))), offset : (20i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"V\": {\"F4\": {}, \"F2\": \"hello\"}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_VOuter.VOuter)) : stdgo.Ref<stdgo._internal.encoding.json.Json_VOuter.VOuter>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("string" : stdgo.GoString), struct_ : ("V" : stdgo.GoString), field : ("V.F2" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt32))), offset : (30i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\":\"true\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_B.B(true) : stdgo._internal.encoding.json.Json_B.B))), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\":\"false\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_B.B(false) : stdgo._internal.encoding.json.Json_B.B))), _golden : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\": \"maybe\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _err : stdgo._internal.errors.Errors_new_.new_(("json: invalid use of ,string struct tag, trying to unmarshal \"maybe\" into bool" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\": \"tru\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _err : stdgo._internal.errors.Errors_new_.new_(("json: invalid use of ,string struct tag, trying to unmarshal \"tru\" into bool" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\": \"False\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _err : stdgo._internal.errors.Errors_new_.new_(("json: invalid use of ,string struct tag, trying to unmarshal \"False\" into bool" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\": \"null\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _out : stdgo.Go.toInterface(stdgo.Go.asInterface((new stdgo._internal.encoding.json.Json_B.B(false) : stdgo._internal.encoding.json.Json_B.B))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\": \"nul\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _err : stdgo._internal.errors.Errors_new_.new_(("json: invalid use of ,string struct tag, trying to unmarshal \"nul\" into bool" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"B\": [2, 3]}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_B.B)) : stdgo.Ref<stdgo._internal.encoding.json.Json_B.B>))), _err : stdgo._internal.errors.Errors_new_.new_(("json: invalid use of ,string struct tag, trying to unmarshal unquoted value into bool" : stdgo.GoString)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\n\t\t\t\"Level0\": 1,\n\t\t\t\"Level1b\": 2,\n\t\t\t\"Level1c\": 3,\n\t\t\t\"x\": 4,\n\t\t\t\"Level1a\": 5,\n\t\t\t\"LEVEL1B\": 6,\n\t\t\t\"e\": {\n\t\t\t\t\"Level1a\": 8,\n\t\t\t\t\"Level1b\": 9,\n\t\t\t\t\"Level1c\": 10,\n\t\t\t\t\"Level1d\": 11,\n\t\t\t\t\"x\": 12\n\t\t\t},\n\t\t\t\"Loop1\": 13,\n\t\t\t\"Loop2\": 14,\n\t\t\t\"X\": 15,\n\t\t\t\"Y\": 16,\n\t\t\t\"Z\": 17,\n\t\t\t\"Q\": 18,\n\t\t\t\"extra\": true\n\t\t}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_Top.Top)) : stdgo.Ref<stdgo._internal.encoding.json.Json_Top.Top>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"extra\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\n\t\t\t\"Level0\": 1,\n\t\t\t\"Level1b\": 2,\n\t\t\t\"Level1c\": 3,\n\t\t\t\"x\": 4,\n\t\t\t\"Level1a\": 5,\n\t\t\t\"LEVEL1B\": 6,\n\t\t\t\"e\": {\n\t\t\t\t\"Level1a\": 8,\n\t\t\t\t\"Level1b\": 9,\n\t\t\t\t\"Level1c\": 10,\n\t\t\t\t\"Level1d\": 11,\n\t\t\t\t\"x\": 12,\n\t\t\t\t\"extra\": null\n\t\t\t},\n\t\t\t\"Loop1\": 13,\n\t\t\t\"Loop2\": 14,\n\t\t\t\"X\": 15,\n\t\t\t\"Y\": 16,\n\t\t\t\"Z\": 17,\n\t\t\t\"Q\": 18\n\t\t}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_Top.Top)) : stdgo.Ref<stdgo._internal.encoding.json.Json_Top.Top>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: unknown field \"extra\"" : stdgo.GoString)), _disallowUnknownFields : true } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"data\":{\"test1\": \"bob\", \"test2\": 123}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_mapStringToStringData.T_mapStringToStringData)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_mapStringToStringData.T_mapStringToStringData>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.str())), offset : (37i64 : stdgo.GoInt64), struct_ : ("mapStringToStringData" : stdgo.GoString), field : ("data" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"data\":{\"test1\": 123, \"test2\": \"bob\"}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_T_mapStringToStringData.T_mapStringToStringData)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T_mapStringToStringData.T_mapStringToStringData>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("number" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.str())), offset : (21i64 : stdgo.GoInt64), struct_ : ("mapStringToStringData" : stdgo.GoString), field : ("data" : stdgo.GoString) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("[1, 2, 3]" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText)) : stdgo.Ref<stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("array" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText() : stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText)) : stdgo.Ref<stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText>)))), offset : (1i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"foo\": \"bar\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText)) : stdgo.Ref<stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("object" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef((new stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText() : stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText)) : stdgo.Ref<stdgo._internal.encoding.json.Json_MustNotUnmarshalText.MustNotUnmarshalText>)))), offset : (1i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"PP\": {\"T\": {\"Y\": \"bad-type\"}}}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_P.P)) : stdgo.Ref<stdgo._internal.encoding.json.Json_P.P>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("string" : stdgo.GoString), struct_ : ("T" : stdgo.GoString), field : ("PP.T.Y" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt))), offset : (29i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"Ts\": [{\"Y\": 1}, {\"Y\": 2}, {\"Y\": \"bad-type\"}]}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({} : stdgo._internal.encoding.json.Json_PP.PP)) : stdgo.Ref<stdgo._internal.encoding.json.Json_PP.PP>))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ value : ("string" : stdgo.GoString), struct_ : ("T" : stdgo.GoString), field : ("Ts.Y" : stdgo.GoString), type : stdgo._internal.reflect.Reflect_typeOf.typeOf(stdgo.Go.toInterface((0 : stdgo.GoInt))), offset : (29i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_UnmarshalTypeError.UnmarshalTypeError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("invalid" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((("" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), _err : stdgo.Go.asInterface((stdgo.Go.setRef(({ _msg : ("invalid character \'i\' looking for beginning of value" : stdgo.GoString), offset : (1i64 : stdgo.GoInt64) } : stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError)) : stdgo.Ref<stdgo._internal.encoding.json.Json_SyntaxError.SyntaxError>)) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("\"invalid\"" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.pointer((("" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: invalid number literal, trying to unmarshal %q into Number" : stdgo.GoString), stdgo.Go.toInterface(("\"invalid\"" : stdgo.GoString))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"A\":\"invalid\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({ a : (("" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number) } : stdgo._internal.encoding.json.Json_T__struct_4.T__struct_4)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T__struct_4.T__struct_4>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: invalid number literal, trying to unmarshal %q into Number" : stdgo.GoString), stdgo.Go.toInterface(("\"invalid\"" : stdgo.GoString))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"A\":\"invalid\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface(stdgo.Go.asInterface((stdgo.Go.setRef(({ a : (("" : stdgo.GoString) : stdgo._internal.encoding.json.Json_Number.Number) } : stdgo._internal.encoding.json.Json_T__struct_5.T__struct_5)) : stdgo.Ref<stdgo._internal.encoding.json.Json_T__struct_5.T__struct_5>))), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: invalid use of ,string struct tag, trying to unmarshal %q into json.Number" : stdgo.GoString), stdgo.Go.toInterface(("invalid" : stdgo.GoString))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest),
({ _in : ("{\"A\":\"invalid\"}" : stdgo.GoString), _ptr : stdgo.Go.toInterface((stdgo.Go.setRef((null : stdgo.GoMap<stdgo.GoString, stdgo._internal.encoding.json.Json_Number.Number>)) : stdgo.Ref<stdgo.GoMap<stdgo.GoString, stdgo._internal.encoding.json.Json_Number.Number>>)), _err : stdgo._internal.fmt.Fmt_errorf.errorf(("json: invalid number literal, trying to unmarshal %q into Number" : stdgo.GoString), stdgo.Go.toInterface(("\"invalid\"" : stdgo.GoString))) } : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest)].concat([for (i in 152 ... (152 > 152 ? 152 : 152 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest)])) : stdgo.Slice<stdgo._internal.encoding.json.Json_T_unmarshalTest.T_unmarshalTest>);
