package stdgo._internal.encoding.json;
@:named @:using(stdgo._internal.encoding.json.Json_T_testStringKind___localname___stringKind_47067_static_extension.T_testStringKind___localname___stringKind_47067_static_extension) typedef T_testStringKind___localname___stringKind_47067 = stdgo.GoString;
