package stdgo._internal.encoding.json;
@:named @:using(stdgo._internal.encoding.json.Json_T_testSliceOfCustomByte___localname___Uint8_47988_static_extension.T_testSliceOfCustomByte___localname___Uint8_47988_static_extension) typedef T_testSliceOfCustomByte___localname___Uint8_47988 = stdgo.GoUInt8;
