package _internal.io_dot_test;
import stdgo._internal.io.Io;
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample>(18, 18, ...[
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleCopy" : stdgo.GoString), _internal.io_test.Io_test_exampleCopy.exampleCopy, ("some io.Reader stream to be read\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleCopyBuffer" : stdgo.GoString), _internal.io_test.Io_test_exampleCopyBuffer.exampleCopyBuffer, ("first reader\nsecond reader\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleCopyN" : stdgo.GoString), _internal.io_test.Io_test_exampleCopyN.exampleCopyN, ("some\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleReadAtLeast" : stdgo.GoString), _internal.io_test.Io_test_exampleReadAtLeast.exampleReadAtLeast, ("some io.Reader\nerror: short buffer\nerror: unexpected EOF\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleReadFull" : stdgo.GoString), _internal.io_test.Io_test_exampleReadFull.exampleReadFull, ("some\nerror: unexpected EOF\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleWriteString" : stdgo.GoString), _internal.io_test.Io_test_exampleWriteString.exampleWriteString, ("Hello World\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleLimitReader" : stdgo.GoString), _internal.io_test.Io_test_exampleLimitReader.exampleLimitReader, ("some\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleMultiReader" : stdgo.GoString), _internal.io_test.Io_test_exampleMultiReader.exampleMultiReader, ("first reader second reader third reader\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleTeeReader" : stdgo.GoString), _internal.io_test.Io_test_exampleTeeReader.exampleTeeReader, ("some io.Reader stream to be read\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSectionReader" : stdgo.GoString), _internal.io_test.Io_test_exampleSectionReader.exampleSectionReader, ("io.Reader stream\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSectionReader_Read" : stdgo.GoString), _internal.io_test.Io_test_exampleSectionReader_Read.exampleSectionReader_Read, ("io.Reader\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSectionReader_ReadAt" : stdgo.GoString), _internal.io_test.Io_test_exampleSectionReader_ReadAt.exampleSectionReader_ReadAt, ("stream\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSectionReader_Seek" : stdgo.GoString), _internal.io_test.Io_test_exampleSectionReader_Seek.exampleSectionReader_Seek, ("stream\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSectionReader_Size" : stdgo.GoString), _internal.io_test.Io_test_exampleSectionReader_Size.exampleSectionReader_Size, ("17\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSeeker_Seek" : stdgo.GoString), _internal.io_test.Io_test_exampleSeeker_Seek.exampleSeeker_Seek, ("io.Reader stream to be read\nread\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleMultiWriter" : stdgo.GoString), _internal.io_test.Io_test_exampleMultiWriter.exampleMultiWriter, ("some io.Reader stream to be read\nsome io.Reader stream to be read\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExamplePipe" : stdgo.GoString), _internal.io_test.Io_test_examplePipe.examplePipe, ("some io.Reader stream to be read\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleReadAll" : stdgo.GoString), _internal.io_test.Io_test_exampleReadAll.exampleReadAll, ("Go is a general-purpose language designed with systems programming in mind.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample)].concat([for (i in 18 ... (18 > 18 ? 18 : 18 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_InternalExample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample>);
