package stdgo._internal.image_test;
import stdgo._internal.image.Image;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>(8, 8, ...[(new stdgo._internal.testing.Testing.InternalTest(("TestRectangle" : stdgo.GoString), stdgo._internal.image.Image.testRectangle) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestImage" : stdgo.GoString), stdgo._internal.image.Image.testImage) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestNewXxxBadRectangle" : stdgo.GoString), stdgo._internal.image.Image.testNewXxxBadRectangle) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("Test16BitsPerColorChannel" : stdgo.GoString), stdgo._internal.image.Image.test16BitsPerColorChannel) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestRGBA64Image" : stdgo.GoString), stdgo._internal.image.Image.testRGBA64Image) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestYCbCr" : stdgo.GoString), stdgo._internal.image.Image.testYCbCr) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestYCbCrSlicesDontOverlap" : stdgo.GoString), stdgo._internal.image.Image.testYCbCrSlicesDontOverlap) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestDecode" : stdgo.GoString), stdgo._internal.image_test.Image_test.testDecode) : stdgo._internal.testing.Testing.InternalTest)].concat([for (i in 8 ... (8 > 8 ? 8 : 8 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>(18, 18, ...[
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAt" : stdgo.GoString), stdgo._internal.image.Image.benchmarkAt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSet" : stdgo.GoString), stdgo._internal.image.Image.benchmarkSet) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRGBAAt" : stdgo.GoString), stdgo._internal.image.Image.benchmarkRGBAAt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRGBASetRGBA" : stdgo.GoString), stdgo._internal.image.Image.benchmarkRGBASetRGBA) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRGBA64At" : stdgo.GoString), stdgo._internal.image.Image.benchmarkRGBA64At) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRGBA64SetRGBA64" : stdgo.GoString), stdgo._internal.image.Image.benchmarkRGBA64SetRGBA64) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNRGBAAt" : stdgo.GoString), stdgo._internal.image.Image.benchmarkNRGBAAt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNRGBASetNRGBA" : stdgo.GoString), stdgo._internal.image.Image.benchmarkNRGBASetNRGBA) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNRGBA64At" : stdgo.GoString), stdgo._internal.image.Image.benchmarkNRGBA64At) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNRGBA64SetNRGBA64" : stdgo.GoString), stdgo._internal.image.Image.benchmarkNRGBA64SetNRGBA64) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAlphaAt" : stdgo.GoString), stdgo._internal.image.Image.benchmarkAlphaAt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAlphaSetAlpha" : stdgo.GoString), stdgo._internal.image.Image.benchmarkAlphaSetAlpha) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAlpha16At" : stdgo.GoString), stdgo._internal.image.Image.benchmarkAlpha16At) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAlphaSetAlpha16" : stdgo.GoString), stdgo._internal.image.Image.benchmarkAlphaSetAlpha16) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkGrayAt" : stdgo.GoString), stdgo._internal.image.Image.benchmarkGrayAt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkGraySetGray" : stdgo.GoString), stdgo._internal.image.Image.benchmarkGraySetGray) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkGray16At" : stdgo.GoString), stdgo._internal.image.Image.benchmarkGray16At) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkGraySetGray16" : stdgo.GoString), stdgo._internal.image.Image.benchmarkGraySetGray16) : stdgo._internal.testing.Testing.InternalBenchmark)].concat([for (i in 18 ... (18 > 18 ? 18 : 18 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>(1, 1, ...[(new stdgo._internal.testing.Testing.InternalExample(("Example" : stdgo.GoString), stdgo._internal.image_test.Image_test.example, ("bin               red  green   blue  alpha\n0x0000-0x0fff:    364    790   7242      0\n0x1000-0x1fff:    645   2967   1039      0\n0x2000-0x2fff:   1072   2299    979      0\n0x3000-0x3fff:    820   2266    980      0\n0x4000-0x4fff:    537   1305    541      0\n0x5000-0x5fff:    319    962    261      0\n0x6000-0x6fff:    322    375    177      0\n0x7000-0x7fff:    601    279    214      0\n0x8000-0x8fff:   3478    227    273      0\n0x9000-0x9fff:   2260    234    329      0\n0xa000-0xafff:    921    282    373      0\n0xb000-0xbfff:    321    335    397      0\n0xc000-0xcfff:    229    388    298      0\n0xd000-0xdfff:    260    414    277      0\n0xe000-0xefff:    516    428    298      0\n0xf000-0xffff:   2785   1899   1772  15450\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo._internal.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        Sys.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo._internal.testing.internal.testdeps.Testdeps.importPath = ("image" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
