package stdgo._internal.math_test;
import stdgo._internal.math.Math;
import stdgo._internal.math.Math;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>(76, 76, ...[
(new stdgo._internal.testing.Testing.InternalTest(("TestNaN" : stdgo.GoString), stdgo._internal.math_test.Math_test.testNaN) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAcos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAcos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAcosh" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAcosh) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAsin" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAsin) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAsinh" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAsinh) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAtan" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAtan) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAtanh" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAtanh) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAtan2" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAtan2) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCbrt" : stdgo.GoString), stdgo._internal.math_test.Math_test.testCbrt) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCeil" : stdgo.GoString), stdgo._internal.math_test.Math_test.testCeil) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCopysign" : stdgo.GoString), stdgo._internal.math_test.Math_test.testCopysign) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testCos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCosh" : stdgo.GoString), stdgo._internal.math_test.Math_test.testCosh) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestErf" : stdgo.GoString), stdgo._internal.math_test.Math_test.testErf) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestErfc" : stdgo.GoString), stdgo._internal.math_test.Math_test.testErfc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestErfinv" : stdgo.GoString), stdgo._internal.math_test.Math_test.testErfinv) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestErfcinv" : stdgo.GoString), stdgo._internal.math_test.Math_test.testErfcinv) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestExp" : stdgo.GoString), stdgo._internal.math_test.Math_test.testExp) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestExpm1" : stdgo.GoString), stdgo._internal.math_test.Math_test.testExpm1) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestExp2" : stdgo.GoString), stdgo._internal.math_test.Math_test.testExp2) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAbs" : stdgo.GoString), stdgo._internal.math_test.Math_test.testAbs) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDim" : stdgo.GoString), stdgo._internal.math_test.Math_test.testDim) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFloor" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFloor) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMax" : stdgo.GoString), stdgo._internal.math_test.Math_test.testMax) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMin" : stdgo.GoString), stdgo._internal.math_test.Math_test.testMin) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMod" : stdgo.GoString), stdgo._internal.math_test.Math_test.testMod) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFrexp" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFrexp) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestGamma" : stdgo.GoString), stdgo._internal.math_test.Math_test.testGamma) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHypot" : stdgo.GoString), stdgo._internal.math_test.Math_test.testHypot) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHypotGo" : stdgo.GoString), stdgo._internal.math_test.Math_test.testHypotGo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIlogb" : stdgo.GoString), stdgo._internal.math_test.Math_test.testIlogb) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestJ0" : stdgo.GoString), stdgo._internal.math_test.Math_test.testJ0) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestJ1" : stdgo.GoString), stdgo._internal.math_test.Math_test.testJ1) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestJn" : stdgo.GoString), stdgo._internal.math_test.Math_test.testJn) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLdexp" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLdexp) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLgamma" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLgamma) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLog" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLog) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLogb" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLogb) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLog10" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLog10) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLog1p" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLog1p) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLog2" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLog2) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestModf" : stdgo.GoString), stdgo._internal.math_test.Math_test.testModf) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestNextafter32" : stdgo.GoString), stdgo._internal.math_test.Math_test.testNextafter32) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestNextafter64" : stdgo.GoString), stdgo._internal.math_test.Math_test.testNextafter64) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestPow" : stdgo.GoString), stdgo._internal.math_test.Math_test.testPow) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestPow10" : stdgo.GoString), stdgo._internal.math_test.Math_test.testPow10) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestRemainder" : stdgo.GoString), stdgo._internal.math_test.Math_test.testRemainder) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestRound" : stdgo.GoString), stdgo._internal.math_test.Math_test.testRound) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestRoundToEven" : stdgo.GoString), stdgo._internal.math_test.Math_test.testRoundToEven) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSignbit" : stdgo.GoString), stdgo._internal.math_test.Math_test.testSignbit) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSin" : stdgo.GoString), stdgo._internal.math_test.Math_test.testSin) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSincos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testSincos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSinh" : stdgo.GoString), stdgo._internal.math_test.Math_test.testSinh) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSqrt" : stdgo.GoString), stdgo._internal.math_test.Math_test.testSqrt) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTan" : stdgo.GoString), stdgo._internal.math_test.Math_test.testTan) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTanh" : stdgo.GoString), stdgo._internal.math_test.Math_test.testTanh) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTrunc" : stdgo.GoString), stdgo._internal.math_test.Math_test.testTrunc) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestY0" : stdgo.GoString), stdgo._internal.math_test.Math_test.testY0) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestY1" : stdgo.GoString), stdgo._internal.math_test.Math_test.testY1) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestYn" : stdgo.GoString), stdgo._internal.math_test.Math_test.testYn) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFMA" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFMA) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFMANegativeArgs" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFMANegativeArgs) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLargeCos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLargeCos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLargeSin" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLargeSin) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLargeSincos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLargeSincos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLargeTan" : stdgo.GoString), stdgo._internal.math_test.Math_test.testLargeTan) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTrigReduce" : stdgo.GoString), stdgo._internal.math_test.Math_test.testTrigReduce) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFloatMinMax" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFloatMinMax) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFloatMinima" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFloatMinima) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFloat32Sqrt" : stdgo.GoString), stdgo._internal.math_test.Math_test.testFloat32Sqrt) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMaxUint" : stdgo.GoString), stdgo._internal.math_test.Math_test.testMaxUint) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMaxInt" : stdgo.GoString), stdgo._internal.math_test.Math_test.testMaxInt) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHugeCos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testHugeCos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHugeSin" : stdgo.GoString), stdgo._internal.math_test.Math_test.testHugeSin) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHugeSinCos" : stdgo.GoString), stdgo._internal.math_test.Math_test.testHugeSinCos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHugeTan" : stdgo.GoString), stdgo._internal.math_test.Math_test.testHugeTan) : stdgo._internal.testing.Testing.InternalTest)].concat([for (i in 76 ... (76 > 76 ? 76 : 76 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>(72, 72, ...[
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAcos" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAcos) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAcosh" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAcosh) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAsin" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAsin) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAsinh" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAsinh) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAtan" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAtan) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAtanh" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAtanh) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAtan2" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAtan2) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCbrt" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkCbrt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCeil" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkCeil) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCopysign" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkCopysign) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCos" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkCos) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCosh" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkCosh) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkErf" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkErf) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkErfc" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkErfc) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkErfinv" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkErfinv) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkErfcinv" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkErfcinv) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkExp" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkExp) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkExpGo" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkExpGo) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkExpm1" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkExpm1) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkExp2" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkExp2) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkExp2Go" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkExp2Go) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkAbs" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkAbs) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkDim" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkDim) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFloor" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFloor) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkMax" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkMax) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkMin" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkMin) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkMod" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkMod) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFrexp" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFrexp) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkGamma" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkGamma) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkHypot" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkHypot) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkHypotGo" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkHypotGo) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkIlogb" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkIlogb) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkJ0" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkJ0) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkJ1" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkJ1) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkJn" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkJn) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLdexp" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLdexp) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLgamma" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLgamma) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLog" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLog) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLogb" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLogb) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLog1p" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLog1p) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLog10" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLog10) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLog2" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkLog2) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkModf" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkModf) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNextafter32" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkNextafter32) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNextafter64" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkNextafter64) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkPowInt" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkPowInt) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkPowFrac" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkPowFrac) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkPow10Pos" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkPow10Pos) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkPow10Neg" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkPow10Neg) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRound" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkRound) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRoundToEven" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkRoundToEven) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkRemainder" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkRemainder) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSignbit" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSignbit) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSin" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSin) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSincos" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSincos) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSinh" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSinh) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSqrtIndirect" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSqrtIndirect) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSqrtLatency" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSqrtLatency) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSqrtIndirectLatency" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSqrtIndirectLatency) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSqrtGoLatency" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSqrtGoLatency) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkSqrtPrime" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkSqrtPrime) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkTan" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkTan) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkTanh" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkTanh) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkTrunc" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkTrunc) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkY0" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkY0) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkY1" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkY1) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkYn" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkYn) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFloat64bits" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFloat64bits) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFloat64frombits" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFloat64frombits) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFloat32bits" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFloat32bits) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFloat32frombits" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFloat32frombits) : stdgo._internal.testing.Testing.InternalBenchmark),
(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkFMA" : stdgo.GoString), stdgo._internal.math_test.Math_test.benchmarkFMA) : stdgo._internal.testing.Testing.InternalBenchmark)].concat([for (i in 72 ... (72 > 72 ? 72 : 72 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>(35, 35, ...[
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAcos" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAcos, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAcosh" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAcosh, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAsin" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAsin, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAsinh" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAsinh, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAtan" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAtan, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAtan2" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAtan2, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAtanh" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAtanh, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCopysign" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleCopysign, ("-3.20\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCos" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleCos, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCosh" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleCosh, ("1.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSin" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleSin, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSincos" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleSincos, ("0.00, 1.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSinh" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleSinh, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleTan" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleTan, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleTanh" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleTanh, ("0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleSqrt" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleSqrt, ("5.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCeil" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleCeil, ("2.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleFloor" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleFloor, ("1.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExamplePow" : stdgo.GoString), stdgo._internal.math_test.Math_test.examplePow, ("8.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExamplePow10" : stdgo.GoString), stdgo._internal.math_test.Math_test.examplePow10, ("100.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleRound" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleRound, ("11.0\n-11.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleRoundToEven" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleRoundToEven, ("12.0\n12.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleLog" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleLog, ("0.0\n1.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleLog2" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleLog2, ("8.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleLog10" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleLog10, ("2.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleRemainder" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleRemainder, ("10.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleMod" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleMod, ("3.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleAbs" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleAbs, ("2.0\n2.0\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleDim" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleDim, ("6.00\n0.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleExp" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleExp, ("2.72\n7.39\n0.37\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleExp2" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleExp2, ("2.00\n0.12\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleExpm1" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleExpm1, ("0.010050\n-0.632121\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleTrunc" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleTrunc, ("3.00\n-1.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleCbrt" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleCbrt, ("2.00\n3.00\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample),
(new stdgo._internal.testing.Testing.InternalExample(("ExampleModf" : stdgo.GoString), stdgo._internal.math_test.Math_test.exampleModf, ("3.00, 0.14\n-2.00, -0.71\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample)].concat([for (i in 35 ... (35 > 35 ? 35 : 35 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo._internal.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        Sys.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo._internal.testing.internal.testdeps.Testdeps.importPath = ("math" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
