package stdgo._internal.context;
@:keep @:using(stdgo._internal.context.Context_T_deadlineExceededError_static_extension.T_deadlineExceededError_static_extension) typedef T_deadlineExceededErrorPointer = stdgo.Pointer<stdgo._internal.context.Context_T_deadlineExceededError.T_deadlineExceededError>;
