package _internal.strings_test;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
var containsTests : stdgo.Slice<_internal.strings_test.Strings_test_T__struct_22.T__struct_22> = (new stdgo.Slice<_internal.strings_test.Strings_test_T__struct_22.T__struct_22>(56, 56, ...[
({ _str : ("abc" : stdgo.GoString), _substr : ("bc" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("abc" : stdgo.GoString), _substr : ("bcd" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("abc" : stdgo.GoString), _substr : stdgo.Go.str()?.__copy__(), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : stdgo.Go.str()?.__copy__(), _substr : ("a" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxx" : stdgo.GoString), _substr : ("01" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("01xxxx" : stdgo.GoString), _substr : ("01" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx01xx" : stdgo.GoString), _substr : ("01" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx01" : stdgo.GoString), _substr : ("01" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("01xxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("01" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx01" : stdgo.GoString).__slice__(0, (6 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("01" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxx" : stdgo.GoString), _substr : ("012" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("012xxxx" : stdgo.GoString), _substr : ("012" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx012xx" : stdgo.GoString), _substr : ("012" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx012" : stdgo.GoString), _substr : ("012" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("012xxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("012" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx012" : stdgo.GoString).__slice__(0, (7 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("012" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxxx" : stdgo.GoString), _substr : ("0123" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("0123xxxx" : stdgo.GoString), _substr : ("0123" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx0123xx" : stdgo.GoString), _substr : ("0123" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx0123" : stdgo.GoString), _substr : ("0123" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("0123xxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("0123" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx0123" : stdgo.GoString).__slice__(0, (8 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("0123" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxxxx" : stdgo.GoString), _substr : ("01234" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("01234xxxx" : stdgo.GoString), _substr : ("01234" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx01234xx" : stdgo.GoString), _substr : ("01234" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx01234" : stdgo.GoString), _substr : ("01234" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("01234xxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("01234" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx01234" : stdgo.GoString).__slice__(0, (9 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("01234" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxxxxxxx" : stdgo.GoString), _substr : ("01234567" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("01234567xxxx" : stdgo.GoString), _substr : ("01234567" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx01234567xx" : stdgo.GoString), _substr : ("01234567" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx01234567" : stdgo.GoString), _substr : ("01234567" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("01234567xxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("01234567" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx01234567" : stdgo.GoString).__slice__(0, (12 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("01234567" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxxxxxxxx" : stdgo.GoString), _substr : ("012345678" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("012345678xxxx" : stdgo.GoString), _substr : ("012345678" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx012345678xx" : stdgo.GoString), _substr : ("012345678" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx012345678" : stdgo.GoString), _substr : ("012345678" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("012345678xxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("012345678" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx012345678" : stdgo.GoString).__slice__(0, (13 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("012345678" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxxxxxxxxxxxxxxx" : stdgo.GoString), _substr : ("0123456789ABCDEF" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("0123456789ABCDEFxxxx" : stdgo.GoString), _substr : ("0123456789ABCDEF" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx0123456789ABCDEFxx" : stdgo.GoString), _substr : ("0123456789ABCDEF" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx0123456789ABCDEF" : stdgo.GoString), _substr : ("0123456789ABCDEF" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("0123456789ABCDEFxxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("0123456789ABCDEF" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx0123456789ABCDEF" : stdgo.GoString).__slice__(0, (20 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("0123456789ABCDEF" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxxxxxxxxxxxxxxxxxxx" : stdgo.GoString), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("0123456789ABCDEFGxxxx" : stdgo.GoString), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx0123456789ABCDEFGxx" : stdgo.GoString), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xxxx0123456789ABCDEFG" : stdgo.GoString), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : true } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("0123456789ABCDEFGxxxxx" : stdgo.GoString).__slice__((1 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : (("xxxxx0123456789ABCDEFG" : stdgo.GoString).__slice__(0, (21 : stdgo.GoInt)) : stdgo.GoString)?.__copy__(), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx01x" : stdgo.GoString), _substr : ("012" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx0123x" : stdgo.GoString), _substr : ("01234" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx01234567x" : stdgo.GoString), _substr : ("012345678" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22),
({ _str : ("xx0123456789ABCDEFx" : stdgo.GoString), _substr : ("0123456789ABCDEFG" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22)].concat([for (i in 56 ... (56 > 56 ? 56 : 56 : stdgo.GoInt).toBasic()) ({ _str : ("" : stdgo.GoString), _substr : ("" : stdgo.GoString), _expected : false } : _internal.strings_test.Strings_test_T__struct_22.T__struct_22)])) : stdgo.Slice<_internal.strings_test.Strings_test_T__struct_22.T__struct_22>);
