package _internal.strings_test;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
function testReplacer(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
        trace("testReplacer" + " skip function");
        return;
        {};
        var _testCases:stdgo.Slice<_internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871> = (null : stdgo.Slice<_internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871>);
        var _str = (function(_b:stdgo.GoUInt8):stdgo.GoString {
            return ((new stdgo.Slice<stdgo.GoUInt8>(1, 1, ...[_b]).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>) : stdgo.GoString)?.__copy__();
        } : stdgo.GoUInt8 -> stdgo.GoString);
        var _s:stdgo.Slice<stdgo.GoString> = (null : stdgo.Slice<stdgo.GoString>);
        _s = (null : stdgo.Slice<stdgo.GoString>);
        {
            var _i = (0 : stdgo.GoInt);
            stdgo.Go.cfor((_i < (256 : stdgo.GoInt) : Bool), _i++, {
                _s = (_s.__append__(_str((_i : stdgo.GoUInt8))?.__copy__(), _str(((_i + (1 : stdgo.GoInt) : stdgo.GoInt) : stdgo.GoUInt8))?.__copy__()));
            });
        };
        var _inc = stdgo._internal.strings.Strings_newReplacer.newReplacer(...(_s : Array<stdgo.GoString>));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__capitalLetters._capitalLetters, ("brad" : stdgo.GoString), ("BrAd" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__capitalLetters._capitalLetters, stdgo._internal.strings.Strings_repeat.repeat(("a" : stdgo.GoString), (32891 : stdgo.GoInt))?.__copy__(), stdgo._internal.strings.Strings_repeat.repeat(("A" : stdgo.GoString), (32891 : stdgo.GoInt))?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__capitalLetters._capitalLetters, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_inc, ("brad" : stdgo.GoString), ("csbe" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_inc, stdgo.Go.str(0, 255)?.__copy__(), stdgo.Go.str(1, 0)?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_inc, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(stdgo._internal.strings.Strings_newReplacer.newReplacer(("a" : stdgo.GoString), ("1" : stdgo.GoString), ("a" : stdgo.GoString), ("2" : stdgo.GoString)), ("brad" : stdgo.GoString), ("br1d" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        _s = (null : stdgo.Slice<stdgo.GoString>);
        {
            var _i = (0 : stdgo.GoInt);
            stdgo.Go.cfor((_i < (256 : stdgo.GoInt) : Bool), _i++, {
                var _n = ((_i + (1 : stdgo.GoInt) : stdgo.GoInt) - (97 : stdgo.GoInt) : stdgo.GoInt);
                if ((_n < (1 : stdgo.GoInt) : Bool)) {
                    _n = (1 : stdgo.GoInt);
                };
                _s = (_s.__append__(_str((_i : stdgo.GoUInt8))?.__copy__(), stdgo._internal.strings.Strings_repeat.repeat(_str((_i : stdgo.GoUInt8))?.__copy__(), _n)?.__copy__()));
            });
        };
        var _repeat = stdgo._internal.strings.Strings_newReplacer.newReplacer(...(_s : Array<stdgo.GoString>));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlEscaper._htmlEscaper, ("No changes" : stdgo.GoString), ("No changes" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlEscaper._htmlEscaper, ("I <3 escaping & stuff" : stdgo.GoString), ("I &lt;3 escaping &amp; stuff" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlEscaper._htmlEscaper, ("&&&" : stdgo.GoString), ("&amp;&amp;&amp;" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlEscaper._htmlEscaper, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_repeat, ("brad" : stdgo.GoString), ("bbrrrrrrrrrrrrrrrrrradddd" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_repeat, ("abba" : stdgo.GoString), ("abbbba" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_repeat, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(stdgo._internal.strings.Strings_newReplacer.newReplacer(("a" : stdgo.GoString), ("11" : stdgo.GoString), ("a" : stdgo.GoString), ("22" : stdgo.GoString)), ("brad" : stdgo.GoString), ("br11d" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlUnescaper._htmlUnescaper, ("&amp;amp;" : stdgo.GoString), ("&amp;" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlUnescaper._htmlUnescaper, ("&lt;b&gt;HTML&apos;s neat&lt;/b&gt;" : stdgo.GoString), ("<b>HTML\'s neat</b>" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_internal.strings_test.Strings_test__htmlUnescaper._htmlUnescaper, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(stdgo._internal.strings.Strings_newReplacer.newReplacer(("a" : stdgo.GoString), ("1" : stdgo.GoString), ("a" : stdgo.GoString), ("2" : stdgo.GoString), ("xxx" : stdgo.GoString), ("xxx" : stdgo.GoString)), ("brad" : stdgo.GoString), ("br1d" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(stdgo._internal.strings.Strings_newReplacer.newReplacer(("a" : stdgo.GoString), ("1" : stdgo.GoString), ("aa" : stdgo.GoString), ("2" : stdgo.GoString), ("aaa" : stdgo.GoString), ("3" : stdgo.GoString)), ("aaaa" : stdgo.GoString), ("1111" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(stdgo._internal.strings.Strings_newReplacer.newReplacer(("aaa" : stdgo.GoString), ("3" : stdgo.GoString), ("aa" : stdgo.GoString), ("2" : stdgo.GoString), ("a" : stdgo.GoString), ("1" : stdgo.GoString)), ("aaaa" : stdgo.GoString), ("31" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _gen1 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("aaa" : stdgo.GoString),
("3[aaa]" : stdgo.GoString),
("aa" : stdgo.GoString),
("2[aa]" : stdgo.GoString),
("a" : stdgo.GoString),
("1[a]" : stdgo.GoString),
("i" : stdgo.GoString),
("i" : stdgo.GoString),
("longerst" : stdgo.GoString),
("most long" : stdgo.GoString),
("longer" : stdgo.GoString),
("medium" : stdgo.GoString),
("long" : stdgo.GoString),
("short" : stdgo.GoString),
("xx" : stdgo.GoString),
("xx" : stdgo.GoString),
("x" : stdgo.GoString),
("X" : stdgo.GoString),
("X" : stdgo.GoString),
("Y" : stdgo.GoString),
("Y" : stdgo.GoString),
("Z" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen1, ("fooaaabar" : stdgo.GoString), ("foo3[aaa]b1[a]r" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen1, ("long, longerst, longer" : stdgo.GoString), ("short, most long, medium" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen1, ("xxxxx" : stdgo.GoString), ("xxxxX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen1, ("XiX" : stdgo.GoString), ("YiY" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen1, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _gen2 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("roses" : stdgo.GoString), ("red" : stdgo.GoString), ("violets" : stdgo.GoString), ("blue" : stdgo.GoString), ("sugar" : stdgo.GoString), ("sweet" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen2, ("roses are red, violets are blue..." : stdgo.GoString), ("red are red, blue are blue..." : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen2, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _gen3 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("abracadabra" : stdgo.GoString), ("poof" : stdgo.GoString), ("abracadabrakazam" : stdgo.GoString), ("splat" : stdgo.GoString), ("abraham" : stdgo.GoString), ("lincoln" : stdgo.GoString), ("abrasion" : stdgo.GoString), ("scrape" : stdgo.GoString), ("abraham" : stdgo.GoString), ("isaac" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen3, ("abracadabrakazam abraham" : stdgo.GoString), ("poofkazam lincoln" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen3, ("abrasion abracad" : stdgo.GoString), ("scrape abracad" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen3, ("abba abram abrasive" : stdgo.GoString), ("abba abram abrasive" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_gen3, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _foo1 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("foo1" : stdgo.GoString), ("A" : stdgo.GoString), ("foo2" : stdgo.GoString), ("B" : stdgo.GoString), ("foo3" : stdgo.GoString), ("C" : stdgo.GoString));
        var _foo2 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("foo1" : stdgo.GoString), ("A" : stdgo.GoString), ("foo2" : stdgo.GoString), ("B" : stdgo.GoString), ("foo31" : stdgo.GoString), ("C" : stdgo.GoString), ("foo32" : stdgo.GoString), ("D" : stdgo.GoString));
        var _foo3 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("foo11" : stdgo.GoString), ("A" : stdgo.GoString), ("foo12" : stdgo.GoString), ("B" : stdgo.GoString), ("foo31" : stdgo.GoString), ("C" : stdgo.GoString), ("foo32" : stdgo.GoString), ("D" : stdgo.GoString));
        var _foo4 = stdgo._internal.strings.Strings_newReplacer.newReplacer(("foo12" : stdgo.GoString), ("B" : stdgo.GoString), ("foo32" : stdgo.GoString), ("D" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo1, ("fofoofoo12foo32oo" : stdgo.GoString), ("fofooA2C2oo" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo1, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo2, ("fofoofoo12foo32oo" : stdgo.GoString), ("fofooA2Doo" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo2, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo3, ("fofoofoo12foo32oo" : stdgo.GoString), ("fofooBDoo" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo3, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo4, ("fofoofoo12foo32oo" : stdgo.GoString), ("fofooBDoo" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_foo4, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _allBytes = (new stdgo.Slice<stdgo.GoUInt8>((256 : stdgo.GoInt).toBasic(), 0).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>);
        for (_i => _ in _allBytes) {
            _allBytes[(_i : stdgo.GoInt)] = (_i : stdgo.GoUInt8);
        };
        var _allString = ((_allBytes : stdgo.GoString)?.__copy__() : stdgo.GoString);
        var _genAll = stdgo._internal.strings.Strings_newReplacer.newReplacer(_allString?.__copy__(), ("[all]" : stdgo.GoString), stdgo.Go.str(255)?.__copy__(), ("[ff]" : stdgo.GoString), stdgo.Go.str(0)?.__copy__(), ("[00]" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_genAll, _allString?.__copy__(), ("[all]" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_genAll, ((stdgo.Go.str("a", 255) + _allString?.__copy__() : stdgo.GoString) + stdgo.Go.str(0)?.__copy__() : stdgo.GoString)?.__copy__(), ("a[ff][all][00]" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_genAll, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _blankToX1 = stdgo._internal.strings.Strings_newReplacer.newReplacer(stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString));
        var _blankToX2 = stdgo._internal.strings.Strings_newReplacer.newReplacer(stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString), stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__());
        var _blankHighPriority = stdgo._internal.strings.Strings_newReplacer.newReplacer(stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString), ("o" : stdgo.GoString), ("O" : stdgo.GoString));
        var _blankLowPriority = stdgo._internal.strings.Strings_newReplacer.newReplacer(("o" : stdgo.GoString), ("O" : stdgo.GoString), stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString));
        var _blankNoOp1 = stdgo._internal.strings.Strings_newReplacer.newReplacer(stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__());
        var _blankNoOp2 = stdgo._internal.strings.Strings_newReplacer.newReplacer(stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__(), ("A" : stdgo.GoString));
        var _blankFoo = stdgo._internal.strings.Strings_newReplacer.newReplacer(stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString), ("foobar" : stdgo.GoString), ("R" : stdgo.GoString), ("foobaz" : stdgo.GoString), ("Z" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankToX1, ("foo" : stdgo.GoString), ("XfXoXoX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankToX1, stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankToX2, ("foo" : stdgo.GoString), ("XfXoXoX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankToX2, stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankHighPriority, ("oo" : stdgo.GoString), ("XOXOX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankHighPriority, ("ii" : stdgo.GoString), ("XiXiX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankHighPriority, ("oiio" : stdgo.GoString), ("XOXiXiXOX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankHighPriority, ("iooi" : stdgo.GoString), ("XiXOXOXiX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankHighPriority, stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankLowPriority, ("oo" : stdgo.GoString), ("OOX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankLowPriority, ("ii" : stdgo.GoString), ("XiXiX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankLowPriority, ("oiio" : stdgo.GoString), ("OXiXiOX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankLowPriority, ("iooi" : stdgo.GoString), ("XiOOXiX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankLowPriority, stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankNoOp1, ("foo" : stdgo.GoString), ("foo" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankNoOp1, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankNoOp2, ("foo" : stdgo.GoString), ("foo" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankNoOp2, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankFoo, ("foobarfoobaz" : stdgo.GoString), ("XRXZX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankFoo, ("foobar-foobaz" : stdgo.GoString), ("XRX-XZX" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871),
(new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_blankFoo, stdgo.Go.str()?.__copy__(), ("X" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _abcMatcher = stdgo._internal.strings.Strings_newReplacer.newReplacer(("abc" : stdgo.GoString), ("[match]" : stdgo.GoString));
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_abcMatcher, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_abcMatcher, ("ab" : stdgo.GoString), ("ab" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_abcMatcher, ("abc" : stdgo.GoString), ("[match]" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_abcMatcher, ("abcd" : stdgo.GoString), ("[match]d" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_abcMatcher, ("cabcabcdabca" : stdgo.GoString), ("c[match][match]d[match]a" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _noHello = stdgo._internal.strings.Strings_newReplacer.newReplacer(("Hello" : stdgo.GoString), stdgo.Go.str()?.__copy__());
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_noHello, ("Hello" : stdgo.GoString), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_noHello, ("Hellox" : stdgo.GoString), ("x" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_noHello, ("xHello" : stdgo.GoString), ("x" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_noHello, ("xHellox" : stdgo.GoString), ("xx" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        var _nop = stdgo._internal.strings.Strings_newReplacer.newReplacer();
        _testCases = (_testCases.__append__((new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_nop, ("abc" : stdgo.GoString), ("abc" : stdgo.GoString)) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871), (new _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871(_nop, stdgo.Go.str()?.__copy__(), stdgo.Go.str()?.__copy__()) : _internal.strings_test.Strings_test_T_testReplacer___localname___testCase_871.T_testReplacer___localname___testCase_871)));
        for (_i => _tc in _testCases) {
            {
                var _s = (_tc._r.replace(_tc._in?.__copy__())?.__copy__() : stdgo.GoString);
                if (_s != (_tc._out)) {
                    _t.errorf(("%d. Replace(%q) = %q, want %q" : stdgo.GoString), stdgo.Go.toInterface(_i), stdgo.Go.toInterface(_tc._in), stdgo.Go.toInterface(_s), stdgo.Go.toInterface(_tc._out));
                };
            };
            var _buf:stdgo._internal.bytes.Bytes_Buffer.Buffer = ({} : stdgo._internal.bytes.Bytes_Buffer.Buffer);
            var __tmp__ = _tc._r.writeString(stdgo.Go.asInterface((stdgo.Go.setRef(_buf) : stdgo.Ref<stdgo._internal.bytes.Bytes_Buffer.Buffer>)), _tc._in?.__copy__()), _n:stdgo.GoInt = __tmp__._0, _err:stdgo.Error = __tmp__._1;
            if (_err != null) {
                _t.errorf(("%d. WriteString: %v" : stdgo.GoString), stdgo.Go.toInterface(_i), stdgo.Go.toInterface(_err));
                continue;
            };
            var _got = ((_buf.string() : stdgo.GoString)?.__copy__() : stdgo.GoString);
            if (_got != (_tc._out)) {
                _t.errorf(("%d. WriteString(%q) wrote %q, want %q" : stdgo.GoString), stdgo.Go.toInterface(_i), stdgo.Go.toInterface(_tc._in), stdgo.Go.toInterface(_got), stdgo.Go.toInterface(_tc._out));
                continue;
            };
            if (_n != ((_tc._out.length))) {
                _t.errorf(("%d. WriteString(%q) wrote correct string but reported %d bytes; want %d (%q)" : stdgo.GoString), stdgo.Go.toInterface(_i), stdgo.Go.toInterface(_tc._in), stdgo.Go.toInterface(_n), stdgo.Go.toInterface((_tc._out.length)), stdgo.Go.toInterface(_tc._out));
            };
        };
    }
