package _internal.strings_test;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
import stdgo._internal.strings.Strings;
var _fieldstests : stdgo.Slice<_internal.strings_test.Strings_test_FieldsTest.FieldsTest> = (new stdgo.Slice<_internal.strings_test.Strings_test_FieldsTest.FieldsTest>(15, 15, ...[
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(stdgo.Go.str()?.__copy__(), (new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest((" " : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest((" \t " : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("\u2000" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("  abc  " : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("abc" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("1 2 3 4" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[("1" : stdgo.GoString), ("2" : stdgo.GoString), ("3" : stdgo.GoString), ("4" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("1  2  3  4" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[("1" : stdgo.GoString), ("2" : stdgo.GoString), ("3" : stdgo.GoString), ("4" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("1\t\t2\t\t3\t4" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[("1" : stdgo.GoString), ("2" : stdgo.GoString), ("3" : stdgo.GoString), ("4" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("1\u20002\u20013\u20024" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(4, 4, ...[("1" : stdgo.GoString), ("2" : stdgo.GoString), ("3" : stdgo.GoString), ("4" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("\u2000\u2001\u2002" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(0, 0, ...[]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("\n™\t™\n" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("™" : stdgo.GoString), ("™" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("\n\u20001™2\u2000 \u2001 ™" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("1™2" : stdgo.GoString), ("™" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(("\n1� �2\u20003�4" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(3, 3, ...[("1�" : stdgo.GoString), ("�2" : stdgo.GoString), ("3�4" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(stdgo.Go.str("1", 255, "\u2000", 255, "2", 255, " ", 255)?.__copy__(), (new stdgo.Slice<stdgo.GoString>(3, 3, ...[stdgo.Go.str("1", 255)?.__copy__(), stdgo.Go.str(255, "2", 255)?.__copy__(), stdgo.Go.str(255)?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest),
(new _internal.strings_test.Strings_test_FieldsTest.FieldsTest(_internal.strings_test.Strings_test__faces._faces?.__copy__(), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[_internal.strings_test.Strings_test__faces._faces?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.strings_test.Strings_test_FieldsTest.FieldsTest)].concat([for (i in 15 ... (15 > 15 ? 15 : 15 : stdgo.GoInt).toBasic()) ({} : _internal.strings_test.Strings_test_FieldsTest.FieldsTest)])) : stdgo.Slice<_internal.strings_test.Strings_test_FieldsTest.FieldsTest>);
