package stdgo._internal.encoding.gob;
@:keep @:follow @:using(stdgo._internal.encoding.gob.Gob_t_testslice___localname___type3_7014_static_extension.T_testSlice___localname___Type3_7014_static_extension) typedef T_testSlice___localname___Type3_7014Pointer = stdgo.Pointer<stdgo._internal.encoding.gob.Gob_t_testslice___localname___type3_7014.T_testSlice___localname___Type3_7014>;
