package stdgo._internal.encoding.gob;
import stdgo._internal.flag.Flag;
import stdgo._internal.errors.Errors;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strings.Strings;
import stdgo._internal.time.Time;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.testing.Testing;
import stdgo._internal.io.Io;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.hex.Hex;
import stdgo._internal.sort.Sort;
import stdgo._internal.os.Os;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.encoding.binary.Binary;
var _decOpTable : stdgo.GoArray<stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp> = {
        var s:stdgo.GoArray<stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp> = new stdgo.GoArray<stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp>(25, 25, ...[for (i in 0 ... 25) (null : stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp)]);
        s[1] = stdgo._internal.encoding.gob.Gob__decBool._decBool;
        s[3] = stdgo._internal.encoding.gob.Gob__decInt8._decInt8;
        s[4] = stdgo._internal.encoding.gob.Gob__decInt16._decInt16;
        s[5] = stdgo._internal.encoding.gob.Gob__decInt32._decInt32;
        s[6] = stdgo._internal.encoding.gob.Gob__decInt64._decInt64;
        s[8] = stdgo._internal.encoding.gob.Gob__decUint8._decUint8;
        s[9] = stdgo._internal.encoding.gob.Gob__decUint16._decUint16;
        s[10] = stdgo._internal.encoding.gob.Gob__decUint32._decUint32;
        s[11] = stdgo._internal.encoding.gob.Gob__decUint64._decUint64;
        s[13] = stdgo._internal.encoding.gob.Gob__decFloat32._decFloat32;
        s[14] = stdgo._internal.encoding.gob.Gob__decFloat64._decFloat64;
        s[15] = stdgo._internal.encoding.gob.Gob__decComplex64._decComplex64;
        s[16] = stdgo._internal.encoding.gob.Gob__decComplex128._decComplex128;
        s[24] = stdgo._internal.encoding.gob.Gob__decString._decString;
        s;
    };
