package stdgo._internal.encoding.gob;
var _encSliceHelper : stdgo.GoMap<stdgo._internal.reflect.Reflect_Kind.Kind, stdgo._internal.encoding.gob.Gob_T_encHelper.T_encHelper> = ({
        final x = new stdgo.GoMap.GoIntMap<stdgo._internal.encoding.gob.Gob_T_encHelper.T_encHelper>();
        x.__defaultValue__ = () -> (null : stdgo._internal.encoding.gob.Gob_T_encHelper.T_encHelper);
        x.set((1u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encBoolSlice._encBoolSlice);
x.set((15u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encComplex64Slice._encComplex64Slice);
x.set((16u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encComplex128Slice._encComplex128Slice);
x.set((13u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encFloat32Slice._encFloat32Slice);
x.set((14u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encFloat64Slice._encFloat64Slice);
x.set((2u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encIntSlice._encIntSlice);
x.set((4u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encInt16Slice._encInt16Slice);
x.set((5u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encInt32Slice._encInt32Slice);
x.set((6u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encInt64Slice._encInt64Slice);
x.set((3u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encInt8Slice._encInt8Slice);
x.set((24u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encStringSlice._encStringSlice);
x.set((7u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encUintSlice._encUintSlice);
x.set((9u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encUint16Slice._encUint16Slice);
x.set((10u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encUint32Slice._encUint32Slice);
x.set((11u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encUint64Slice._encUint64Slice);
x.set((12u32 : stdgo._internal.reflect.Reflect_Kind.Kind), stdgo._internal.encoding.gob.Gob__encUintptrSlice._encUintptrSlice);
        x;
    } : stdgo.GoMap<stdgo._internal.reflect.Reflect_Kind.Kind, stdgo._internal.encoding.gob.Gob_T_encHelper.T_encHelper>);
