package stdgo._internal.encoding.gob;
@:named typedef T_testRecursiveMapType___localname___recursiveMap_7903 = stdgo.GoMap<stdgo.GoString, stdgo._internal.encoding.gob.Gob_T_testRecursiveMapType___localname___recursiveMap_7903.T_testRecursiveMapType___localname___recursiveMap_7903>;
