package stdgo._internal.encoding.gob;
import stdgo._internal.flag.Flag;
import stdgo._internal.errors.Errors;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strings.Strings;
import stdgo._internal.time.Time;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.testing.Testing;
import stdgo._internal.io.Io;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.hex.Hex;
import stdgo._internal.sort.Sort;
import stdgo._internal.os.Os;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.encoding.binary.Binary;
var _decIgnoreOpMap : stdgo.GoMap<stdgo._internal.encoding.gob.Gob_T_typeId.T_typeId, stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp> = ({
        final x = new stdgo.GoMap.GoIntMap<stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp>();
        x.__defaultValue__ = () -> (null : stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp);
        x.set(stdgo._internal.encoding.gob.Gob__tBool._tBool, stdgo._internal.encoding.gob.Gob__ignoreUint._ignoreUint);
x.set(stdgo._internal.encoding.gob.Gob__tInt._tInt, stdgo._internal.encoding.gob.Gob__ignoreUint._ignoreUint);
x.set(stdgo._internal.encoding.gob.Gob__tUint._tUint, stdgo._internal.encoding.gob.Gob__ignoreUint._ignoreUint);
x.set(stdgo._internal.encoding.gob.Gob__tFloat._tFloat, stdgo._internal.encoding.gob.Gob__ignoreUint._ignoreUint);
x.set(stdgo._internal.encoding.gob.Gob__tBytes._tBytes, stdgo._internal.encoding.gob.Gob__ignoreUint8Array._ignoreUint8Array);
x.set(stdgo._internal.encoding.gob.Gob__tString._tString, stdgo._internal.encoding.gob.Gob__ignoreUint8Array._ignoreUint8Array);
x.set(stdgo._internal.encoding.gob.Gob__tComplex._tComplex, stdgo._internal.encoding.gob.Gob__ignoreTwoUints._ignoreTwoUints);
        x;
    } : stdgo.GoMap<stdgo._internal.encoding.gob.Gob_T_typeId.T_typeId, stdgo._internal.encoding.gob.Gob_T_decOp.T_decOp>);
