package stdgo._internal.encoding.gob;
import stdgo._internal.flag.Flag;
import stdgo._internal.errors.Errors;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strings.Strings;
import stdgo._internal.time.Time;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.testing.Testing;
import stdgo._internal.io.Io;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.Math;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.encoding.hex.Hex;
import stdgo._internal.sort.Sort;
import stdgo._internal.os.Os;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.encoding.binary.Binary;
var _encOpTable : stdgo.GoArray<stdgo._internal.encoding.gob.Gob_T_encOp.T_encOp> = {
        var s:stdgo.GoArray<stdgo._internal.encoding.gob.Gob_T_encOp.T_encOp> = new stdgo.GoArray<stdgo._internal.encoding.gob.Gob_T_encOp.T_encOp>(25, 25, ...[for (i in 0 ... 25) (null : stdgo._internal.encoding.gob.Gob_T_encOp.T_encOp)]);
        s[1] = stdgo._internal.encoding.gob.Gob__encBool._encBool;
        s[2] = stdgo._internal.encoding.gob.Gob__encInt._encInt;
        s[3] = stdgo._internal.encoding.gob.Gob__encInt._encInt;
        s[4] = stdgo._internal.encoding.gob.Gob__encInt._encInt;
        s[5] = stdgo._internal.encoding.gob.Gob__encInt._encInt;
        s[6] = stdgo._internal.encoding.gob.Gob__encInt._encInt;
        s[7] = stdgo._internal.encoding.gob.Gob__encUint._encUint;
        s[8] = stdgo._internal.encoding.gob.Gob__encUint._encUint;
        s[9] = stdgo._internal.encoding.gob.Gob__encUint._encUint;
        s[10] = stdgo._internal.encoding.gob.Gob__encUint._encUint;
        s[11] = stdgo._internal.encoding.gob.Gob__encUint._encUint;
        s[12] = stdgo._internal.encoding.gob.Gob__encUint._encUint;
        s[13] = stdgo._internal.encoding.gob.Gob__encFloat._encFloat;
        s[14] = stdgo._internal.encoding.gob.Gob__encFloat._encFloat;
        s[15] = stdgo._internal.encoding.gob.Gob__encComplex._encComplex;
        s[16] = stdgo._internal.encoding.gob.Gob__encComplex._encComplex;
        s[24] = stdgo._internal.encoding.gob.Gob__encString._encString;
        s;
    };
