package stdgo._internal.encoding.gob;
@:keep @:follow @:using(stdgo._internal.encoding.gob.Gob_t_testendtoend___localname___t1_13836_static_extension.T_testEndToEnd___localname___T1_13836_static_extension) typedef T_testEndToEnd___localname___T1_13836Pointer = stdgo.Pointer<stdgo._internal.encoding.gob.Gob_t_testendtoend___localname___t1_13836.T_testEndToEnd___localname___T1_13836>;
