package stdgo._internal.encoding.gob;
@:keep @:follow @:using(stdgo._internal.encoding.gob.Gob_t_testregistration___localname___t_4300_static_extension.T_testRegistration___localname___T_4300_static_extension) typedef T_testRegistration___localname___T_4300Pointer = stdgo.Pointer<stdgo._internal.encoding.gob.Gob_t_testregistration___localname___t_4300.T_testRegistration___localname___T_4300>;
