package stdgo._internal.encoding.gob;
@:keep @:follow @:using(stdgo._internal.encoding.gob.Gob_t_testarray___localname___type6_7544_static_extension.T_testArray___localname___Type6_7544_static_extension) typedef T_testArray___localname___Type6_7544Pointer = stdgo.Pointer<stdgo._internal.encoding.gob.Gob_t_testarray___localname___type6_7544.T_testArray___localname___Type6_7544>;
