package stdgo.encoding.gob;
typedef T_testTypeToPtrType___localname___Type0_6215Pointer = stdgo._internal.encoding.gob.Gob_T_testTypeToPtrType___localname___Type0_6215Pointer.T_testTypeToPtrType___localname___Type0_6215Pointer;
