package stdgo.encoding.gob;
typedef T_testBadRecursiveType___localname___Rec_23209 = stdgo._internal.encoding.gob.Gob_T_testBadRecursiveType___localname___Rec_23209.T_testBadRecursiveType___localname___Rec_23209;
