package _internal.math_test;
import stdgo._internal.math.Math;
import stdgo._internal.math.Math;
import stdgo._internal.math.Math;
var _powSC : stdgo.Slice<stdgo.GoFloat64> = (new stdgo.Slice<stdgo.GoFloat64>(75, 75, ...[
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_naN.naN(),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_naN.naN(),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(-3.141592653589793 : stdgo.GoFloat64),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_naN.naN(),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)),
stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)),
(0 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
(0 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(3.141592653589793 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_naN.naN(),
(0 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_naN.naN(),
(1 : stdgo.GoFloat64),
(1 : stdgo.GoFloat64),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_naN.naN(),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
(0 : stdgo.GoFloat64),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
(0 : stdgo.GoFloat64),
stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)),
stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)),
stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.Slice<stdgo.GoFloat64>);
