package _internal.math_test;
import stdgo._internal.math.Math;
import stdgo._internal.math.Math;
import stdgo._internal.math.Math;
var _vffmodSC : stdgo.Slice<stdgo.GoArray<stdgo.GoFloat64>> = (new stdgo.Slice<stdgo.GoArray<stdgo.GoFloat64>>(34, 34, ...[
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)), (-3.141592653589793 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)), (3.141592653589793 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt)), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(-3.141592653589793 : stdgo.GoFloat64), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(-3.141592653589793 : stdgo.GoFloat64), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(-3.141592653589793 : stdgo.GoFloat64), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(-3.141592653589793 : stdgo.GoFloat64), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_copysign.copysign((0 : stdgo.GoFloat64), (-1 : stdgo.GoFloat64)), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(0 : stdgo.GoFloat64), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(0 : stdgo.GoFloat64), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(0 : stdgo.GoFloat64), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(0 : stdgo.GoFloat64), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(3.141592653589793 : stdgo.GoFloat64), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(3.141592653589793 : stdgo.GoFloat64), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(3.141592653589793 : stdgo.GoFloat64), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[(3.141592653589793 : stdgo.GoFloat64), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)), (-3.141592653589793 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)), (3.141592653589793 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt)), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_naN.naN(), stdgo._internal.math.Math_inf.inf((-1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_naN.naN(), (-3.141592653589793 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_naN.naN(), (0 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_naN.naN(), (3.141592653589793 : stdgo.GoFloat64)]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_naN.naN(), stdgo._internal.math.Math_inf.inf((1 : stdgo.GoInt))]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__(),
(new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[stdgo._internal.math.Math_naN.naN(), stdgo._internal.math.Math_naN.naN()]).__setNumber32__() : stdgo.GoArray<stdgo.GoFloat64>)?.__copy__()].concat([for (i in 34 ... (34 > 34 ? 34 : 34 : stdgo.GoInt).toBasic()) new stdgo.GoArray<stdgo.GoFloat64>(2, 2, ...[for (i in 0 ... 2) (0 : stdgo.GoFloat64)])])) : stdgo.Slice<stdgo.GoArray<stdgo.GoFloat64>>);
