package stdgo._internal.text.template;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.errors.Errors;
import stdgo._internal.flag.Flag;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.io.Io;
import stdgo._internal.testing.Testing;
import stdgo._internal.unicode.Unicode;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.net.url.Url;
import stdgo._internal.path.filepath.Filepath;
import stdgo._internal.io.fs.Fs;
import stdgo._internal.os.Os;
import stdgo._internal.path.Path;
import stdgo._internal.internal.fmtsort.Fmtsort;
@:keep @:follow @:using(stdgo._internal.text.template.Template_T__struct_3_static_extension.T__struct_3_static_extension) @:using(stdgo._internal.text.template.Template_T__struct_3Pointer_static_extension.T__struct_3Pointer_static_extension) typedef T__struct_3Pointer = stdgo.Pointer<stdgo._internal.text.template.Template_T__struct_3.T__struct_3>;
