package stdgo._internal.internal.profile;
import stdgo._internal.errors.Errors;
import stdgo._internal.internal.lazyregexp.Lazyregexp;
import stdgo._internal.strings.Strings;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.io.Io;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.math.Math;
import stdgo._internal.compress.gzip.Gzip;
import stdgo._internal.sort.Sort;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.time.Time;
import stdgo._internal.regexp.Regexp;
@:named @:using(stdgo._internal.internal.profile.Profile_Demangler_static_extension.Demangler_static_extension) typedef Demangler = stdgo.Slice<stdgo.GoString> -> { var _0 : stdgo.GoMap<stdgo.GoString, stdgo.GoString>; var _1 : stdgo.Error; };
