package stdgo._internal.internal.pkgbits;
import stdgo._internal.errors.Errors;
import stdgo._internal.strings.Strings;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.io.Io;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.go.constant.Constant;
import stdgo._internal.crypto.md5.Md5;
import stdgo._internal.strconv.Strconv;
@:keep @:follow @:using(stdgo._internal.internal.pkgbits.Pkgbits_Encoder_static_extension.Encoder_static_extension) typedef EncoderPointer = stdgo.Pointer<stdgo._internal.internal.pkgbits.Pkgbits_Encoder.Encoder>;
