package _internal.unicode.utf8_test;
import stdgo._internal.unicode.utf8.Utf8;
var _utf8map : stdgo.Slice<_internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map> = (new stdgo.Slice<_internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map>(32, 32, ...[
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((0 : stdgo.GoInt32), stdgo.Go.str(0)?.__copy__()) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((1 : stdgo.GoInt32), stdgo.Go.str(1)?.__copy__()) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((126 : stdgo.GoInt32), ("~" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((127 : stdgo.GoInt32), stdgo.Go.str(127)?.__copy__()) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((128 : stdgo.GoInt32), ("\u0080" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((129 : stdgo.GoInt32), ("\u0081" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((191 : stdgo.GoInt32), ("¿" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((192 : stdgo.GoInt32), ("À" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((193 : stdgo.GoInt32), ("Á" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((200 : stdgo.GoInt32), ("È" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((208 : stdgo.GoInt32), ("Ð" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((224 : stdgo.GoInt32), ("à" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((240 : stdgo.GoInt32), ("ð" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((248 : stdgo.GoInt32), ("ø" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((255 : stdgo.GoInt32), ("ÿ" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((256 : stdgo.GoInt32), ("Ā" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((2047 : stdgo.GoInt32), ("߿" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((1024 : stdgo.GoInt32), ("Ѐ" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((2048 : stdgo.GoInt32), ("ࠀ" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((2049 : stdgo.GoInt32), ("ࠁ" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((4096 : stdgo.GoInt32), ("က" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((53248 : stdgo.GoInt32), ("퀀" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((55295 : stdgo.GoInt32), ("\ud7ff" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((57344 : stdgo.GoInt32), ("\ue000" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((65534 : stdgo.GoInt32), ("\ufffe" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((65535 : stdgo.GoInt32), ("\uffff" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((65536 : stdgo.GoInt32), ("𐀀" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((65537 : stdgo.GoInt32), ("𐀁" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((262144 : stdgo.GoInt32), ("\u{00040000}" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((1114110 : stdgo.GoInt32), ("\u{0010fffe}" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((1114111 : stdgo.GoInt32), ("\u{0010ffff}" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map),
(new _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map((65533 : stdgo.GoInt32), ("�" : stdgo.GoString)) : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map)].concat([for (i in 32 ... (32 > 32 ? 32 : 32 : stdgo.GoInt).toBasic()) ({} : _internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map)])) : stdgo.Slice<_internal.unicode.utf8_test.Utf8_test_Utf8Map.Utf8Map>);
