package _internal.strconv_test;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
var sink : _internal.strconv_test.Strconv_test_T__struct_6.T__struct_6 = ({ bool_ : false, int_ : (0 : stdgo.GoInt), int64 : (0 : stdgo.GoInt64), uint64 : (0 : stdgo.GoUInt64), float64 : (0 : stdgo.GoFloat64), complex128 : new stdgo.GoComplex128(0, 0), error : (null : stdgo.Error), bytes : (null : stdgo.Slice<stdgo.GoUInt8>) } : _internal.strconv_test.Strconv_test_T__struct_6.T__struct_6);
