package _internal.strconv_test;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
var _roundTripCases : stdgo.Slice<_internal.strconv_test.Strconv_test_T__struct_0.T__struct_0> = (new stdgo.Slice<_internal.strconv_test.Strconv_test_T__struct_0.T__struct_0>(2, 2, ...[({ _f : (4.87402195346389e+27 : stdgo.GoFloat64), _s : ("4.87402195346389e+27" : stdgo.GoString) } : _internal.strconv_test.Strconv_test_T__struct_0.T__struct_0), ({ _f : (4.8740219534638903e+27 : stdgo.GoFloat64), _s : ("4.8740219534638903e+27" : stdgo.GoString) } : _internal.strconv_test.Strconv_test_T__struct_0.T__struct_0)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({ _f : (0 : stdgo.GoFloat64), _s : ("" : stdgo.GoString) } : _internal.strconv_test.Strconv_test_T__struct_0.T__struct_0)])) : stdgo.Slice<_internal.strconv_test.Strconv_test_T__struct_0.T__struct_0>);
