package _internal.strconv_test;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
var _parseBitSizeTests : stdgo.Slice<_internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest> = (new stdgo.Slice<_internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest>(4, 4, ...[(new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((-1 : stdgo.GoInt), _internal.strconv_test.Strconv_test__bitSizeErrStub._bitSizeErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((0 : stdgo.GoInt), _internal.strconv_test.Strconv_test__noErrStub._noErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((64 : stdgo.GoInt), _internal.strconv_test.Strconv_test__noErrStub._noErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((65 : stdgo.GoInt), _internal.strconv_test.Strconv_test__bitSizeErrStub._bitSizeErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest)])) : stdgo.Slice<_internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest>);
