package _internal.strconv_test;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
@:local @:using(_internal.strconv_test.Strconv_test_T__struct_6_static_extension.T__struct_6_static_extension) typedef T__struct_6 = {
    public var bool_ : Bool;
    public var int_ : stdgo.GoInt;
    public var int64 : stdgo.GoInt64;
    public var uint64 : stdgo.GoUInt64;
    public var float64 : stdgo.GoFloat64;
    public var complex128 : stdgo.GoComplex128;
    public var error : stdgo.Error;
    public var bytes : stdgo.Slice<stdgo.GoUInt8>;
};
