package _internal.strconv_test;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strconv.Strconv;
var _parseBaseTests : stdgo.Slice<_internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest> = (new stdgo.Slice<_internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest>(6, 6, ...[(new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((-1 : stdgo.GoInt), _internal.strconv_test.Strconv_test__baseErrStub._baseErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((0 : stdgo.GoInt), _internal.strconv_test.Strconv_test__noErrStub._noErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((1 : stdgo.GoInt), _internal.strconv_test.Strconv_test__baseErrStub._baseErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((2 : stdgo.GoInt), _internal.strconv_test.Strconv_test__noErrStub._noErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((36 : stdgo.GoInt), _internal.strconv_test.Strconv_test__noErrStub._noErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest), (new _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest((37 : stdgo.GoInt), _internal.strconv_test.Strconv_test__baseErrStub._baseErrStub) : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest)].concat([for (i in 6 ... (6 > 6 ? 6 : 6 : stdgo.GoInt).toBasic()) ({} : _internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest)])) : stdgo.Slice<_internal.strconv_test.Strconv_test_T_parseErrorTest.T_parseErrorTest>);
