package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
function testPallocDataFindScavengeCandidate(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
        {};
        var _tests = ({
            final x = new stdgo.GoMap.GoStringMap<_internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526>();
            x.__defaultValue__ = () -> ({} : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
            x.set(("MixedMin1" : stdgo.GoString), ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (40u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((42u32 : stdgo.GoUInt), (470u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (41u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((42u32 : stdgo.GoUInt), (470u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : (1 : stdgo.GoUIntptr), _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((41u32 : stdgo.GoUInt), (1u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526));
x.set(("MultiMin1" : stdgo.GoString), ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(3, 3, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (63u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((65u32 : stdgo.GoUInt), (20u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((87u32 : stdgo.GoUInt), (425u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((86u32 : stdgo.GoUInt), (1u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : (1 : stdgo.GoUIntptr), _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((85u32 : stdgo.GoUInt), (1u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526));
            x;
        } : stdgo.GoMap<stdgo.GoString, _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526>);
        {
            var _m = ((1 : stdgo.GoUIntptr) : stdgo.GoUIntptr);
            stdgo.Go.cfor((_m <= (64 : stdgo.GoUIntptr) : Bool), _m = (_m * ((2 : stdgo.GoUIntptr)) : stdgo.GoUIntptr), {
                var _suffix = (stdgo._internal.fmt.Fmt_sprintf.sprintf(("Min%d" : stdgo.GoString), stdgo.Go.toInterface(_m))?.__copy__() : stdgo.GoString);
                _tests[(("AllFree" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (512u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("AllScavenged" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (512u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (0u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("NoneFree" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (512u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((256u32 : stdgo.GoUInt), (256u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (0u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("StartFree" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((_m : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("EndFree" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("Straddle64" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((64u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((64u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((64u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : ((2 : stdgo.GoUIntptr) * _m : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((64u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), ((2u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("BottomEdge64WithFull" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((64u32 : stdgo.GoUInt), (64u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((128u32 : stdgo.GoUInt) + ((3u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((128u32 : stdgo.GoUInt) + ((3u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((1u32 : stdgo.GoUInt), (10u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : ((3 : stdgo.GoUIntptr) * _m : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((128u32 : stdgo.GoUInt), ((3u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("BottomEdge64WithPocket" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(3, 3, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((64u32 : stdgo.GoUInt), (62u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((127u32 : stdgo.GoUInt), (1u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((128u32 : stdgo.GoUInt) + ((3u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((128u32 : stdgo.GoUInt) + ((3u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((1u32 : stdgo.GoUInt), (10u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : ((3 : stdgo.GoUIntptr) * _m : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((128u32 : stdgo.GoUInt), ((3u32 : stdgo.GoUInt) * (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                _tests[(("Max0" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (0 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                if ((_m <= (8 : stdgo.GoUIntptr) : Bool)) {
                    _tests[("OneFree" : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (40u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((40u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((40u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((40u32 : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                    _tests[("OneScavenged" : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (40u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((40u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((40u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((40u32 : stdgo.GoUInt), (1u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (512 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (0u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                };
                if ((_m > (1 : stdgo.GoUIntptr) : Bool)) {
                    _tests[(("MaxUnaligned" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((_m * (2 : stdgo.GoUIntptr) : stdgo.GoUIntptr) - (1 : stdgo.GoUIntptr) : stdgo.GoUIntptr) : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (_m - (2 : stdgo.GoUIntptr) : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                    _tests[(("SkipSmall" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(4, 4, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((64u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((64u32 : stdgo.GoUInt), (5u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((70u32 : stdgo.GoUInt), (11u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((82u32 : stdgo.GoUInt), (430u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : _m, _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((64u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                    _tests[(("SkipMisaligned" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(3, 3, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((64u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((64u32 : stdgo.GoUInt), (63u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((127u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (((127u32 : stdgo.GoUInt) + (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : _m, _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((64u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                    _tests[(("MaxLessThan" : stdgo.GoString) + _suffix?.__copy__() : stdgo.GoString)] = ({ _scavenged : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : _m, _max : (1 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((512u32 : stdgo.GoUInt) - (_m : stdgo.GoUInt) : stdgo.GoUInt), (_m : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                };
            });
        };
        if ((stdgo._internal.runtime.Runtime_physHugePageSize.physHugePageSize > (8192 : stdgo.GoUIntptr) : Bool)) {
            var _bits = ((stdgo._internal.runtime.Runtime_physHugePageSize.physHugePageSize / (8192 : stdgo.GoUIntptr) : stdgo.GoUIntptr) : stdgo.GoUInt);
            if ((_bits < (512u32 : stdgo.GoUInt) : Bool)) {
                _tests[("PreserveHugePageBottom" : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((_bits + (2u32 : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - ((_bits + (2u32 : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : (1 : stdgo.GoUIntptr), _max : (3 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (_bits + (2u32 : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                if ((((3u32 : stdgo.GoUInt) * _bits : stdgo.GoUInt) < (512u32 : stdgo.GoUInt) : Bool)) {
                    _tests[("PreserveHugePageMiddle" : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(2, 2, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (_bits - (10u32 : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange), (new stdgo._internal.runtime.Runtime_BitRange.BitRange((((2u32 : stdgo.GoUInt) * _bits : stdgo.GoUInt) + (10u32 : stdgo.GoUInt) : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - ((((2u32 : stdgo.GoUInt) * _bits : stdgo.GoUInt) + (10u32 : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : (1 : stdgo.GoUIntptr), _max : (12 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(_bits, (_bits + (10u32 : stdgo.GoUInt) : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
                };
                _tests[("PreserveHugePageTop" : stdgo.GoString)] = ({ _alloc : (new stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>(1, 1, ...[(new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), ((512u32 : stdgo.GoUInt) - _bits : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange)].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_BitRange.BitRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>), _min : (1 : stdgo.GoUIntptr), _max : (1 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange(((512u32 : stdgo.GoUInt) - _bits : stdgo.GoUInt), _bits) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
            } else if (_bits == ((512u32 : stdgo.GoUInt))) {
                _tests[("PreserveHugePageAll" : stdgo.GoString)] = ({ _min : (1 : stdgo.GoUIntptr), _max : (1 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((0u32 : stdgo.GoUInt), (512u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
            } else {
                _tests[("PreserveHugePageNone" : stdgo.GoString)] = ({ _min : (1 : stdgo.GoUIntptr), _max : (1 : stdgo.GoUIntptr), _want : (new stdgo._internal.runtime.Runtime_BitRange.BitRange((511u32 : stdgo.GoUInt), (1u32 : stdgo.GoUInt)) : stdgo._internal.runtime.Runtime_BitRange.BitRange) } : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
            };
        };
        for (_name => _v in _tests) {
            var _v = (_v?.__copy__() : _internal.runtime_test.Runtime_test_T_testPallocDataFindScavengeCandidate___localname___test_2526.T_testPallocDataFindScavengeCandidate___localname___test_2526);
            _t.run(_name?.__copy__(), function(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
                var _b = _internal.runtime_test.Runtime_test__makePallocData._makePallocData(_v._alloc, _v._scavenged);
                var __tmp__ = _b.findScavengeCandidate((511u32 : stdgo.GoUInt), _v._min, _v._max), _start:stdgo.GoUInt = __tmp__._0, _size:stdgo.GoUInt = __tmp__._1;
                var _got = (new stdgo._internal.runtime.Runtime_BitRange.BitRange(_start, _size) : stdgo._internal.runtime.Runtime_BitRange.BitRange);
                if ((!(((_got.n == (0u32 : stdgo.GoUInt)) && (_v._want.n == (0u32 : stdgo.GoUInt)) : Bool)) && (stdgo.Go.toInterface(_got) != stdgo.Go.toInterface(_v._want)) : Bool)) {
                    _t.fatalf(("candidate mismatch: got %v, want %v" : stdgo.GoString), stdgo.Go.toInterface(_got), stdgo.Go.toInterface(_v._want));
                };
            });
        };
    }
