package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
@:local @:using(_internal.runtime_test.Runtime_test_T__struct_19_static_extension.T__struct_19_static_extension) typedef T__struct_19 = {
    public var _gcAssist : stdgo.GoFloat64;
    public var _gcDedicated : stdgo.GoFloat64;
    public var _gcIdle : stdgo.GoFloat64;
    public var _gcPause : stdgo.GoFloat64;
    public var _gcTotal : stdgo.GoFloat64;
    public var _idle : stdgo.GoFloat64;
    public var _user : stdgo.GoFloat64;
    public var _scavengeAssist : stdgo.GoFloat64;
    public var _scavengeBg : stdgo.GoFloat64;
    public var _scavengeTotal : stdgo.GoFloat64;
    public var _total : stdgo.GoFloat64;
};
