package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
function benchmarkMapDelete(_b:stdgo.Ref<stdgo._internal.testing.Testing_B.B>):Void {
        _b.run(("Int32" : stdgo.GoString), _internal.runtime_test.Runtime_test__runWith._runWith(_internal.runtime_test.Runtime_test__benchmarkMapDeleteInt32._benchmarkMapDeleteInt32, (100 : stdgo.GoInt), (1000 : stdgo.GoInt), (10000 : stdgo.GoInt)));
        _b.run(("Int64" : stdgo.GoString), _internal.runtime_test.Runtime_test__runWith._runWith(_internal.runtime_test.Runtime_test__benchmarkMapDeleteInt64._benchmarkMapDeleteInt64, (100 : stdgo.GoInt), (1000 : stdgo.GoInt), (10000 : stdgo.GoInt)));
        _b.run(("Str" : stdgo.GoString), _internal.runtime_test.Runtime_test__runWith._runWith(_internal.runtime_test.Runtime_test__benchmarkMapDeleteStr._benchmarkMapDeleteStr, (100 : stdgo.GoInt), (1000 : stdgo.GoInt), (10000 : stdgo.GoInt)));
        _b.run(("Pointer" : stdgo.GoString), _internal.runtime_test.Runtime_test__runWith._runWith(_internal.runtime_test.Runtime_test__benchmarkMapDeletePointer._benchmarkMapDeletePointer, (100 : stdgo.GoInt), (1000 : stdgo.GoInt), (10000 : stdgo.GoInt)));
    }
