package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
@:local @:using(_internal.runtime_test.Runtime_test_T__struct_26_static_extension.T__struct_26_static_extension) typedef T__struct_26 = {
    public var _before : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>;
    public var _after : stdgo.Slice<stdgo._internal.runtime.Runtime_BitRange.BitRange>;
    public var _npages : stdgo.GoUIntptr;
    public var _hits : stdgo.Slice<stdgo.GoUInt>;
};
