package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
@:keep class Key_static_extension {
    static public function _name(t:_internal.runtime_test.Runtime_test_Key.Key):stdgo.GoString return t._name();
    static public function _hash(t:_internal.runtime_test.Runtime_test_Key.Key):stdgo.GoUIntptr return t._hash();
    static public function _flipBit(t:_internal.runtime_test.Runtime_test_Key.Key, _i:stdgo.GoInt):Void t._flipBit(_i);
    static public function _bits(t:_internal.runtime_test.Runtime_test_Key.Key):stdgo.GoInt return t._bits();
    static public function _random(t:_internal.runtime_test.Runtime_test_Key.Key, _r:stdgo.Ref<stdgo._internal.math.rand.Rand_Rand.Rand>):Void t._random(_r);
    static public function _clear(t:_internal.runtime_test.Runtime_test_Key.Key):Void t._clear();
}
