package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
function testDeferWithRepeatedRepanics(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
        _internal.runtime_test.Runtime_test__interpreter._interpreter((0 : stdgo.GoInt), (6 : stdgo.GoInt), (2 : stdgo.GoInt));
        _internal.runtime_test.Runtime_test__recurseFnPanicRec._recurseFnPanicRec((0 : stdgo.GoInt), (10 : stdgo.GoInt));
        _internal.runtime_test.Runtime_test__interpreter._interpreter((0 : stdgo.GoInt), (5 : stdgo.GoInt), (1 : stdgo.GoInt));
        _internal.runtime_test.Runtime_test__recurseFnPanicRec._recurseFnPanicRec((0 : stdgo.GoInt), (10 : stdgo.GoInt));
        _internal.runtime_test.Runtime_test__interpreter._interpreter((0 : stdgo.GoInt), (6 : stdgo.GoInt), (3 : stdgo.GoInt));
        _internal.runtime_test.Runtime_test__recurseFnPanicRec._recurseFnPanicRec((0 : stdgo.GoInt), (10 : stdgo.GoInt));
    }
