package _internal.runtime_test;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.unsafe.Unsafe;
function testAddrRangesFindSucc(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
        var _large:stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange> = (null : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>);
        {
            var _i = (0 : stdgo.GoInt);
            stdgo.Go.cfor((_i < (100 : stdgo.GoInt) : Bool), _i++, {
                _large = (_large.__append__(stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange(((5 : stdgo.GoUIntptr) + ((_i : stdgo.GoUIntptr) * (5 : stdgo.GoUIntptr) : stdgo.GoUIntptr) : stdgo.GoUIntptr), (((5 : stdgo.GoUIntptr) + ((_i : stdgo.GoUIntptr) * (5 : stdgo.GoUIntptr) : stdgo.GoUIntptr) : stdgo.GoUIntptr) + (3 : stdgo.GoUIntptr) : stdgo.GoUIntptr))?.__copy__()));
            });
        };
        {};
        var _tests = (new stdgo.Slice<_internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330>(18, 18, ...[
({ _name : ("Empty" : stdgo.GoString), _base : (12 : stdgo.GoUIntptr), _expect : (0 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("OneBefore" : stdgo.GoString), _base : (12 : stdgo.GoUIntptr), _expect : (0 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(1, 1, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((14 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("OneWithin" : stdgo.GoString), _base : (14 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(1, 1, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((14 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("OneAfterLimit" : stdgo.GoString), _base : (16 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(1, 1, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((14 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("OneAfter" : stdgo.GoString), _base : (17 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(1, 1, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((14 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("ThreeBefore" : stdgo.GoString), _base : (3 : stdgo.GoUIntptr), _expect : (0 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(3, 3, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((6 : stdgo.GoUIntptr), (10 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((12 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((19 : stdgo.GoUIntptr), (22 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("ThreeAfter" : stdgo.GoString), _base : (24 : stdgo.GoUIntptr), _expect : (3 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(3, 3, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((6 : stdgo.GoUIntptr), (10 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((12 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((19 : stdgo.GoUIntptr), (22 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("ThreeBetween" : stdgo.GoString), _base : (11 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(3, 3, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((6 : stdgo.GoUIntptr), (10 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((12 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((19 : stdgo.GoUIntptr), (22 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("ThreeWithin" : stdgo.GoString), _base : (9 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(3, 3, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((6 : stdgo.GoUIntptr), (10 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((12 : stdgo.GoUIntptr), (16 : stdgo.GoUIntptr))?.__copy__(), stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((19 : stdgo.GoUIntptr), (22 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("Zero" : stdgo.GoString), _base : (0 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(1, 1, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((0 : stdgo.GoUIntptr), (10 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("Max" : stdgo.GoString), _base : (4294967295 : stdgo.GoUIntptr), _expect : (1 : stdgo.GoInt), _ranges : (new stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>(1, 1, ...[stdgo._internal.runtime.Runtime_makeAddrRange.makeAddrRange((4294967290 : stdgo.GoUIntptr), (4294967295 : stdgo.GoUIntptr))?.__copy__()].concat([for (i in 1 ... (1 > 1 ? 1 : 1 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.runtime.Runtime_AddrRange.AddrRange)])) : stdgo.Slice<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>) } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeBefore" : stdgo.GoString), _base : (2 : stdgo.GoUIntptr), _expect : (0 : stdgo.GoInt), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeAfter" : stdgo.GoString), _base : (((5 : stdgo.GoUIntptr) + ((_large.length : stdgo.GoUIntptr) * (5 : stdgo.GoUIntptr) : stdgo.GoUIntptr) : stdgo.GoUIntptr) + (30 : stdgo.GoUIntptr) : stdgo.GoUIntptr), _expect : (_large.length), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeBetweenLow" : stdgo.GoString), _base : (14 : stdgo.GoUIntptr), _expect : (2 : stdgo.GoInt), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeBetweenHigh" : stdgo.GoString), _base : (249 : stdgo.GoUIntptr), _expect : (49 : stdgo.GoInt), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeWithinLow" : stdgo.GoString), _base : (25 : stdgo.GoUIntptr), _expect : (5 : stdgo.GoInt), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeWithinHigh" : stdgo.GoString), _base : (396 : stdgo.GoUIntptr), _expect : (79 : stdgo.GoInt), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330),
({ _name : ("LargeWithinMiddle" : stdgo.GoString), _base : (250 : stdgo.GoUIntptr), _expect : (50 : stdgo.GoInt), _ranges : _large } : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330)].concat([for (i in 18 ... (18 > 18 ? 18 : 18 : stdgo.GoInt).toBasic()) ({} : _internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330)])) : stdgo.Slice<_internal.runtime_test.Runtime_test_T_testAddrRangesFindSucc___localname___testt_3330.T_testAddrRangesFindSucc___localname___testt_3330>);
        for (__6 => _test in _tests) {
            _t.run(_test._name?.__copy__(), function(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
                var _a = (stdgo._internal.runtime.Runtime_makeAddrRanges.makeAddrRanges(...(_test._ranges : Array<stdgo._internal.runtime.Runtime_AddrRange.AddrRange>))?.__copy__() : stdgo._internal.runtime.Runtime_AddrRanges.AddrRanges);
                var _i = (_a.findSucc(_test._base) : stdgo.GoInt);
                if (_i != (_test._expect)) {
                    _t.fatalf(("expected %d, got %d" : stdgo.GoString), stdgo.Go.toInterface(_test._expect), stdgo.Go.toInterface(_i));
                };
            });
        };
    }
