package stdgo.bytes_test;
import stdgo.bytes.Bytes;
/**
    
    
    
**/
var _tests : stdgo.Slice<stdgo.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo.testing.Testing.InternalTest>(
87,
87,
(new stdgo.testing.Testing.InternalTest(("TestNewBuffer" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testNewBuffer) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestNewBufferString" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testNewBufferString) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestBasicOperations" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testBasicOperations) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLargeStringWrites" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLargeStringWrites) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLargeByteWrites" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLargeByteWrites) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLargeStringReads" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLargeStringReads) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLargeByteReads" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLargeByteReads) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestMixedReadsAndWrites" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testMixedReadsAndWrites) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCapWithPreallocatedSlice" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCapWithPreallocatedSlice) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCapWithSliceAndWrittenData" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCapWithSliceAndWrittenData) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestNil" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testNil) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadFrom" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadFrom) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadFromPanicReader" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadFromPanicReader) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadFromNegativeReader" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadFromNegativeReader) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestWriteTo" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testWriteTo) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestWriteAppend" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testWriteAppend) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestRuneIO" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testRuneIO) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestWriteInvalidRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testWriteInvalidRune) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestNext" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testNext) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadBytes" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadBytes) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadString" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadString) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestGrow" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testGrow) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestGrowOverflow" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testGrowOverflow) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadEmptyAtEOF" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadEmptyAtEOF) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestUnreadByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testUnreadByte) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestBufferGrowth" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testBufferGrowth) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestEqual" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testEqual) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestEqualExhaustive" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testEqualExhaustive) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestNotEqual" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testNotEqual) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndex" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndex) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLastIndex" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLastIndex) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndexAny" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndexAny) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLastIndexAny" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLastIndexAny) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndexByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndexByte) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestLastIndexByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testLastIndexByte) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndexByteBig" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndexByteBig) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndexByteSmall" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndexByteSmall) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndexRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndexRune) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCountByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCountByte) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCountByteNoMatch" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCountByteNoMatch) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestSplit" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testSplit) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestSplitAfter" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testSplitAfter) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestFields" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testFields) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestFieldsFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testFieldsFunc) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestMap" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testMap) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestToUpper" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testToUpper) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestToLower" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testToLower) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestToValidUTF8" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testToValidUTF8) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestTrimSpace" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testTrimSpace) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestRepeat" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testRepeat) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestRepeatCatchesOverflow" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testRepeatCatchesOverflow) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestRunes" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testRunes) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestTrim" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testTrim) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestTrimFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testTrimFunc) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestIndexFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testIndexFunc) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReplace" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReplace) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestTitle" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testTitle) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestToTitle" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testToTitle) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestEqualFold" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testEqualFold) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCut" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCut) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCutPrefix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCutPrefix) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCutSuffix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCutSuffix) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestBufferGrowNegative" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testBufferGrowNegative) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestBufferTruncateNegative" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testBufferTruncateNegative) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestBufferTruncateOutOfRange" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testBufferTruncateOutOfRange) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestContains" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testContains) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestContainsAny" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testContainsAny) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestContainsRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testContainsRune) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestContainsFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testContainsFunc) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestClone" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testClone) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCompare" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCompare) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCompareIdenticalSlice" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCompareIdenticalSlice) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestCompareBytes" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testCompareBytes) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestEndianBaseCompare" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testEndianBaseCompare) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReader" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReader) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReadAfterBigSeek" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReadAfterBigSeek) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderAt" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderAt) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderAtConcurrent" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderAtConcurrent) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestEmptyReaderConcurrent" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testEmptyReaderConcurrent) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderWriteTo" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderWriteTo) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderLen" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderLen) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestUnreadRuneError" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testUnreadRuneError) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderDoubleUnreadRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderDoubleUnreadRune) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderCopyNothing" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderCopyNothing) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderLenSize" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderLenSize) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderReset" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderReset) : stdgo.testing.Testing.InternalTest),
(new stdgo.testing.Testing.InternalTest(("TestReaderZero" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.testReaderZero) : stdgo.testing.Testing.InternalTest)) : stdgo.Slice<stdgo.testing.Testing.InternalTest>);
/**
    
    
    
**/
var _benchmarks : stdgo.Slice<stdgo.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo.testing.Testing.InternalBenchmark>(
59,
59,
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkReadString" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkReadString) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkWriteByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkWriteByte) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkWriteRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkWriteRune) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkBufferNotEmptyWriteRead" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkBufferNotEmptyWriteRead) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkBufferFullSmallReads" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkBufferFullSmallReads) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkBufferWriteBlock" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkBufferWriteBlock) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkBufferAppendNoCopy" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkBufferAppendNoCopy) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexByte) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexBytePortable" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexBytePortable) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexRune) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexRuneASCII" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexRuneASCII) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkEqual" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkEqual) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkEqualBothUnaligned" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkEqualBothUnaligned) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndex" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndex) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexEasy" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexEasy) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCount" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCount) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCountEasy" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCountEasy) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCountSingle" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCountSingle) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkToUpper" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkToUpper) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkToLower" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkToLower) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkFields" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkFields) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkFieldsFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkFieldsFunc) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkTrimSpace" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkTrimSpace) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkToValidUTF8" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkToValidUTF8) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexHard1" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexHard1) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexHard2" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexHard2) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexHard3" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexHard3) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexHard4" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexHard4) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkLastIndexHard1" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkLastIndexHard1) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkLastIndexHard2" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkLastIndexHard2) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkLastIndexHard3" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkLastIndexHard3) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCountHard1" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCountHard1) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCountHard2" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCountHard2) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCountHard3" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCountHard3) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkSplitEmptySeparator" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkSplitEmptySeparator) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkSplitSingleByteSeparator" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkSplitSingleByteSeparator) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkSplitMultiByteSeparator" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkSplitMultiByteSeparator) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkSplitNSingleByteSeparator" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkSplitNSingleByteSeparator) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkSplitNMultiByteSeparator" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkSplitNMultiByteSeparator) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkRepeat" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkRepeat) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkRepeatLarge" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkRepeatLarge) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkBytesCompare" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkBytesCompare) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexAnyASCII" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexAnyASCII) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexAnyUTF8" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexAnyUTF8) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkLastIndexAnyASCII" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkLastIndexAnyASCII) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkLastIndexAnyUTF8" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkLastIndexAnyUTF8) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkTrimASCII" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkTrimASCII) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkTrimByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkTrimByte) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkIndexPeriodic" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkIndexPeriodic) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesEqual" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesEqual) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesToNil" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesToNil) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesEmpty" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesEmpty) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesIdentical" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesIdentical) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesSameLength" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesSameLength) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesDifferentLength" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesDifferentLength) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesBigUnaligned" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesBigUnaligned) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesBigBothUnaligned" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesBigBothUnaligned) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesBig" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesBig) : stdgo.testing.Testing.InternalBenchmark),
(new stdgo.testing.Testing.InternalBenchmark(("BenchmarkCompareBytesBigIdentical" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.benchmarkCompareBytesBigIdentical) : stdgo.testing.Testing.InternalBenchmark)) : stdgo.Slice<stdgo.testing.Testing.InternalBenchmark>);
/**
    
    
    
**/
var _fuzzTargets : stdgo.Slice<stdgo.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo.testing.Testing.InternalFuzzTarget>(0, 0) : stdgo.Slice<stdgo.testing.Testing.InternalFuzzTarget>);
/**
    
    
    
**/
var _examples : stdgo.Slice<stdgo.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo.testing.Testing.InternalExample>(
59,
59,
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer, ("Hello world!\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_reader" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_reader, ("Gophers rule!\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_Bytes" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_Bytes, ("hello world\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_AvailableBuffer" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_AvailableBuffer, ("0 1 2 3\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_Cap" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_Cap, ("10\n10\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_Grow" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_Grow, ("\"64 bytes or fewer\"\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_Len" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_Len, ("5\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleBuffer_Next" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleBuffer_Next, ("ab\ncd\ne\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleClone" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleClone, ("abc\nabc\ndbc\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleContains" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleContains, ("true\nfalse\ntrue\ntrue\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleContainsAny" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleContainsAny, ("true\ntrue\nfalse\nfalse\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleContainsRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleContainsRune, ("true\nfalse\ntrue\ntrue\nfalse\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleCount" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleCount, ("3\n5\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleCut" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleCut, ("Cut(\"Gopher\", \"Go\") = \"\", \"pher\", true\nCut(\"Gopher\", \"ph\") = \"Go\", \"er\", true\nCut(\"Gopher\", \"er\") = \"Goph\", \"\", true\nCut(\"Gopher\", \"Badger\") = \"Gopher\", \"\", false\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleCutPrefix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleCutPrefix, ("CutPrefix(\"Gopher\", \"Go\") = \"pher\", true\nCutPrefix(\"Gopher\", \"ph\") = \"Gopher\", false\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleCutSuffix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleCutSuffix, ("CutSuffix(\"Gopher\", \"Go\") = \"Gopher\", false\nCutSuffix(\"Gopher\", \"er\") = \"Goph\", true\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleEqual" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleEqual, ("true\nfalse\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleEqualFold" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleEqualFold, ("true\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleFields" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleFields, ("Fields are: [\"foo\" \"bar\" \"baz\"]\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleFieldsFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleFieldsFunc, ("Fields are: [\"foo1\" \"bar2\" \"baz3\"]\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleHasPrefix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleHasPrefix, ("true\nfalse\ntrue\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleHasSuffix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleHasSuffix, ("true\nfalse\nfalse\ntrue\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleIndex" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleIndex, ("4\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleIndexByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleIndexByte, ("4\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleIndexFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleIndexFunc, ("7\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleIndexAny" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleIndexAny, ("2\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleIndexRune" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleIndexRune, ("4\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleJoin" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleJoin, ("foo, bar, baz\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleLastIndex" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleLastIndex, ("0\n3\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleLastIndexAny" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleLastIndexAny, ("5\n3\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleLastIndexByte" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleLastIndexByte, ("3\n8\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleLastIndexFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleLastIndexFunc, ("8\n9\n-1\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleMap" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleMap, ("\'Gjnf oevyyvt naq gur fyvgul tbcure...\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleReader_Len" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleReader_Len, ("3\n16\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleRepeat" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleRepeat, ("banana\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleReplace" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleReplace, ("oinky oinky oink\nmoo moo moo\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleReplaceAll" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleReplaceAll, ("moo moo moo\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleRunes" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleRunes, ("U+0067 \'g\'\nU+006F \'o\'\nU+0020 \' \'\nU+0067 \'g\'\nU+006F \'o\'\nU+0070 \'p\'\nU+0068 \'h\'\nU+0065 \'e\'\nU+0072 \'r\'\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleSplit" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleSplit, ("[\"a\" \"b\" \"c\"]\n[\"\" \"man \" \"plan \" \"canal panama\"]\n[\" \" \"x\" \"y\" \"z\" \" \"]\n[\"\"]\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleSplitN" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleSplitN, ("[\"a\" \"b,c\"]\n[] (nil = true)\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleSplitAfter" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleSplitAfter, ("[\"a,\" \"b,\" \"c\"]\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleSplitAfterN" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleSplitAfterN, ("[\"a,\" \"b,c\"]\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTitle" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTitle, ("Her Royal Highness\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToTitle" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToTitle, ("LOUD NOISES\nХЛЕБ\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToTitleSpecial" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToTitleSpecial, ("Original : ahoj vývojári golang\nToTitle : AHOJ VÝVOJÁRİ GOLANG\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToValidUTF8" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToValidUTF8, ("abc\nabc\nabc\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrim" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrim, ("[\"Achtung! Achtung\"]\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimFunc, ("-gopher!\n\"go-gopher!\"\ngo-gopher\ngo-gopher!\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimLeft" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimLeft, ("gopher8257\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimLeftFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimLeftFunc, ("-gopher\ngo-gopher!\ngo-gopher!567\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimPrefix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimPrefix, ("Hello, world!\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimSpace" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimSpace, ("a lone gopher\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimSuffix" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimSuffix, ("Hello, world!\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimRight" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimRight, ("453gopher\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleTrimRightFunc" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleTrimRightFunc, ("go-\ngo-gopher\n1234go-gopher!\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToLower" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToLower, ("gopher\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToLowerSpecial" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToLowerSpecial, ("Original : AHOJ VÝVOJÁRİ GOLANG\nToLower : ahoj vývojári golang\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToUpper" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToUpper, ("GOPHER\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample),
(new stdgo.testing.Testing.InternalExample(("ExampleToUpperSpecial" : stdgo.GoString)?.__copy__(), stdgo.bytes_test.Bytes_test.exampleToUpperSpecial, ("Original : ahoj vývojári golang\nToUpper : AHOJ VÝVOJÁRİ GOLANG\n" : stdgo.GoString)?.__copy__(), false) : stdgo.testing.Testing.InternalExample)) : stdgo.Slice<stdgo.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        Sys.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo.testing.internal.testdeps.Testdeps.importPath = ("bytes" : stdgo.GoString)?.__copy__();
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
