package stdgo.go.types_test;
import stdgo._internal.go.types.Types;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>(
131,
131,
(new stdgo._internal.testing.Testing.InternalTest(("TestContextHashCollisions" : stdgo.GoString), stdgo._internal.go.types.Types.testContextHashCollisions) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestError" : stdgo.GoString), stdgo._internal.go.types.Types.testError) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStripAnnotations" : stdgo.GoString), stdgo._internal.go.types.Types.testStripAnnotations) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSizeof" : stdgo.GoString), stdgo._internal.go.types.Types.testSizeof) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistAll" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistAll) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistString" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistString) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistIsEmpty" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistIsEmpty) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistIsAll" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistIsAll) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistNorm" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistNorm) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistUnion" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistUnion) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistIntersect" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistIntersect) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistEqual" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistEqual) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistIncludes" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistIncludes) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistSupersetOf" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistSupersetOf) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermlistSubsetOf" : stdgo.GoString), stdgo._internal.go.types.Types.testTermlistSubsetOf) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestZeroTok" : stdgo.GoString), stdgo._internal.go.types.Types.testZeroTok) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAssignOp" : stdgo.GoString), stdgo._internal.go.types.Types.testAssignOp) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInvalidTypeSet" : stdgo.GoString), stdgo._internal.go.types.Types.testInvalidTypeSet) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTypeSetString" : stdgo.GoString), stdgo._internal.go.types.Types.testTypeSetString) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermString" : stdgo.GoString), stdgo._internal.go.types.Types.testTermString) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermEqual" : stdgo.GoString), stdgo._internal.go.types.Types.testTermEqual) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermUnion" : stdgo.GoString), stdgo._internal.go.types.Types.testTermUnion) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermIntersection" : stdgo.GoString), stdgo._internal.go.types.Types.testTermIntersection) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermIncludes" : stdgo.GoString), stdgo._internal.go.types.Types.testTermIncludes) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermSubsetOf" : stdgo.GoString), stdgo._internal.go.types.Types.testTermSubsetOf) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTermDisjoint" : stdgo.GoString), stdgo._internal.go.types.Types.testTermDisjoint) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestParseGoVersion" : stdgo.GoString), stdgo._internal.go.types.Types.testParseGoVersion) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestValuesInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testValuesInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTypesInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testTypesInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstanceInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstanceInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDefsInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testDefsInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestUsesInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testUsesInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestGenericMethodInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testGenericMethodInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestImplicitsInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testImplicitsInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestPredicatesInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testPredicatesInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestScopesInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testScopesInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInitOrderInfo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInitOrderInfo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMultiFileInitOrder" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testMultiFileInitOrder) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFiles" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testFiles) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSelection" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testSelection) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue8518" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue8518) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue59603" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue59603) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLookupFieldOrMethodOnNil" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testLookupFieldOrMethodOnNil) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLookupFieldOrMethod" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testLookupFieldOrMethod) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLookupFieldOrMethod_RecursiveGeneric" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testLookupFieldOrMethod_RecursiveGeneric) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestScopeLookupParent" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testScopeLookupParent) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestConvertibleTo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testConvertibleTo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAssignableTo" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testAssignableTo) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIdentical" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIdentical) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIdentical_issue15173" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIdentical_issue15173) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIdenticalUnions" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIdenticalUnions) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue61737" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue61737) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue15305" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue15305) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCompositeLitTypes" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testCompositeLitTypes) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestObjectParents" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testObjectParents) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFailedImport" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testFailedImport) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstantiate" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstantiate) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstantiateErrors" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstantiateErrors) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestArgumentErrorUnwrapping" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testArgumentErrorUnwrapping) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstanceIdentity" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstanceIdentity) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstantiatedObjects" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstantiatedObjects) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestImplements" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testImplements) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMissingMethodAlternative" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testMissingMethodAlternative) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestErrorURL" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testErrorURL) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestBuiltinSignatures" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testBuiltinSignatures) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestManual" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testManual) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLongConstants" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testLongConstants) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIndexRepresentability" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIndexRepresentability) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue47243_TypedRHS" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue47243_TypedRHS) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCheck" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testCheck) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSpec" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testSpec) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestExamples" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testExamples) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFixedbugs" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testFixedbugs) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestLocal" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testLocal) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCommentMap" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testCommentMap) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestErrorCalls" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testErrorCalls) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEvalBasic" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testEvalBasic) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEvalComposite" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testEvalComposite) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEvalArith" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testEvalArith) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEvalPos" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testEvalPos) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestCheckExpr" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testCheckExpr) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestExprString" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testExprString) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestGenerate" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testGenerate) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestHilbert" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testHilbert) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstantiateEquality" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstantiateEquality) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestInstantiateNonEquality" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testInstantiateNonEquality) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMethodInstantiation" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testMethodInstantiation) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestImmutableSignatures" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testImmutableSignatures) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue5770" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue5770) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue5849" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue5849) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue6413" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue6413) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue7245" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue7245) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue7827" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue7827) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue13898" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue13898) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue22525" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue22525) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue25627" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue25627) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue28005" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue28005) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue28282" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue28282) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue29029" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue29029) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue34151" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue34151) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue34921" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue34921) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue43088" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue43088) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue44515" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue44515) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue43124" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue43124) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue50646" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue50646) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue55030" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue55030) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue51093" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue51093) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue54258" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue54258) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue59944" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue59944) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue61931" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue61931) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestNewMethodSet" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testNewMethodSet) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestNewMethodSet_RecursiveGeneric" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testNewMethodSet_RecursiveGeneric) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue60634" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue60634) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMonoGood" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testMonoGood) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMonoBad" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testMonoBad) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestFiniteTypeExpansion" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testFiniteTypeExpansion) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIsAlias" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIsAlias) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEmbeddedMethod" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testEmbeddedMethod) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestObjectString" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testObjectString) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestResolveIdents" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testResolveIdents) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestSelf" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testSelf) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestMultipleSizeUse" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testMultipleSizeUse) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAlignofNaclSlice" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testAlignofNaclSlice) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestIssue16902" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testIssue16902) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestAtomicAlign" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testAtomicAlign) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStdlib" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testStdlib) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStdTest" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testStdTest) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStdFixed" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testStdFixed) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestStdKen" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testStdKen) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestTypeString" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testTypeString) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestQualifiedTypeString" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.testQualifiedTypeString) : stdgo._internal.testing.Testing.InternalTest)) : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>(3, 3, (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkLookupFieldOrMethod" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.benchmarkLookupFieldOrMethod) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNamed" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.benchmarkNamed) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkCheck" : stdgo.GoString), stdgo._internal.go.types_test.Types_test.benchmarkCheck) : stdgo._internal.testing.Testing.InternalBenchmark)) : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>(0, 0) : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>(0, 0) : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo._internal.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        stdgo._internal.go.types_test.Types_test.testMain(_m);
        Sys.exit((stdgo._internal.reflect.Reflect.valueOf(stdgo.Go.toInterface(stdgo.Go.asInterface(_m))).elem().fieldByName(("exitCode" : stdgo.GoString)).int_() : stdgo.GoInt));
    }
@:keep var _ = {
        try {
            stdgo._internal.testing.internal.testdeps.Testdeps.importPath = ("go/types" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
