package stdgo.debug.dwarf;
var attrSibling : Attr = 1i64;
var attrLocation : Attr = 2i64;
var attrName : Attr = 3i64;
var attrOrdering : Attr = 9i64;
var attrByteSize : Attr = 11i64;
var attrBitOffset : Attr = 12i64;
var attrBitSize : Attr = 13i64;
var attrStmtList : Attr = 16i64;
var attrLowpc : Attr = 17i64;
var attrHighpc : Attr = 18i64;
var attrLanguage : Attr = 19i64;
var attrDiscr : Attr = 21i64;
var attrDiscrValue : Attr = 22i64;
var attrVisibility : Attr = 23i64;
var attrImport : Attr = 24i64;
var attrStringLength : Attr = 25i64;
var attrCommonRef : Attr = 26i64;
var attrCompDir : Attr = 27i64;
var attrConstValue : Attr = 28i64;
var attrContainingType : Attr = 29i64;
var attrDefaultValue : Attr = 30i64;
var attrInline : Attr = 32i64;
var attrIsOptional : Attr = 33i64;
var attrLowerBound : Attr = 34i64;
var attrProducer : Attr = 37i64;
var attrPrototyped : Attr = 39i64;
var attrReturnAddr : Attr = 42i64;
var attrStartScope : Attr = 44i64;
var attrStrideSize : Attr = 46i64;
var attrUpperBound : Attr = 47i64;
var attrAbstractOrigin : Attr = 49i64;
var attrAccessibility : Attr = 50i64;
var attrAddrClass : Attr = 51i64;
var attrArtificial : Attr = 52i64;
var attrBaseTypes : Attr = 53i64;
var attrCalling : Attr = 54i64;
var attrCount : Attr = 55i64;
var attrDataMemberLoc : Attr = 56i64;
var attrDeclColumn : Attr = 57i64;
var attrDeclFile : Attr = 58i64;
var attrDeclLine : Attr = 59i64;
var attrDeclaration : Attr = 60i64;
var attrDiscrList : Attr = 61i64;
var attrEncoding : Attr = 62i64;
var attrExternal : Attr = 63i64;
var attrFrameBase : Attr = 64i64;
var attrFriend : Attr = 65i64;
var attrIdentifierCase : Attr = 66i64;
var attrMacroInfo : Attr = 67i64;
var attrNamelistItem : Attr = 68i64;
var attrPriority : Attr = 69i64;
var attrSegment : Attr = 70i64;
var attrSpecification : Attr = 71i64;
var attrStaticLink : Attr = 72i64;
var attrType : Attr = 73i64;
var attrUseLocation : Attr = 74i64;
var attrVarParam : Attr = 75i64;
var attrVirtuality : Attr = 76i64;
var attrVtableElemLoc : Attr = 77i64;
var attrAllocated : Attr = 78i64;
var attrAssociated : Attr = 79i64;
var attrDataLocation : Attr = 80i64;
var attrStride : Attr = 81i64;
var attrEntrypc : Attr = 82i64;
var attrUseUTF8 : Attr = 83i64;
var attrExtension : Attr = 84i64;
var attrRanges : Attr = 85i64;
var attrTrampoline : Attr = 86i64;
var attrCallColumn : Attr = 87i64;
var attrCallFile : Attr = 88i64;
var attrCallLine : Attr = 89i64;
var attrDescription : Attr = 90i64;
var attrBinaryScale : Attr = 91i64;
var attrDecimalScale : Attr = 92i64;
var attrSmall : Attr = 93i64;
var attrDecimalSign : Attr = 94i64;
var attrDigitCount : Attr = 95i64;
var attrPictureString : Attr = 96i64;
var attrMutable : Attr = 97i64;
var attrThreadsScaled : Attr = 98i64;
var attrExplicit : Attr = 99i64;
var attrObjectPointer : Attr = 100i64;
var attrEndianity : Attr = 101i64;
var attrElemental : Attr = 102i64;
var attrPure : Attr = 103i64;
var attrRecursive : Attr = 104i64;
var attrSignature : Attr = 105i64;
var attrMainSubprogram : Attr = 106i64;
var attrDataBitOffset : Attr = 107i64;
var attrConstExpr : Attr = 108i64;
var attrEnumClass : Attr = 109i64;
var attrLinkageName : Attr = 110i64;
var attrStringLengthBitSize : Attr = 111i64;
var attrStringLengthByteSize : Attr = 112i64;
var attrRank : Attr = 113i64;
var attrStrOffsetsBase : Attr = 114i64;
var attrAddrBase : Attr = 115i64;
var attrRnglistsBase : Attr = 116i64;
var attrDwoName : Attr = 118i64;
var attrReference : Attr = 119i64;
var attrRvalueReference : Attr = 120i64;
var attrMacros : Attr = 121i64;
var attrCallAllCalls : Attr = 122i64;
var attrCallAllSourceCalls : Attr = 123i64;
var attrCallAllTailCalls : Attr = 124i64;
var attrCallReturnPC : Attr = 125i64;
var attrCallValue : Attr = 126i64;
var attrCallOrigin : Attr = 127i64;
var attrCallParameter : Attr = 128i64;
var attrCallPC : Attr = 129i64;
var attrCallTailCall : Attr = 130i64;
var attrCallTarget : Attr = 131i64;
var attrCallTargetClobbered : Attr = 132i64;
var attrCallDataLocation : Attr = 133i64;
var attrCallDataValue : Attr = 134i64;
var attrNoreturn : Attr = 135i64;
var attrAlignment : Attr = 136i64;
var attrExportSymbols : Attr = 137i64;
var attrDeleted : Attr = 138i64;
var attrDefaulted : Attr = 139i64;
var attrLoclistsBase : Attr = 140i64;
var tagArrayType : Tag = 1i64;
var tagClassType : Tag = 2i64;
var tagEntryPoint : Tag = 3i64;
var tagEnumerationType : Tag = 4i64;
var tagFormalParameter : Tag = 5i64;
var tagImportedDeclaration : Tag = 8i64;
var tagLabel : Tag = 10i64;
var tagLexDwarfBlock : Tag = 11i64;
var tagMember : Tag = 13i64;
var tagPointerType : Tag = 15i64;
var tagReferenceType : Tag = 16i64;
var tagCompileUnit : Tag = 17i64;
var tagStringType : Tag = 18i64;
var tagStructType : Tag = 19i64;
var tagSubroutineType : Tag = 21i64;
var tagTypedef : Tag = 22i64;
var tagUnionType : Tag = 23i64;
var tagUnspecifiedParameters : Tag = 24i64;
var tagVariant : Tag = 25i64;
var tagCommonDwarfBlock : Tag = 26i64;
var tagCommonInclusion : Tag = 27i64;
var tagInheritance : Tag = 28i64;
var tagInlinedSubroutine : Tag = 29i64;
var tagModule : Tag = 30i64;
var tagPtrToMemberType : Tag = 31i64;
var tagSetType : Tag = 32i64;
var tagSubrangeType : Tag = 33i64;
var tagWithStmt : Tag = 34i64;
var tagAccessDeclaration : Tag = 35i64;
var tagBaseType : Tag = 36i64;
var tagCatchDwarfBlock : Tag = 37i64;
var tagConstType : Tag = 38i64;
var tagConstant : Tag = 39i64;
var tagEnumerator : Tag = 40i64;
var tagFileType : Tag = 41i64;
var tagFriend : Tag = 42i64;
var tagNamelist : Tag = 43i64;
var tagNamelistItem : Tag = 44i64;
var tagPackedType : Tag = 45i64;
var tagSubprogram : Tag = 46i64;
var tagTemplateTypeParameter : Tag = 47i64;
var tagTemplateValueParameter : Tag = 48i64;
var tagThrownType : Tag = 49i64;
var tagTryDwarfBlock : Tag = 50i64;
var tagVariantPart : Tag = 51i64;
var tagVariable : Tag = 52i64;
var tagVolatileType : Tag = 53i64;
var tagDwarfProcedure : Tag = 54i64;
var tagRestrictType : Tag = 55i64;
var tagInterfaceType : Tag = 56i64;
var tagNamespace : Tag = 57i64;
var tagImportedModule : Tag = 58i64;
var tagUnspecifiedType : Tag = 59i64;
var tagPartialUnit : Tag = 60i64;
var tagImportedUnit : Tag = 61i64;
var tagMutableType : Tag = 62i64;
var tagCondition : Tag = 63i64;
var tagSharedType : Tag = 64i64;
var tagTypeUnit : Tag = 65i64;
var tagRvalueReferenceType : Tag = 66i64;
var tagTemplateAlias : Tag = 67i64;
var tagCoarrayType : Tag = 68i64;
var tagGenericSubrange : Tag = 69i64;
var tagDynamicType : Tag = 70i64;
var tagAtomicType : Tag = 71i64;
var tagCallSite : Tag = 72i64;
var tagCallSiteParameter : Tag = 73i64;
var tagSkeletonUnit : Tag = 74i64;
var tagImmutableType : Tag = 75i64;
var classUnknown : Class_ = 0i64;
var classAddress : Class_ = 1i64;
var classBlock : Class_ = 2i64;
var classConstant : Class_ = 3i64;
var classExprLoc : Class_ = 4i64;
var classFlag : Class_ = 5i64;
var classLinePtr : Class_ = 6i64;
var classLocListPtr : Class_ = 7i64;
var classMacPtr : Class_ = 8i64;
var classRangeListPtr : Class_ = 9i64;
var classReference : Class_ = 10i64;
var classReferenceSig : Class_ = 11i64;
var classString : Class_ = 12i64;
var classReferenceAlt : Class_ = 13i64;
var classStringAlt : Class_ = 14i64;
var classAddrPtr : Class_ = 15i64;
var classLocList : Class_ = 16i64;
var classRngList : Class_ = 17i64;
var classRngListsPtr : Class_ = 18i64;
var classStrOffsetsPtr : Class_ = 19i64;
var errUnknownPC(get, set) : stdgo.Error;
private function get_errUnknownPC():stdgo.Error return stdgo._internal.debug.dwarf.Dwarf_errunknownpc.errUnknownPC;
private function set_errUnknownPC(v:stdgo.Error):stdgo.Error {
        stdgo._internal.debug.dwarf.Dwarf_errunknownpc.errUnknownPC = v;
        return v;
    }
typedef Type_ = stdgo._internal.debug.dwarf.Dwarf_type_.Type_;
typedef DecodeError = stdgo._internal.debug.dwarf.Dwarf_decodeerror.DecodeError;
typedef Entry = stdgo._internal.debug.dwarf.Dwarf_entry.Entry;
typedef Field = stdgo._internal.debug.dwarf.Dwarf_field.Field;
typedef Reader = stdgo._internal.debug.dwarf.Dwarf_reader.Reader;
typedef LineReader = stdgo._internal.debug.dwarf.Dwarf_linereader.LineReader;
typedef LineEntry = stdgo._internal.debug.dwarf.Dwarf_lineentry.LineEntry;
typedef LineFile = stdgo._internal.debug.dwarf.Dwarf_linefile.LineFile;
typedef LineReaderPos = stdgo._internal.debug.dwarf.Dwarf_linereaderpos.LineReaderPos;
typedef Data = stdgo._internal.debug.dwarf.Dwarf_data.Data;
typedef CommonType = stdgo._internal.debug.dwarf.Dwarf_commontype.CommonType;
typedef BasicType = stdgo._internal.debug.dwarf.Dwarf_basictype.BasicType;
typedef CharType = stdgo._internal.debug.dwarf.Dwarf_chartype.CharType;
typedef UcharType = stdgo._internal.debug.dwarf.Dwarf_uchartype.UcharType;
typedef IntType = stdgo._internal.debug.dwarf.Dwarf_inttype.IntType;
typedef UintType = stdgo._internal.debug.dwarf.Dwarf_uinttype.UintType;
typedef FloatType = stdgo._internal.debug.dwarf.Dwarf_floattype.FloatType;
typedef ComplexType = stdgo._internal.debug.dwarf.Dwarf_complextype.ComplexType;
typedef BoolType = stdgo._internal.debug.dwarf.Dwarf_booltype.BoolType;
typedef AddrType = stdgo._internal.debug.dwarf.Dwarf_addrtype.AddrType;
typedef UnspecifiedType = stdgo._internal.debug.dwarf.Dwarf_unspecifiedtype.UnspecifiedType;
typedef QualType = stdgo._internal.debug.dwarf.Dwarf_qualtype.QualType;
typedef ArrayType = stdgo._internal.debug.dwarf.Dwarf_arraytype.ArrayType;
typedef VoidType = stdgo._internal.debug.dwarf.Dwarf_voidtype.VoidType;
typedef PtrType = stdgo._internal.debug.dwarf.Dwarf_ptrtype.PtrType;
typedef StructType = stdgo._internal.debug.dwarf.Dwarf_structtype.StructType;
typedef StructField = stdgo._internal.debug.dwarf.Dwarf_structfield.StructField;
typedef EnumType = stdgo._internal.debug.dwarf.Dwarf_enumtype.EnumType;
typedef EnumValue_ = stdgo._internal.debug.dwarf.Dwarf_enumvalue_.EnumValue_;
typedef FuncType = stdgo._internal.debug.dwarf.Dwarf_functype.FuncType;
typedef DotDotDotType = stdgo._internal.debug.dwarf.Dwarf_dotdotdottype.DotDotDotType;
typedef TypedefType = stdgo._internal.debug.dwarf.Dwarf_typedeftype.TypedefType;
typedef UnsupportedType = stdgo._internal.debug.dwarf.Dwarf_unsupportedtype.UnsupportedType;
typedef Attr = stdgo._internal.debug.dwarf.Dwarf_attr.Attr;
typedef Tag = stdgo._internal.debug.dwarf.Dwarf_tag.Tag;
typedef Class_ = stdgo._internal.debug.dwarf.Dwarf_class_.Class_;
typedef Offset = stdgo._internal.debug.dwarf.Dwarf_offset.Offset;
typedef DecodeErrorPointer = stdgo._internal.debug.dwarf.Dwarf_decodeerrorpointer.DecodeErrorPointer;
typedef EntryPointer = stdgo._internal.debug.dwarf.Dwarf_entrypointer.EntryPointer;
typedef FieldPointer = stdgo._internal.debug.dwarf.Dwarf_fieldpointer.FieldPointer;
typedef ReaderPointer = stdgo._internal.debug.dwarf.Dwarf_readerpointer.ReaderPointer;
typedef LineReaderPointer = stdgo._internal.debug.dwarf.Dwarf_linereaderpointer.LineReaderPointer;
typedef LineEntryPointer = stdgo._internal.debug.dwarf.Dwarf_lineentrypointer.LineEntryPointer;
typedef LineFilePointer = stdgo._internal.debug.dwarf.Dwarf_linefilepointer.LineFilePointer;
typedef LineReaderPosPointer = stdgo._internal.debug.dwarf.Dwarf_linereaderpospointer.LineReaderPosPointer;
typedef DataPointer = stdgo._internal.debug.dwarf.Dwarf_datapointer.DataPointer;
typedef CommonTypePointer = stdgo._internal.debug.dwarf.Dwarf_commontypepointer.CommonTypePointer;
typedef BasicTypePointer = stdgo._internal.debug.dwarf.Dwarf_basictypepointer.BasicTypePointer;
typedef CharTypePointer = stdgo._internal.debug.dwarf.Dwarf_chartypepointer.CharTypePointer;
typedef UcharTypePointer = stdgo._internal.debug.dwarf.Dwarf_uchartypepointer.UcharTypePointer;
typedef IntTypePointer = stdgo._internal.debug.dwarf.Dwarf_inttypepointer.IntTypePointer;
typedef UintTypePointer = stdgo._internal.debug.dwarf.Dwarf_uinttypepointer.UintTypePointer;
typedef FloatTypePointer = stdgo._internal.debug.dwarf.Dwarf_floattypepointer.FloatTypePointer;
typedef ComplexTypePointer = stdgo._internal.debug.dwarf.Dwarf_complextypepointer.ComplexTypePointer;
typedef BoolTypePointer = stdgo._internal.debug.dwarf.Dwarf_booltypepointer.BoolTypePointer;
typedef AddrTypePointer = stdgo._internal.debug.dwarf.Dwarf_addrtypepointer.AddrTypePointer;
typedef UnspecifiedTypePointer = stdgo._internal.debug.dwarf.Dwarf_unspecifiedtypepointer.UnspecifiedTypePointer;
typedef QualTypePointer = stdgo._internal.debug.dwarf.Dwarf_qualtypepointer.QualTypePointer;
typedef ArrayTypePointer = stdgo._internal.debug.dwarf.Dwarf_arraytypepointer.ArrayTypePointer;
typedef VoidTypePointer = stdgo._internal.debug.dwarf.Dwarf_voidtypepointer.VoidTypePointer;
typedef PtrTypePointer = stdgo._internal.debug.dwarf.Dwarf_ptrtypepointer.PtrTypePointer;
typedef StructTypePointer = stdgo._internal.debug.dwarf.Dwarf_structtypepointer.StructTypePointer;
typedef StructFieldPointer = stdgo._internal.debug.dwarf.Dwarf_structfieldpointer.StructFieldPointer;
typedef EnumTypePointer = stdgo._internal.debug.dwarf.Dwarf_enumtypepointer.EnumTypePointer;
typedef EnumValue_Pointer = stdgo._internal.debug.dwarf.Dwarf_enumvalue_pointer.EnumValue_Pointer;
typedef FuncTypePointer = stdgo._internal.debug.dwarf.Dwarf_functypepointer.FuncTypePointer;
typedef DotDotDotTypePointer = stdgo._internal.debug.dwarf.Dwarf_dotdotdottypepointer.DotDotDotTypePointer;
typedef TypedefTypePointer = stdgo._internal.debug.dwarf.Dwarf_typedeftypepointer.TypedefTypePointer;
typedef UnsupportedTypePointer = stdgo._internal.debug.dwarf.Dwarf_unsupportedtypepointer.UnsupportedTypePointer;
typedef AttrPointer = stdgo._internal.debug.dwarf.Dwarf_attrpointer.AttrPointer;
typedef TagPointer = stdgo._internal.debug.dwarf.Dwarf_tagpointer.TagPointer;
typedef Class_Pointer = stdgo._internal.debug.dwarf.Dwarf_class_pointer.Class_Pointer;
typedef OffsetPointer = stdgo._internal.debug.dwarf.Dwarf_offsetpointer.OffsetPointer;
/**
    * 
    * Package dwarf provides access to DWARF debugging information loaded from
    * executable files, as defined in the DWARF 2.0 Standard at
    * http://dwarfstd.org/doc/dwarf-2.0.0.pdf.
    * 
    * # Security
    * 
    * This package is not designed to be hardened against adversarial inputs, and is
    * outside the scope of https://go.dev/security/policy. In particular, only basic
    * validation is done when parsing object files. As such, care should be taken when
    * parsing untrusted inputs, as parsing malformed files may consume significant
    * resources, or cause panics.
    * 
**/
class Dwarf {
    /**
        * New returns a new Data object initialized from the given parameters.
        * Rather than calling this function directly, clients should typically use
        * the DWARF method of the File type of the appropriate package debug/elf,
        * debug/macho, or debug/pe.
        * 
        * The []byte arguments are the data from the corresponding debug section
        * in the object file; for example, for an ELF object, abbrev is the contents of
        * the ".debug_abbrev" section.
    **/
    static public inline function new_(_abbrev:stdgo.Slice<stdgo.GoUInt8>, _aranges:stdgo.Slice<stdgo.GoUInt8>, _frame:stdgo.Slice<stdgo.GoUInt8>, _info:stdgo.Slice<stdgo.GoUInt8>, _line:stdgo.Slice<stdgo.GoUInt8>, _pubnames:stdgo.Slice<stdgo.GoUInt8>, _ranges:stdgo.Slice<stdgo.GoUInt8>, _str:stdgo.Slice<stdgo.GoUInt8>):{ var _0 : stdgo.Ref<stdgo._internal.debug.dwarf.Dwarf_data.Data>; var _1 : stdgo.Error; } return stdgo._internal.debug.dwarf.Dwarf_new_.new_(_abbrev, _aranges, _frame, _info, _line, _pubnames, _ranges, _str);
}
