package stdgo.syscall.js_test;
import stdgo.StdGoTypes;
import stdgo.Error;
import stdgo.Go;
import stdgo.GoString;
import stdgo.Pointer;
import stdgo.Slice;
import stdgo.GoArray;
import stdgo.GoMap;
import stdgo.Chan;
var _tests : Slice<stdgo.testing.Testing.InternalTest> = null;
var _benchmarks : Slice<stdgo.testing.Testing.InternalBenchmark> = null;
var _fuzzTargets : Slice<stdgo.testing.Testing.InternalFuzzTarget> = null;
var _examples : Slice<stdgo.testing.Testing.InternalExample> = null;
function main():Void throw "syscall.js_test.main is not yet implemented";
