package stdgo.crypto.internal.edwards25519;
typedef T_fiatScalarMontgomeryDomainFieldElement = stdgo._internal.crypto.internal.edwards25519.Edwards25519_T_fiatScalarMontgomeryDomainFieldElement.T_fiatScalarMontgomeryDomainFieldElement;
