package stdgo.syscall_test;
import stdgo.StdGoTypes;
import stdgo.Error;
import stdgo.Go;
import stdgo.GoString;
import stdgo.Pointer;
import stdgo.Slice;
import stdgo.GoArray;
import stdgo.GoMap;
import stdgo.Chan;
function testEnv(_t:stdgo.testing.Testing.T_):Void return;
function testExecErrPermutedFds(_t:stdgo.testing.Testing.T_):Void return;
function testGettimeofday(_t:stdgo.testing.Testing.T_):Void return;
