package stdgo._internal.encoding.binary;
import stdgo._internal.math.Math;
import stdgo._internal.errors.Errors;
import stdgo._internal.io.Io;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strings.Strings;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.unsafe.Unsafe;
@:keep @:follow @:using(stdgo._internal.encoding.binary.Binary_T_testSizeStructCache___localname___foo_7241_static_extension.T_testSizeStructCache___localname___foo_7241_static_extension) typedef T_testSizeStructCache___localname___foo_7241Pointer = stdgo.Pointer<stdgo._internal.encoding.binary.Binary_T_testSizeStructCache___localname___foo_7241.T_testSizeStructCache___localname___foo_7241>;
