package stdgo._internal.encoding.binary;
import stdgo._internal.math.Math;
import stdgo._internal.errors.Errors;
import stdgo._internal.io.Io;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strings.Strings;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.unsafe.Unsafe;
@:keep @:follow @:using(stdgo._internal.encoding.binary.Binary_BlankFieldsProbe_static_extension.BlankFieldsProbe_static_extension) typedef BlankFieldsProbePointer = stdgo.Pointer<stdgo._internal.encoding.binary.Binary_BlankFieldsProbe.BlankFieldsProbe>;
