package stdgo._internal.net.http;
@:keep @:using(stdgo._internal.net.http.Http_T_http2sortPriorityNodeSiblings_static_extension.T_http2sortPriorityNodeSiblings_static_extension) typedef T_http2sortPriorityNodeSiblingsPointer = stdgo.Pointer<stdgo._internal.net.http.Http_T_http2sortPriorityNodeSiblings.T_http2sortPriorityNodeSiblings>;
