package stdgo._internal.net.http;
@:keep @:using(stdgo._internal.net.http.Http_T_http2write100ContinueHeadersFrame_static_extension.T_http2write100ContinueHeadersFrame_static_extension) typedef T_http2write100ContinueHeadersFramePointer = stdgo.Pointer<stdgo._internal.net.http.Http_T_http2write100ContinueHeadersFrame.T_http2write100ContinueHeadersFrame>;
