package stdgo._internal.image;
import stdgo._internal.errors.Errors;
import stdgo._internal.image.color.Color;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.image.color.palette.Palette;
import stdgo._internal.testing.Testing;
import stdgo._internal.strconv.Strconv;
@:keep @:follow @:using(stdgo._internal.image.Image_NYCbCrA_static_extension.NYCbCrA_static_extension) typedef NYCbCrAPointer = stdgo.Pointer<stdgo._internal.image.Image_NYCbCrA.NYCbCrA>;
