package stdgo._internal.crypto.rsa;
import stdgo._internal.errors.Errors;
import stdgo._internal.math.big.Big;
import stdgo._internal.crypto.internal.randutil.Randutil;
import stdgo._internal.crypto.internal.boring.Boring;
import stdgo._internal.crypto.subtle.Subtle;
import stdgo._internal.io.Io;
import stdgo._internal.bytes.Bytes;
import _internal.crypto.internal.boring.bbig.Bbig;
import stdgo._internal.crypto.internal.bigmod.Bigmod;
import stdgo._internal.math.Math;
import stdgo._internal.crypto.rand.Rand;
@:keep @:follow @:using(stdgo._internal.crypto.rsa.Rsa_PSSOptions_static_extension.PSSOptions_static_extension) typedef PSSOptionsPointer = stdgo.Pointer<stdgo._internal.crypto.rsa.Rsa_PSSOptions.PSSOptions>;
