package stdgo._internal.debug.dwarf;
import stdgo._internal.errors.Errors;
import stdgo._internal.path.Path;
import stdgo._internal.strings.Strings;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.io.Io;
import stdgo._internal.sort.Sort;
@:keep @:follow @:using(stdgo._internal.debug.dwarf.Dwarf_FuncType_static_extension.FuncType_static_extension) typedef FuncTypePointer = stdgo.Pointer<stdgo._internal.debug.dwarf.Dwarf_FuncType.FuncType>;
