package stdgo._internal.debug.dwarf;
import stdgo._internal.errors.Errors;
import stdgo._internal.path.Path;
import stdgo._internal.strings.Strings;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.io.Io;
import stdgo._internal.sort.Sort;
var _knownOpcodeLengths : stdgo.GoMap<stdgo.GoInt, stdgo.GoInt> = ({
        final x = new stdgo.GoMap.GoIntMap<stdgo.GoInt>();
        x.__defaultValue__ = () -> (0 : stdgo.GoInt);
        x.set((1 : stdgo.GoInt), (0 : stdgo.GoInt));
x.set((2 : stdgo.GoInt), (1 : stdgo.GoInt));
x.set((3 : stdgo.GoInt), (1 : stdgo.GoInt));
x.set((4 : stdgo.GoInt), (1 : stdgo.GoInt));
x.set((6 : stdgo.GoInt), (0 : stdgo.GoInt));
x.set((7 : stdgo.GoInt), (0 : stdgo.GoInt));
x.set((8 : stdgo.GoInt), (0 : stdgo.GoInt));
x.set((10 : stdgo.GoInt), (0 : stdgo.GoInt));
x.set((11 : stdgo.GoInt), (0 : stdgo.GoInt));
x.set((12 : stdgo.GoInt), (1 : stdgo.GoInt));
        x;
    } : stdgo.GoMap<stdgo.GoInt, stdgo.GoInt>);
