package stdgo._internal.debug.elf;
import stdgo._internal.errors.Errors;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.os.Os;
import stdgo._internal.io.Io;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strings.Strings;
import stdgo._internal.debug.dwarf.Dwarf;
import stdgo._internal.compress.zlib.Zlib;
import stdgo._internal.internal.zstd.Zstd;
var _dflagStrings : stdgo.Slice<stdgo._internal.debug.elf.Elf_T_intName.T_intName> = (new stdgo.Slice<stdgo._internal.debug.elf.Elf_T_intName.T_intName>(5, 5, ...[(new stdgo._internal.debug.elf.Elf_T_intName.T_intName((1u32 : stdgo.GoUInt32), ("DF_ORIGIN" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_T_intName.T_intName), (new stdgo._internal.debug.elf.Elf_T_intName.T_intName((2u32 : stdgo.GoUInt32), ("DF_SYMBOLIC" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_T_intName.T_intName), (new stdgo._internal.debug.elf.Elf_T_intName.T_intName((4u32 : stdgo.GoUInt32), ("DF_TEXTREL" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_T_intName.T_intName), (new stdgo._internal.debug.elf.Elf_T_intName.T_intName((8u32 : stdgo.GoUInt32), ("DF_BIND_NOW" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_T_intName.T_intName), (new stdgo._internal.debug.elf.Elf_T_intName.T_intName((16u32 : stdgo.GoUInt32), ("DF_STATIC_TLS" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_T_intName.T_intName)].concat([for (i in 5 ... (5 > 5 ? 5 : 5 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.debug.elf.Elf_T_intName.T_intName)])) : stdgo.Slice<stdgo._internal.debug.elf.Elf_T_intName.T_intName>);
