package stdgo._internal.debug.elf;
var _ptStrings : stdgo.Slice<stdgo._internal.debug.elf.Elf_t_intname.T_intName> = (new stdgo.Slice<stdgo._internal.debug.elf.Elf_t_intname.T_intName>(21, 21, ...[
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((0u32 : stdgo.GoUInt32), ("PT_NULL" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1u32 : stdgo.GoUInt32), ("PT_LOAD" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((2u32 : stdgo.GoUInt32), ("PT_DYNAMIC" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((3u32 : stdgo.GoUInt32), ("PT_INTERP" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((4u32 : stdgo.GoUInt32), ("PT_NOTE" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((5u32 : stdgo.GoUInt32), ("PT_SHLIB" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((6u32 : stdgo.GoUInt32), ("PT_PHDR" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((7u32 : stdgo.GoUInt32), ("PT_TLS" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1610612736u32 : stdgo.GoUInt32), ("PT_LOOS" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1685382480u32 : stdgo.GoUInt32), ("PT_GNU_EH_FRAME" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1685382481u32 : stdgo.GoUInt32), ("PT_GNU_STACK" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1685382482u32 : stdgo.GoUInt32), ("PT_GNU_RELRO" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1685382483u32 : stdgo.GoUInt32), ("PT_GNU_PROPERTY" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1694766464u32 : stdgo.GoUInt32), ("PT_PAX_FLAGS" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1705237478u32 : stdgo.GoUInt32), ("PT_OPENBSD_RANDOMIZE" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1705237479u32 : stdgo.GoUInt32), ("PT_OPENBSD_WXNEEDED" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1705253862u32 : stdgo.GoUInt32), ("PT_OPENBSD_BOOTDATA" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1879048187u32 : stdgo.GoUInt32), ("PT_SUNWSTACK" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1879048191u32 : stdgo.GoUInt32), ("PT_HIOS" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((1879048192u32 : stdgo.GoUInt32), ("PT_LOPROC" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName),
(new stdgo._internal.debug.elf.Elf_t_intname.T_intName((2147483647u32 : stdgo.GoUInt32), ("PT_HIPROC" : stdgo.GoString)) : stdgo._internal.debug.elf.Elf_t_intname.T_intName)].concat([for (i in 21 ... (21 > 21 ? 21 : 21 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.debug.elf.Elf_t_intname.T_intName)])) : stdgo.Slice<stdgo._internal.debug.elf.Elf_t_intname.T_intName>);
