package stdgo.encoding.json;
typedef T_testUnmarshalRescanLiteralMangledUnquote___localname___T_59829Pointer = stdgo._internal.encoding.json.Json_T_testUnmarshalRescanLiteralMangledUnquote___localname___T_59829Pointer.T_testUnmarshalRescanLiteralMangledUnquote___localname___T_59829Pointer;
