package stdgo.encoding.json;
typedef T_testUnmarshalEmbeddedUnexported___localname___S3_54541Pointer = stdgo._internal.encoding.json.Json_T_testUnmarshalEmbeddedUnexported___localname___S3_54541Pointer.T_testUnmarshalEmbeddedUnexported___localname___S3_54541Pointer;
