package stdgo.encoding.json;
typedef T_testEncoderErrorAndReuseEncodeState___localname___Data_1733Pointer = stdgo._internal.encoding.json.Json_T_testEncoderErrorAndReuseEncodeState___localname___Data_1733Pointer.T_testEncoderErrorAndReuseEncodeState___localname___Data_1733Pointer;
