package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___S_9958Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___S_9958Pointer.T_testAnonymousFields___localname___S_9958Pointer;
