package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___myInt_10694 = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___myInt_10694.T_testAnonymousFields___localname___myInt_10694;
