package stdgo.encoding.json;
typedef T_testUnmarshalEmbeddedUnexported___localname___S4_54578Pointer = stdgo._internal.encoding.json.Json_T_testUnmarshalEmbeddedUnexported___localname___S4_54578Pointer.T_testUnmarshalEmbeddedUnexported___localname___S4_54578Pointer;
