package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___myInt_8782 = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___myInt_8782.T_testAnonymousFields___localname___myInt_8782;
