package stdgo.encoding.json;
typedef T_testMarshalErrorAndReuseEncodeState___localname___Dummy_15460Pointer = stdgo._internal.encoding.json.Json_T_testMarshalErrorAndReuseEncodeState___localname___Dummy_15460Pointer.T_testMarshalErrorAndReuseEncodeState___localname___Dummy_15460Pointer;
