package stdgo.encoding.json;
typedef T_testUnmarshalEmbeddedUnexported___localname___embed1_54365Pointer = stdgo._internal.encoding.json.Json_T_testUnmarshalEmbeddedUnexported___localname___embed1_54365Pointer.T_testUnmarshalEmbeddedUnexported___localname___embed1_54365Pointer;
