package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___MyInt_9005Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___MyInt_9005Pointer.T_testAnonymousFields___localname___MyInt_9005Pointer;
