package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___s2_10709Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___s2_10709Pointer.T_testAnonymousFields___localname___s2_10709Pointer;
