package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___myInt_8782Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___myInt_8782Pointer.T_testAnonymousFields___localname___myInt_8782Pointer;
