package stdgo.encoding.json;
typedef T_testUnmarshalEmbeddedUnexported___localname___S5_54617Pointer = stdgo._internal.encoding.json.Json_T_testUnmarshalEmbeddedUnexported___localname___S5_54617Pointer.T_testUnmarshalEmbeddedUnexported___localname___S5_54617Pointer;
