package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___S_10811Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___S_10811Pointer.T_testAnonymousFields___localname___S_10811Pointer;
