package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___S_8796Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___S_8796Pointer.T_testAnonymousFields___localname___S_8796Pointer;
