package stdgo.encoding.json;
typedef T_testAnonymousFields___localname___S_11225Pointer = stdgo._internal.encoding.json.Json_T_testAnonymousFields___localname___S_11225Pointer.T_testAnonymousFields___localname___S_11225Pointer;
