package stdgo.encoding.json;
typedef T_testUnmarshalEmbeddedUnexported___localname___S7_54699Pointer = stdgo._internal.encoding.json.Json_T_testUnmarshalEmbeddedUnexported___localname___S7_54699Pointer.T_testUnmarshalEmbeddedUnexported___localname___S7_54699Pointer;
