package _internal.path.filepath_test;
import stdgo._internal.path.filepath.Filepath;
var evalSymlinksTests : stdgo.Slice<_internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest> = (new stdgo.Slice<_internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest>(12, 12, ...[
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test" : stdgo.GoString), ("test" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/dir" : stdgo.GoString), ("test/dir" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/dir/../.." : stdgo.GoString), ("." : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/link1" : stdgo.GoString), ("test" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/link2" : stdgo.GoString), ("test/dir" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/link1/dir" : stdgo.GoString), ("test/dir" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/link2/.." : stdgo.GoString), ("test" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/dir/link3" : stdgo.GoString), ("." : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/link2/link3/test" : stdgo.GoString), ("test" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/linkabs" : stdgo.GoString), ("/" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("test/link4/.." : stdgo.GoString), ("test" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest),
(new _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest(("src/versions/current/modules/test" : stdgo.GoString), ("src/pool/test" : stdgo.GoString)) : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest)].concat([for (i in 12 ... (12 > 12 ? 12 : 12 : stdgo.GoInt).toBasic()) ({} : _internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest)])) : stdgo.Slice<_internal.path.filepath_test.Filepath_test_EvalSymlinksTest.EvalSymlinksTest>);
