package _internal.path.filepath_test;
import stdgo._internal.path.filepath.Filepath;
var _winsplitlisttests : stdgo.Slice<_internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest> = (new stdgo.Slice<_internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest>(14, 14, ...[
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"a\"" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("a" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\";\"" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[(";" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"a;b\"" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("a;b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\";\";" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[(";" : stdgo.GoString), stdgo.Go.str()?.__copy__()]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest((";\";\"" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[stdgo.Go.str()?.__copy__(), (";" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("a\";\"b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("a;b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("a; \"\"b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("a" : stdgo.GoString), (" b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"a;b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("a;b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"\"a;b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("a" : stdgo.GoString), ("b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"\"\"a;b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("a;b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"\"\"\"a;b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("a" : stdgo.GoString), ("b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("a\";b" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(1, 1, ...[("a;b" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("a;b\";c" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("a" : stdgo.GoString), ("b;c" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest),
(new _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest(("\"a\";b\";c" : stdgo.GoString), (new stdgo.Slice<stdgo.GoString>(2, 2, ...[("a" : stdgo.GoString), ("b;c" : stdgo.GoString)]).__setString__() : stdgo.Slice<stdgo.GoString>)) : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest)].concat([for (i in 14 ... (14 > 14 ? 14 : 14 : stdgo.GoInt).toBasic()) ({} : _internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest)])) : stdgo.Slice<_internal.path.filepath_test.Filepath_test_SplitListTest.SplitListTest>);
