package stdgo._internal.expvar;
import stdgo._internal.log.Log;
import stdgo._internal.sort.Sort;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.os.Os;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.net.http.Http;
import stdgo._internal.sync.atomic_.Atomic_;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.math.Math;
import stdgo._internal.encoding.json.Json;
@:keep @:follow @:using(stdgo._internal.expvar.Expvar_Float__static_extension.Float__static_extension) typedef Float_Pointer = stdgo.Pointer<stdgo._internal.expvar.Expvar_Float_.Float_>;
