package stdgo._internal.net.http.pprof;
import stdgo._internal.net.http.Http;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.strings.Strings;
import stdgo._internal.os.Os;
import stdgo._internal.time.Time;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.runtime.pprof.Pprof;
import stdgo._internal.runtime.trace_.Trace_;
import stdgo._internal.bufio.Bufio;
import stdgo._internal.runtime.Runtime;
import stdgo._internal.io.Io;
import stdgo._internal.internal.profile.Profile;
import stdgo._internal.sort.Sort;
import stdgo._internal.log.Log;
import stdgo._internal.html.Html;
import stdgo._internal.context.Context;
var _profileSupportsDelta : stdgo.GoMap<stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler, Bool> = ({
        final x = new stdgo.GoMap.GoStringMap<Bool>();
        x.__defaultValue__ = () -> false;
        x.set((("allocs" : stdgo.GoString) : stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler), true);
x.set((("block" : stdgo.GoString) : stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler), true);
x.set((("goroutine" : stdgo.GoString) : stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler), true);
x.set((("heap" : stdgo.GoString) : stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler), true);
x.set((("mutex" : stdgo.GoString) : stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler), true);
x.set((("threadcreate" : stdgo.GoString) : stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler), true);
        x;
    } : stdgo.GoMap<stdgo._internal.net.http.pprof.Pprof_T_handler.T_handler, Bool>);
