package _internal.reflect_test;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
@:local @:using(_internal.reflect_test.Reflect_test_T__struct_102_static_extension.T__struct_102_static_extension) typedef T__struct_102 = {
    public var bool_ : Bool;
    public var int_ : stdgo.GoInt64;
    public var uint : stdgo.GoUInt64;
    public var float_ : stdgo.GoFloat64;
    public var complex : stdgo.GoComplex128;
    public var array : stdgo.GoArray<stdgo._internal.reflect.Reflect_Value.Value>;
    public var chan : stdgo.Chan<stdgo._internal.reflect.Reflect_Value.Value>;
    public var func : () -> stdgo._internal.reflect.Reflect_Value.Value;
    public var interface_ : _internal.reflect_test.Reflect_test_T__interface_4.T__interface_4;
    public var map_ : stdgo.GoMap<stdgo.GoString, stdgo._internal.reflect.Reflect_Value.Value>;
    public var pointer : stdgo.Ref<stdgo._internal.reflect.Reflect_Value.Value>;
    public var slice : stdgo.Slice<stdgo._internal.reflect.Reflect_Value.Value>;
    public var string : stdgo.GoString;
    public var struct_ : stdgo._internal.reflect.Reflect_Value.Value;
};
