package _internal.reflect_test;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
var _typeTests : stdgo.Slice<_internal.reflect_test.Reflect_test_T_pair.T_pair> = (new stdgo.Slice<_internal.reflect_test.Reflect_test_T_pair.T_pair>(36, 36, ...[
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface((new _internal.reflect_test.Reflect_test_T_inner.T_inner() : _internal.reflect_test.Reflect_test_T_inner.T_inner)), ("int" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoInt8) } : _internal.reflect_test.Reflect_test_T__struct_1.T__struct_1))), ("int8" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoInt16) } : _internal.reflect_test.Reflect_test_T__struct_2.T__struct_2))), ("int16" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoInt32) } : _internal.reflect_test.Reflect_test_T__struct_3.T__struct_3))), ("int32" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoInt64) } : _internal.reflect_test.Reflect_test_T__struct_4.T__struct_4))), ("int64" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoUInt) } : _internal.reflect_test.Reflect_test_T__struct_5.T__struct_5))), ("uint" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoUInt8) } : _internal.reflect_test.Reflect_test_T__struct_6.T__struct_6))), ("uint8" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoUInt16) } : _internal.reflect_test.Reflect_test_T__struct_7.T__struct_7))), ("uint16" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoUInt32) } : _internal.reflect_test.Reflect_test_T__struct_8.T__struct_8))), ("uint32" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoUInt64) } : _internal.reflect_test.Reflect_test_T__struct_9.T__struct_9))), ("uint64" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoFloat32) } : _internal.reflect_test.Reflect_test_T__struct_10.T__struct_10))), ("float32" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoFloat64) } : _internal.reflect_test.Reflect_test_T__struct_11.T__struct_11))), ("float64" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (0 : stdgo.GoInt8) } : _internal.reflect_test.Reflect_test_T__struct_1.T__struct_1))), ("int8" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Pointer<stdgo.Pointer<stdgo.GoInt8>>) } : _internal.reflect_test.Reflect_test_T__struct_12.T__struct_12))), ("**int8" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Pointer<stdgo.Pointer<_internal.reflect_test.Reflect_test_T_integer.T_integer>>) } : _internal.reflect_test.Reflect_test_T__struct_13.T__struct_13))), ("**reflect_test.integer" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : new stdgo.GoArray<stdgo.GoInt32>(32, 32, ...[for (i in 0 ... 32) (0 : stdgo.GoInt32)]) } : _internal.reflect_test.Reflect_test_T__struct_14.T__struct_14))), ("[32]int32" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Slice<stdgo.GoInt8>) } : _internal.reflect_test.Reflect_test_T__struct_15.T__struct_15))), ("[]int8" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.GoMap<stdgo.GoString, stdgo.GoInt32>) } : _internal.reflect_test.Reflect_test_T__struct_16.T__struct_16))), ("map[string]int32" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Chan<stdgo.GoString>) } : _internal.reflect_test.Reflect_test_T__struct_17.T__struct_17))), ("chan<- string" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Chan<stdgo.Chan<stdgo.GoString>>) } : _internal.reflect_test.Reflect_test_T__struct_18.T__struct_18))), ("chan<- chan string" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Chan<stdgo.Chan<stdgo.GoString>>) } : _internal.reflect_test.Reflect_test_T__struct_19.T__struct_19))), ("chan<- <-chan string" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Chan<stdgo.Chan<stdgo.GoString>>) } : _internal.reflect_test.Reflect_test_T__struct_20.T__struct_20))), ("<-chan <-chan string" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : stdgo.Chan<stdgo.Chan<stdgo.GoString>>) } : _internal.reflect_test.Reflect_test_T__struct_21.T__struct_21))), ("chan (<-chan string)" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _c : (null : stdgo.Chan<stdgo.Pointer<stdgo.GoInt32>>), _d : (0 : stdgo.GoFloat32) } } : _internal.reflect_test.Reflect_test_T__struct_22.T__struct_22))), ("struct { c chan *int32; d float32 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : null } : _internal.reflect_test.Reflect_test_T__struct_23.T__struct_23))), ("func(int8, int32)" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _c : null } } : _internal.reflect_test.Reflect_test_T__struct_24.T__struct_24))), ("struct { c func(chan *reflect_test.integer, *int8) }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8), _b : (0 : stdgo.GoInt32) } } : _internal.reflect_test.Reflect_test_T__struct_25.T__struct_25))), ("struct { a int8; b int32 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8), _b : (0 : stdgo.GoInt8), _c : (0 : stdgo.GoInt32) } } : _internal.reflect_test.Reflect_test_T__struct_26.T__struct_26))), ("struct { a int8; b int8; c int32 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8), _b : (0 : stdgo.GoInt8), _c : (0 : stdgo.GoInt8), _d : (0 : stdgo.GoInt32) } } : _internal.reflect_test.Reflect_test_T__struct_27.T__struct_27))), ("struct { a int8; b int8; c int8; d int32 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8), _b : (0 : stdgo.GoInt8), _c : (0 : stdgo.GoInt8), _d : (0 : stdgo.GoInt8), _e : (0 : stdgo.GoInt32) } } : _internal.reflect_test.Reflect_test_T__struct_28.T__struct_28))), ("struct { a int8; b int8; c int8; d int8; e int32 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8), _b : (0 : stdgo.GoInt8), _c : (0 : stdgo.GoInt8), _d : (0 : stdgo.GoInt8), _e : (0 : stdgo.GoInt8), _f : (0 : stdgo.GoInt32) } } : _internal.reflect_test.Reflect_test_T__struct_29.T__struct_29))), ("struct { a int8; b int8; c int8; d int8; e int8; f int32 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8) } } : _internal.reflect_test.Reflect_test_T__struct_30.T__struct_30))), ("struct { a int8 \"reflect:\\\"hi there\\\"\" }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _a : (0 : stdgo.GoInt8) } } : _internal.reflect_test.Reflect_test_T__struct_31.T__struct_31))), ("struct { a int8 \"reflect:\\\"hi \\\\x00there\\\\t\\\\n\\\\\\\"\\\\\\\\\\\"\" }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _f : null } } : _internal.reflect_test.Reflect_test_T__struct_32.T__struct_32))), ("struct { f func(...int) }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : (null : _internal.reflect_test.Reflect_test_T__interface_3.T__interface_3) } : _internal.reflect_test.Reflect_test_T__struct_33.T__struct_33))), ("interface { reflect_test.a(func(func(int) int) func(func(int)) int); reflect_test.b() }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair),
(new _internal.reflect_test.Reflect_test_T_pair.T_pair(stdgo.Go.toInterface(stdgo.Go.asInterface(({ _x : { _int32 : (0 : stdgo.GoInt32), _int64 : (0 : stdgo.GoInt64) } } : _internal.reflect_test.Reflect_test_T__struct_34.T__struct_34))), ("struct { int32; int64 }" : stdgo.GoString)) : _internal.reflect_test.Reflect_test_T_pair.T_pair)].concat([for (i in 36 ... (36 > 36 ? 36 : 36 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_T_pair.T_pair)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_T_pair.T_pair>);
