package _internal.reflect_test;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.reflect.Reflect;
function testCanSetField(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
        {};
        {};
        {};
        {};
        {};
        {};
        {};
        var _tests = (new stdgo.Slice<_internal.reflect_test.Reflect_test_T__struct_41.T__struct_41>(4, 4, ...[({ _val : stdgo._internal.reflect.Reflect_valueOf.valueOf(stdgo.Go.toInterface((stdgo.Go.setRef((new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___S1_10513.T_testCanSetField___localname___S1_10513() : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___S1_10513.T_testCanSetField___localname___S1_10513)) : stdgo.Ref<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___S1_10513.T_testCanSetField___localname___S1_10513>)))?.__copy__(), _cases : (new stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>(14, 14, ...[
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(2 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(2 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)].concat([for (i in 14 ... (14 > 14 ? 14 : 14 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>) } : _internal.reflect_test.Reflect_test_T__struct_41.T__struct_41), ({ _val : stdgo._internal.reflect.Reflect_valueOf.valueOf(stdgo.Go.toInterface((stdgo.Go.setRef(({ _embed : (stdgo.Go.setRef((new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___embed_10451.T_testCanSetField___localname___embed_10451() : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___embed_10451.T_testCanSetField___localname___embed_10451)) : stdgo.Ref<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___embed_10451.T_testCanSetField___localname___embed_10451>) } : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___S2_10553.T_testCanSetField___localname___S2_10553)) : stdgo.Ref<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___S2_10553.T_testCanSetField___localname___S2_10553>)))?.__copy__(), _cases : (new stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>(12, 12, ...[
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(2 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)].concat([for (i in 12 ... (12 > 12 ? 12 : 12 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>) } : _internal.reflect_test.Reflect_test_T__struct_41.T__struct_41), ({ _val : stdgo._internal.reflect.Reflect_valueOf.valueOf(stdgo.Go.toInterface((stdgo.Go.setRef((new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___S3_10594.T_testCanSetField___localname___S3_10594() : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___S3_10594.T_testCanSetField___localname___S3_10594)) : stdgo.Ref<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___S3_10594.T_testCanSetField___localname___S3_10594>)))?.__copy__(), _cases : (new stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>(12, 12, ...[
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(2 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)].concat([for (i in 12 ... (12 > 12 ? 12 : 12 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>) } : _internal.reflect_test.Reflect_test_T__struct_41.T__struct_41), ({ _val : stdgo._internal.reflect.Reflect_valueOf.valueOf(stdgo.Go.toInterface((stdgo.Go.setRef(({ embed : (stdgo.Go.setRef((new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___Embed_10482.T_testCanSetField___localname___Embed_10482() : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___Embed_10482.T_testCanSetField___localname___Embed_10482)) : stdgo.Ref<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___Embed_10482.T_testCanSetField___localname___Embed_10482>) } : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___S4_10634.T_testCanSetField___localname___S4_10634)) : stdgo.Ref<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___S4_10634.T_testCanSetField___localname___S4_10634>)))?.__copy__(), _cases : (new stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>(12, 12, ...[
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (0 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(2, 2, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(3, 3, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(4, 4, ...[(0 : stdgo.GoInt), (-1 : stdgo.GoInt), (1 : stdgo.GoInt), (-1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(1 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), false) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676),
(new _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676((new stdgo.Slice<stdgo.GoInt>(1, 1, ...[(2 : stdgo.GoInt)]).__setNumber32__() : stdgo.Slice<stdgo.GoInt>), true) : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)].concat([for (i in 12 ... (12 > 12 ? 12 : 12 : stdgo.GoInt).toBasic()) ({} : _internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>) } : _internal.reflect_test.Reflect_test_T__struct_41.T__struct_41)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({ _val : ({} : stdgo._internal.reflect.Reflect_Value.Value), _cases : (null : stdgo.Slice<_internal.reflect_test.Reflect_test_T_testCanSetField___localname___testCase_10676.T_testCanSetField___localname___testCase_10676>) } : _internal.reflect_test.Reflect_test_T__struct_41.T__struct_41)])) : stdgo.Slice<_internal.reflect_test.Reflect_test_T__struct_41.T__struct_41>);
        for (__7 => _tt in _tests) {
            _t.run(_tt._val.type().name()?.__copy__(), function(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
                for (__16 => _tc in _tt._cases) {
                    var _f = (_tt._val?.__copy__() : stdgo._internal.reflect.Reflect_Value.Value);
                    for (__17 => _i in _tc._index) {
                        if (_f.kind() == ((22u32 : stdgo._internal.reflect.Reflect_Kind.Kind))) {
                            _f = _f.elem()?.__copy__();
                        };
                        if (_i == ((-1 : stdgo.GoInt))) {
                            _f = _f.addr().elem()?.__copy__();
                        } else {
                            _f = _f.field(_i)?.__copy__();
                        };
                    };
                    {
                        var _got = (_f.canSet() : Bool);
                        if (_got != (_tc._canSet)) {
                            _t.errorf(("CanSet() = %v, want %v" : stdgo.GoString), stdgo.Go.toInterface(_got), stdgo.Go.toInterface(_tc._canSet));
                        };
                    };
                };
            });
        };
    }
