package _internal.time_test;
import stdgo._internal.time.Time;
import stdgo._internal.time.Time;
import stdgo._internal.time.Time;
import stdgo._internal.time.Time;
import stdgo._internal.time.Time;
import stdgo._internal.time.tzdata.Tzdata;
var _yearDayTests : stdgo.Slice<_internal.time_test.Time_test_YearDayTest.YearDayTest> = (new stdgo.Slice<_internal.time_test.Time_test_YearDayTest.YearDayTest>(50, 50, ...[
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (1 : stdgo.GoInt), (15 : stdgo.GoInt), (15 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (2 : stdgo.GoInt), (1 : stdgo.GoInt), (32 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (2 : stdgo.GoInt), (15 : stdgo.GoInt), (46 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (3 : stdgo.GoInt), (1 : stdgo.GoInt), (60 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (3 : stdgo.GoInt), (15 : stdgo.GoInt), (74 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (4 : stdgo.GoInt), (1 : stdgo.GoInt), (91 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2007 : stdgo.GoInt), (12 : stdgo.GoInt), (31 : stdgo.GoInt), (365 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (1 : stdgo.GoInt), (15 : stdgo.GoInt), (15 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (2 : stdgo.GoInt), (1 : stdgo.GoInt), (32 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (2 : stdgo.GoInt), (15 : stdgo.GoInt), (46 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (3 : stdgo.GoInt), (1 : stdgo.GoInt), (61 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (3 : stdgo.GoInt), (15 : stdgo.GoInt), (75 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (4 : stdgo.GoInt), (1 : stdgo.GoInt), (92 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((2008 : stdgo.GoInt), (12 : stdgo.GoInt), (31 : stdgo.GoInt), (366 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (1 : stdgo.GoInt), (15 : stdgo.GoInt), (15 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (2 : stdgo.GoInt), (1 : stdgo.GoInt), (32 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (2 : stdgo.GoInt), (15 : stdgo.GoInt), (46 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (3 : stdgo.GoInt), (1 : stdgo.GoInt), (60 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (3 : stdgo.GoInt), (15 : stdgo.GoInt), (74 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (4 : stdgo.GoInt), (1 : stdgo.GoInt), (91 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1900 : stdgo.GoInt), (12 : stdgo.GoInt), (31 : stdgo.GoInt), (365 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (1 : stdgo.GoInt), (15 : stdgo.GoInt), (15 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (2 : stdgo.GoInt), (1 : stdgo.GoInt), (32 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (2 : stdgo.GoInt), (15 : stdgo.GoInt), (46 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (3 : stdgo.GoInt), (1 : stdgo.GoInt), (60 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (3 : stdgo.GoInt), (15 : stdgo.GoInt), (74 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (4 : stdgo.GoInt), (1 : stdgo.GoInt), (91 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1 : stdgo.GoInt), (12 : stdgo.GoInt), (31 : stdgo.GoInt), (365 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (1 : stdgo.GoInt), (15 : stdgo.GoInt), (15 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (2 : stdgo.GoInt), (1 : stdgo.GoInt), (32 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (2 : stdgo.GoInt), (15 : stdgo.GoInt), (46 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (3 : stdgo.GoInt), (1 : stdgo.GoInt), (60 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (3 : stdgo.GoInt), (15 : stdgo.GoInt), (74 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (4 : stdgo.GoInt), (1 : stdgo.GoInt), (91 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-1 : stdgo.GoInt), (12 : stdgo.GoInt), (31 : stdgo.GoInt), (365 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt), (1 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (1 : stdgo.GoInt), (15 : stdgo.GoInt), (15 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (2 : stdgo.GoInt), (1 : stdgo.GoInt), (32 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (2 : stdgo.GoInt), (15 : stdgo.GoInt), (46 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (3 : stdgo.GoInt), (1 : stdgo.GoInt), (61 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (3 : stdgo.GoInt), (15 : stdgo.GoInt), (75 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (4 : stdgo.GoInt), (1 : stdgo.GoInt), (92 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((-400 : stdgo.GoInt), (12 : stdgo.GoInt), (31 : stdgo.GoInt), (366 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1582 : stdgo.GoInt), (10 : stdgo.GoInt), (4 : stdgo.GoInt), (277 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest),
(new _internal.time_test.Time_test_YearDayTest.YearDayTest((1582 : stdgo.GoInt), (10 : stdgo.GoInt), (15 : stdgo.GoInt), (288 : stdgo.GoInt)) : _internal.time_test.Time_test_YearDayTest.YearDayTest)].concat([for (i in 50 ... (50 > 50 ? 50 : 50 : stdgo.GoInt).toBasic()) ({} : _internal.time_test.Time_test_YearDayTest.YearDayTest)])) : stdgo.Slice<_internal.time_test.Time_test_YearDayTest.YearDayTest>);
