package stdgo.math_test;

import stdgo.StdGoTypes;
import stdgo.Error;
import stdgo.Go;
import stdgo.GoString;
import stdgo.Pointer;
import stdgo.Slice;
import stdgo.GoArray;
import stdgo.GoMap;
import stdgo.Chan;

private var _tests:Slice<stdgo.testing.Testing.InternalTest> = (new Slice<stdgo.testing.Testing.InternalTest>(0, 0,
	(new stdgo.testing.Testing.InternalTest(Go.str("TestNaN"), stdgo.math_test.Math_test.testNaN) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAcos"), stdgo.math_test.Math_test.testAcos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAcosh"), stdgo.math_test.Math_test.testAcosh) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAsin"), stdgo.math_test.Math_test.testAsin) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAsinh"), stdgo.math_test.Math_test.testAsinh) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAtan"), stdgo.math_test.Math_test.testAtan) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAtanh"), stdgo.math_test.Math_test.testAtanh) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAtan2"), stdgo.math_test.Math_test.testAtan2) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestCbrt"), stdgo.math_test.Math_test.testCbrt) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestCeil"), stdgo.math_test.Math_test.testCeil) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestCopysign"), stdgo.math_test.Math_test.testCopysign) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestCos"), stdgo.math_test.Math_test.testCos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestCosh"), stdgo.math_test.Math_test.testCosh) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestErf"), stdgo.math_test.Math_test.testErf) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestErfc"), stdgo.math_test.Math_test.testErfc) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestErfinv"), stdgo.math_test.Math_test.testErfinv) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestErfcinv"), stdgo.math_test.Math_test.testErfcinv) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestExp"), stdgo.math_test.Math_test.testExp) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestExpm1"), stdgo.math_test.Math_test.testExpm1) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestExp2"), stdgo.math_test.Math_test.testExp2) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestAbs"), stdgo.math_test.Math_test.testAbs) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestDim"), stdgo.math_test.Math_test.testDim) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestFloor"), stdgo.math_test.Math_test.testFloor) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestMax"), stdgo.math_test.Math_test.testMax) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestMin"), stdgo.math_test.Math_test.testMin) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestMod"), stdgo.math_test.Math_test.testMod) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestFrexp"), stdgo.math_test.Math_test.testFrexp) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestGamma"), stdgo.math_test.Math_test.testGamma) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestHypot"), stdgo.math_test.Math_test.testHypot) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestHypotGo"), stdgo.math_test.Math_test.testHypotGo) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestIlogb"), stdgo.math_test.Math_test.testIlogb) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestJ0"), stdgo.math_test.Math_test.testJ0) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestJ1"), stdgo.math_test.Math_test.testJ1) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestJn"), stdgo.math_test.Math_test.testJn) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLdexp"), stdgo.math_test.Math_test.testLdexp) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLgamma"), stdgo.math_test.Math_test.testLgamma) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLog"), stdgo.math_test.Math_test.testLog) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLogb"), stdgo.math_test.Math_test.testLogb) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLog10"), stdgo.math_test.Math_test.testLog10) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLog1p"), stdgo.math_test.Math_test.testLog1p) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLog2"), stdgo.math_test.Math_test.testLog2) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestModf"), stdgo.math_test.Math_test.testModf) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestNextafter32"), stdgo.math_test.Math_test.testNextafter32) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestNextafter64"), stdgo.math_test.Math_test.testNextafter64) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestPow"), stdgo.math_test.Math_test.testPow) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestPow10"), stdgo.math_test.Math_test.testPow10) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestRemainder"), stdgo.math_test.Math_test.testRemainder) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestRound"), stdgo.math_test.Math_test.testRound) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestRoundToEven"), stdgo.math_test.Math_test.testRoundToEven) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestSignbit"), stdgo.math_test.Math_test.testSignbit) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestSin"), stdgo.math_test.Math_test.testSin) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestSincos"), stdgo.math_test.Math_test.testSincos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestSinh"), stdgo.math_test.Math_test.testSinh) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestSqrt"), stdgo.math_test.Math_test.testSqrt) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestTan"), stdgo.math_test.Math_test.testTan) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestTanh"), stdgo.math_test.Math_test.testTanh) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestTrunc"), stdgo.math_test.Math_test.testTrunc) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestY0"), stdgo.math_test.Math_test.testY0) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestY1"), stdgo.math_test.Math_test.testY1) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestYn"), stdgo.math_test.Math_test.testYn) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestFMA"), stdgo.math_test.Math_test.testFMA) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLargeCos"), stdgo.math_test.Math_test.testLargeCos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLargeSin"), stdgo.math_test.Math_test.testLargeSin) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLargeSincos"), stdgo.math_test.Math_test.testLargeSincos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestLargeTan"), stdgo.math_test.Math_test.testLargeTan) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestTrigReduce"), stdgo.math_test.Math_test.testTrigReduce) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestFloatMinMax"), stdgo.math_test.Math_test.testFloatMinMax) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestFloatMinima"), stdgo.math_test.Math_test.testFloatMinima) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestFloat32Sqrt"), stdgo.math_test.Math_test.testFloat32Sqrt) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestMaxUint"), stdgo.math_test.Math_test.testMaxUint) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestMaxInt"), stdgo.math_test.Math_test.testMaxInt) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestHugeCos"), stdgo.math_test.Math_test.testHugeCos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestHugeSin"), stdgo.math_test.Math_test.testHugeSin) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestHugeSinCos"), stdgo.math_test.Math_test.testHugeSinCos) : stdgo.testing.Testing.InternalTest),
	(new stdgo.testing.Testing.InternalTest(Go.str("TestHugeTan"),
		stdgo.math_test.Math_test.testHugeTan) : stdgo.testing.Testing.InternalTest)) : Slice<stdgo.testing.Testing.InternalTest>);

private var _benchmarks:Slice<stdgo.testing.Testing.InternalBenchmark> = (new Slice<stdgo.testing.Testing.InternalBenchmark>(0, 0,
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAcos"), stdgo.math_test.Math_test.benchmarkAcos) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAcosh"),
		stdgo.math_test.Math_test.benchmarkAcosh) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAsin"), stdgo.math_test.Math_test.benchmarkAsin) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAsinh"),
		stdgo.math_test.Math_test.benchmarkAsinh) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAtan"), stdgo.math_test.Math_test.benchmarkAtan) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAtanh"),
		stdgo.math_test.Math_test.benchmarkAtanh) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAtan2"),
		stdgo.math_test.Math_test.benchmarkAtan2) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkCbrt"), stdgo.math_test.Math_test.benchmarkCbrt) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkCeil"), stdgo.math_test.Math_test.benchmarkCeil) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkCopysign"),
		stdgo.math_test.Math_test.benchmarkCopysign) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkCos"), stdgo.math_test.Math_test.benchmarkCos) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkCosh"), stdgo.math_test.Math_test.benchmarkCosh) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkErf"), stdgo.math_test.Math_test.benchmarkErf) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkErfc"), stdgo.math_test.Math_test.benchmarkErfc) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkErfinv"),
		stdgo.math_test.Math_test.benchmarkErfinv) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkErfcinv"),
		stdgo.math_test.Math_test.benchmarkErfcinv) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkExp"), stdgo.math_test.Math_test.benchmarkExp) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkExpGo"),
		stdgo.math_test.Math_test.benchmarkExpGo) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkExpm1"),
		stdgo.math_test.Math_test.benchmarkExpm1) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkExp2"), stdgo.math_test.Math_test.benchmarkExp2) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkExp2Go"),
		stdgo.math_test.Math_test.benchmarkExp2Go) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkAbs"), stdgo.math_test.Math_test.benchmarkAbs) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkDim"), stdgo.math_test.Math_test.benchmarkDim) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFloor"),
		stdgo.math_test.Math_test.benchmarkFloor) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkMax"), stdgo.math_test.Math_test.benchmarkMax) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkMin"), stdgo.math_test.Math_test.benchmarkMin) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkMod"), stdgo.math_test.Math_test.benchmarkMod) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFrexp"),
		stdgo.math_test.Math_test.benchmarkFrexp) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkGamma"),
		stdgo.math_test.Math_test.benchmarkGamma) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkHypot"),
		stdgo.math_test.Math_test.benchmarkHypot) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkHypotGo"),
		stdgo.math_test.Math_test.benchmarkHypotGo) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkIlogb"),
		stdgo.math_test.Math_test.benchmarkIlogb) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkJ0"), stdgo.math_test.Math_test.benchmarkJ0) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkJ1"), stdgo.math_test.Math_test.benchmarkJ1) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkJn"), stdgo.math_test.Math_test.benchmarkJn) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLdexp"),
		stdgo.math_test.Math_test.benchmarkLdexp) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLgamma"),
		stdgo.math_test.Math_test.benchmarkLgamma) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLog"), stdgo.math_test.Math_test.benchmarkLog) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLogb"), stdgo.math_test.Math_test.benchmarkLogb) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLog1p"),
		stdgo.math_test.Math_test.benchmarkLog1p) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLog10"),
		stdgo.math_test.Math_test.benchmarkLog10) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkLog2"), stdgo.math_test.Math_test.benchmarkLog2) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkModf"), stdgo.math_test.Math_test.benchmarkModf) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkNextafter32"),
		stdgo.math_test.Math_test.benchmarkNextafter32) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkNextafter64"),
		stdgo.math_test.Math_test.benchmarkNextafter64) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkPowInt"),
		stdgo.math_test.Math_test.benchmarkPowInt) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkPowFrac"),
		stdgo.math_test.Math_test.benchmarkPowFrac) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkPow10Pos"),
		stdgo.math_test.Math_test.benchmarkPow10Pos) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkPow10Neg"),
		stdgo.math_test.Math_test.benchmarkPow10Neg) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkRound"),
		stdgo.math_test.Math_test.benchmarkRound) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkRoundToEven"),
		stdgo.math_test.Math_test.benchmarkRoundToEven) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkRemainder"),
		stdgo.math_test.Math_test.benchmarkRemainder) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSignbit"),
		stdgo.math_test.Math_test.benchmarkSignbit) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSin"), stdgo.math_test.Math_test.benchmarkSin) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSincos"),
		stdgo.math_test.Math_test.benchmarkSincos) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSinh"), stdgo.math_test.Math_test.benchmarkSinh) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSqrtIndirect"),
		stdgo.math_test.Math_test.benchmarkSqrtIndirect) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSqrtLatency"),
		stdgo.math_test.Math_test.benchmarkSqrtLatency) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSqrtIndirectLatency"),
		stdgo.math_test.Math_test.benchmarkSqrtIndirectLatency) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSqrtGoLatency"),
		stdgo.math_test.Math_test.benchmarkSqrtGoLatency) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkSqrtPrime"),
		stdgo.math_test.Math_test.benchmarkSqrtPrime) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkTan"), stdgo.math_test.Math_test.benchmarkTan) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkTanh"), stdgo.math_test.Math_test.benchmarkTanh) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkTrunc"),
		stdgo.math_test.Math_test.benchmarkTrunc) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkY0"), stdgo.math_test.Math_test.benchmarkY0) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkY1"), stdgo.math_test.Math_test.benchmarkY1) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkYn"), stdgo.math_test.Math_test.benchmarkYn) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFloat64bits"),
		stdgo.math_test.Math_test.benchmarkFloat64bits) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFloat64frombits"),
		stdgo.math_test.Math_test.benchmarkFloat64frombits) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFloat32bits"),
		stdgo.math_test.Math_test.benchmarkFloat32bits) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFloat32frombits"),
		stdgo.math_test.Math_test.benchmarkFloat32frombits) : stdgo.testing.Testing.InternalBenchmark),
	(new stdgo.testing.Testing.InternalBenchmark(Go.str("BenchmarkFMA"),
		stdgo.math_test.Math_test.benchmarkFMA) : stdgo.testing.Testing.InternalBenchmark)) : Slice<stdgo.testing.Testing.InternalBenchmark>);

private var _fuzzTargets:Slice<stdgo.testing.Testing.InternalFuzzTarget> = (new Slice<stdgo.testing.Testing.InternalFuzzTarget>(0,
	0) : Slice<stdgo.testing.Testing.InternalFuzzTarget>);

private var _examples:Slice<stdgo.testing.Testing.InternalExample> = (new Slice<stdgo.testing.Testing.InternalExample>(0, 0,
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAcos"), stdgo.math_test.Math_test.exampleAcos, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAcosh"), stdgo.math_test.Math_test.exampleAcosh, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAsin"), stdgo.math_test.Math_test.exampleAsin, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAsinh"), stdgo.math_test.Math_test.exampleAsinh, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAtan"), stdgo.math_test.Math_test.exampleAtan, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAtan2"), stdgo.math_test.Math_test.exampleAtan2, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAtanh"), stdgo.math_test.Math_test.exampleAtanh, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleCopysign"), stdgo.math_test.Math_test.exampleCopysign, Go.str("-3.20\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleCos"), stdgo.math_test.Math_test.exampleCos, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleCosh"), stdgo.math_test.Math_test.exampleCosh, Go.str("1.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleSin"), stdgo.math_test.Math_test.exampleSin, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleSincos"), stdgo.math_test.Math_test.exampleSincos, Go.str("0.00, 1.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleSinh"), stdgo.math_test.Math_test.exampleSinh, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleTan"), stdgo.math_test.Math_test.exampleTan, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleTanh"), stdgo.math_test.Math_test.exampleTanh, Go.str("0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleSqrt"), stdgo.math_test.Math_test.exampleSqrt, Go.str("5.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleCeil"), stdgo.math_test.Math_test.exampleCeil, Go.str("2.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleFloor"), stdgo.math_test.Math_test.exampleFloor, Go.str("1.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExamplePow"), stdgo.math_test.Math_test.examplePow, Go.str("8.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExamplePow10"), stdgo.math_test.Math_test.examplePow10, Go.str("100.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleRound"), stdgo.math_test.Math_test.exampleRound, Go.str("11.0\n-11.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleRoundToEven"), stdgo.math_test.Math_test.exampleRoundToEven, Go.str("12.0\n12.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleLog"), stdgo.math_test.Math_test.exampleLog, Go.str("0.0\n1.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleLog2"), stdgo.math_test.Math_test.exampleLog2, Go.str("8.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleLog10"), stdgo.math_test.Math_test.exampleLog10, Go.str("2.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleRemainder"), stdgo.math_test.Math_test.exampleRemainder, Go.str("10.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleMod"), stdgo.math_test.Math_test.exampleMod, Go.str("3.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleAbs"), stdgo.math_test.Math_test.exampleAbs, Go.str("2.0\n2.0\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleDim"), stdgo.math_test.Math_test.exampleDim, Go.str("6.00\n0.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleExp"), stdgo.math_test.Math_test.exampleExp, Go.str("2.72\n7.39\n0.37\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleExp2"), stdgo.math_test.Math_test.exampleExp2, Go.str("2.00\n0.12\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleExpm1"), stdgo.math_test.Math_test.exampleExpm1, Go.str("0.010050\n-0.632121\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleTrunc"), stdgo.math_test.Math_test.exampleTrunc, Go.str("3.00\n-1.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleCbrt"), stdgo.math_test.Math_test.exampleCbrt, Go.str("2.00\n3.00\n"),
		false) : stdgo.testing.Testing.InternalExample),
	(new stdgo.testing.Testing.InternalExample(Go.str("ExampleModf"), stdgo.math_test.Math_test.exampleModf, Go.str("3.00, 0.14\n-2.00, -0.71\n"),
		false) : stdgo.testing.Testing.InternalExample)) : Slice<stdgo.testing.Testing.InternalExample>);

function main():Void {
	var _m = stdgo.testing.Testing.mainStart(Go.asInterface((new stdgo.testing.internal.testdeps.Testdeps.TestDeps() : stdgo.testing.internal.testdeps.Testdeps.TestDeps)),
		_tests, _benchmarks,
		_fuzzTargets, _examples);
	Sys.exit(_m.run());
}

@:keep var _ = {
	try {
		stdgo.testing.internal.testdeps.Testdeps.importPath = Go.str("math");
	} catch (__exception__)
		if (__exception__.message != "__return__")
			throw __exception__;
	true;
};
