package stdgo._internal.crypto.tls;
function cipherSuites():stdgo.Slice<stdgo.Ref<stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite>> {
        return (new stdgo.Slice<stdgo.Ref<stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite>>(17, 17, ...[
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((47 : stdgo.GoUInt16), ("TLS_RSA_WITH_AES_128_CBC_SHA" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supporteduptotls12._supportedUpToTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((53 : stdgo.GoUInt16), ("TLS_RSA_WITH_AES_256_CBC_SHA" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supporteduptotls12._supportedUpToTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((156 : stdgo.GoUInt16), ("TLS_RSA_WITH_AES_128_GCM_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((157 : stdgo.GoUInt16), ("TLS_RSA_WITH_AES_256_GCM_SHA384" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((4865 : stdgo.GoUInt16), ("TLS_AES_128_GCM_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls13._supportedOnlyTLS13, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((4866 : stdgo.GoUInt16), ("TLS_AES_256_GCM_SHA384" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls13._supportedOnlyTLS13, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((4867 : stdgo.GoUInt16), ("TLS_CHACHA20_POLY1305_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls13._supportedOnlyTLS13, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49161 : stdgo.GoUInt16), ("TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supporteduptotls12._supportedUpToTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49162 : stdgo.GoUInt16), ("TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supporteduptotls12._supportedUpToTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49171 : stdgo.GoUInt16), ("TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supporteduptotls12._supportedUpToTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49172 : stdgo.GoUInt16), ("TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supporteduptotls12._supportedUpToTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49195 : stdgo.GoUInt16), ("TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49196 : stdgo.GoUInt16), ("TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49199 : stdgo.GoUInt16), ("TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((49200 : stdgo.GoUInt16), ("TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((52392 : stdgo.GoUInt16), ("TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite),
(new stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite((52393 : stdgo.GoUInt16), ("TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256" : stdgo.GoString), stdgo._internal.crypto.tls.Tls__supportedonlytls12._supportedOnlyTLS12, false) : stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite)]) : stdgo.Slice<stdgo.Ref<stdgo._internal.crypto.tls.Tls_ciphersuite.CipherSuite>>);
    }
