package stdgo._internal.crypto.tls;
import stdgo._internal.internal.cpu.Cpu;
import stdgo._internal.errors.Errors;
import stdgo._internal.internal.godebug.Godebug;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.crypto.ecdsa.Ecdsa;
import stdgo._internal.crypto.ed25519.Ed25519;
import stdgo._internal.crypto.rsa.Rsa;
import stdgo._internal.io.Io;
import stdgo._internal.crypto.elliptic.Elliptic;
import stdgo._internal.crypto.rc4.Rc4;
import stdgo._internal.crypto.des.Des;
import stdgo._internal.crypto.cipher.Cipher;
import stdgo._internal.crypto.aes.Aes;
import stdgo._internal.crypto.sha1.Sha1;
import stdgo._internal.crypto.hmac.Hmac;
import stdgo._internal.crypto.sha256.Sha256;
import stdgo._internal.crypto.internal.boring.Boring;
import _internal.golang_dot_org.x.crypto.chacha20poly1305.Chacha20poly1305;
import stdgo._internal.container.list.List;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strings.Strings;
import stdgo._internal.net.Net;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.crypto.md5.Md5;
import stdgo._internal.crypto.ecdh.Ecdh;
import stdgo._internal.crypto.sha512.Sha512;
import stdgo._internal.context.Context;
import stdgo._internal.os.Os;
import stdgo._internal.encoding.pem.Pem;
import stdgo._internal.crypto.x509.X509;
import stdgo._internal.runtime.Runtime;
import _internal.golang_dot_org.x.crypto.hkdf.Hkdf;
import stdgo._internal.crypto.rand.Rand;
import stdgo._internal.time.Time;
import stdgo._internal.crypto.subtle.Subtle;
import stdgo._internal.encoding.binary.Binary;
import _internal.golang_dot_org.x.crypto.cryptobyte.Cryptobyte;
function _keysFromMasterSecret(_version:stdgo.GoUInt16, _suite:stdgo.Ref<stdgo._internal.crypto.tls.Tls_T_cipherSuite.T_cipherSuite>, _masterSecret:stdgo.Slice<stdgo.GoUInt8>, _clientRandom:stdgo.Slice<stdgo.GoUInt8>, _serverRandom:stdgo.Slice<stdgo.GoUInt8>, _macLen:stdgo.GoInt, _keyLen:stdgo.GoInt, _ivLen:stdgo.GoInt):{ var _0 : stdgo.Slice<stdgo.GoUInt8>; var _1 : stdgo.Slice<stdgo.GoUInt8>; var _2 : stdgo.Slice<stdgo.GoUInt8>; var _3 : stdgo.Slice<stdgo.GoUInt8>; var _4 : stdgo.Slice<stdgo.GoUInt8>; var _5 : stdgo.Slice<stdgo.GoUInt8>; } {
        var _clientMAC = (null : stdgo.Slice<stdgo.GoUInt8>), _serverMAC = (null : stdgo.Slice<stdgo.GoUInt8>), _clientKey = (null : stdgo.Slice<stdgo.GoUInt8>), _serverKey = (null : stdgo.Slice<stdgo.GoUInt8>), _clientIV = (null : stdgo.Slice<stdgo.GoUInt8>), _serverIV = (null : stdgo.Slice<stdgo.GoUInt8>);
        var _seed = (new stdgo.Slice<stdgo.GoUInt8>((0 : stdgo.GoInt).toBasic(), ((_serverRandom.length) + (_clientRandom.length) : stdgo.GoInt)).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>);
        _seed = (_seed.__append__(...(_serverRandom : Array<stdgo.GoUInt8>)));
        _seed = (_seed.__append__(...(_clientRandom : Array<stdgo.GoUInt8>)));
        var _n = ((((2 : stdgo.GoInt) * _macLen : stdgo.GoInt) + ((2 : stdgo.GoInt) * _keyLen : stdgo.GoInt) : stdgo.GoInt) + ((2 : stdgo.GoInt) * _ivLen : stdgo.GoInt) : stdgo.GoInt);
        var _keyMaterial = (new stdgo.Slice<stdgo.GoUInt8>((_n : stdgo.GoInt).toBasic(), 0).__setNumber32__() : stdgo.Slice<stdgo.GoUInt8>);
        stdgo._internal.crypto.tls.Tls__prfForVersion._prfForVersion(_version, _suite)(_keyMaterial, _masterSecret, stdgo._internal.crypto.tls.Tls__keyExpansionLabel._keyExpansionLabel, _seed);
        _clientMAC = (_keyMaterial.__slice__(0, _macLen) : stdgo.Slice<stdgo.GoUInt8>);
        _keyMaterial = (_keyMaterial.__slice__(_macLen) : stdgo.Slice<stdgo.GoUInt8>);
        _serverMAC = (_keyMaterial.__slice__(0, _macLen) : stdgo.Slice<stdgo.GoUInt8>);
        _keyMaterial = (_keyMaterial.__slice__(_macLen) : stdgo.Slice<stdgo.GoUInt8>);
        _clientKey = (_keyMaterial.__slice__(0, _keyLen) : stdgo.Slice<stdgo.GoUInt8>);
        _keyMaterial = (_keyMaterial.__slice__(_keyLen) : stdgo.Slice<stdgo.GoUInt8>);
        _serverKey = (_keyMaterial.__slice__(0, _keyLen) : stdgo.Slice<stdgo.GoUInt8>);
        _keyMaterial = (_keyMaterial.__slice__(_keyLen) : stdgo.Slice<stdgo.GoUInt8>);
        _clientIV = (_keyMaterial.__slice__(0, _ivLen) : stdgo.Slice<stdgo.GoUInt8>);
        _keyMaterial = (_keyMaterial.__slice__(_ivLen) : stdgo.Slice<stdgo.GoUInt8>);
        _serverIV = (_keyMaterial.__slice__(0, _ivLen) : stdgo.Slice<stdgo.GoUInt8>);
        return { _0 : _clientMAC, _1 : _serverMAC, _2 : _clientKey, _3 : _serverKey, _4 : _clientIV, _5 : _serverIV };
    }
