package _internal.encoding.base64_dot_test;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest>(17, 17, ...[
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestEncode" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testEncode.testEncode) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestEncoder" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testEncoder.testEncoder) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestEncoderBuffering" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testEncoderBuffering.testEncoderBuffering) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecode" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecode.testDecode) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoder" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoder.testDecoder) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoderBuffering" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoderBuffering.testDecoderBuffering) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecodeCorrupt" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecodeCorrupt.testDecodeCorrupt) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecodeBounds" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecodeBounds.testDecodeBounds) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestEncodedLen" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testEncodedLen.testEncodedLen) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecodedLen" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecodedLen.testDecodedLen) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestBig" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testBig.testBig) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestNewLineCharacters" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testNewLineCharacters.testNewLineCharacters) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoderIssue3577" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoderIssue3577.testDecoderIssue3577) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoderIssue4779" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoderIssue4779.testDecoderIssue4779) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoderIssue7733" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoderIssue7733.testDecoderIssue7733) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoderIssue15656" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoderIssue15656.testDecoderIssue15656) : stdgo._internal.testing.Testing_InternalTest.InternalTest),
(new stdgo._internal.testing.Testing_InternalTest.InternalTest(("TestDecoderRaw" : stdgo.GoString), stdgo._internal.encoding.base64.Base64_testDecoderRaw.testDecoderRaw) : stdgo._internal.testing.Testing_InternalTest.InternalTest)].concat([for (i in 17 ... (17 > 17 ? 17 : 17 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_InternalTest.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing_InternalTest.InternalTest>);
