package stdgo._internal.runtime;
@:keep @:follow @:using(stdgo._internal.runtime.Runtime_T_goroutineProfileStateHolder_static_extension.T_goroutineProfileStateHolder_static_extension) typedef T_goroutineProfileStateHolderPointer = stdgo.Pointer<stdgo._internal.runtime.Runtime_T_goroutineProfileStateHolder.T_goroutineProfileStateHolder>;
