package stdgo._internal.crypto.internal.edwards25519;
@:named @:using(stdgo._internal.crypto.internal.edwards25519.Edwards25519_T_fiatScalarMontgomeryDomainFieldElement_static_extension.T_fiatScalarMontgomeryDomainFieldElement_static_extension) typedef T_fiatScalarMontgomeryDomainFieldElement = stdgo.GoArray<stdgo.GoUInt64>;
