package stdgo._internal.crypto.internal.edwards25519;
@:named @:using(stdgo._internal.crypto.internal.edwards25519.Edwards25519_t_fiatscalarnonmontgomerydomainfieldelement_static_extension.T_fiatScalarNonMontgomeryDomainFieldElement_static_extension) typedef T_fiatScalarNonMontgomeryDomainFieldElement = stdgo.GoArray<stdgo.GoUInt64>;
