package _internal.unicode.utf8_dot_test;
import stdgo._internal.unicode.utf8.Utf8;
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample>(16, 16, ...[
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleDecodeLastRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleDecodeLastRune.exampleDecodeLastRune, ("界 3\n世 3\n  1\n, 1\no 1\nl 1\nl 1\ne 1\nH 1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleDecodeLastRuneInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleDecodeLastRuneInString.exampleDecodeLastRuneInString, ("界 3\n世 3\n  1\n, 1\no 1\nl 1\nl 1\ne 1\nH 1\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleDecodeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleDecodeRune.exampleDecodeRune, ("H 1\ne 1\nl 1\nl 1\no 1\n, 1\n  1\n世 3\n界 3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleDecodeRuneInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleDecodeRuneInString.exampleDecodeRuneInString, ("H 1\ne 1\nl 1\nl 1\no 1\n, 1\n  1\n世 3\n界 3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleEncodeRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleEncodeRune.exampleEncodeRune, ("[228 184 150]\n3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleEncodeRune_outOfRange" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleEncodeRune_outOfRange.exampleEncodeRune_outOfRange, ("0: [239 191 189] � 3\n1: [239 191 189] � 3\n2: [239 191 189] � 3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFullRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleFullRune.exampleFullRune, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFullRuneInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleFullRuneInString.exampleFullRuneInString, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleRuneCount" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleRuneCount.exampleRuneCount, ("bytes = 13\nrunes = 9\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleRuneCountInString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleRuneCountInString.exampleRuneCountInString, ("bytes = 13\nrunes = 9\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleRuneLen" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleRuneLen.exampleRuneLen, ("1\n3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleRuneStart" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleRuneStart.exampleRuneStart, ("true\ntrue\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleValid" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleValid.exampleValid, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleValidRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleValidRune.exampleValidRune, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleValidString" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleValidString.exampleValidString, ("true\nfalse\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleAppendRune" : stdgo.GoString), _internal.unicode.utf8_test.Utf8_test_exampleAppendRune.exampleAppendRune, ("𐀀\ninit𐀀\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample)].concat([for (i in 16 ... (16 > 16 ? 16 : 16 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_InternalExample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample>);
