package stdgo._internal.debug.macho;
import stdgo._internal.io.Io;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.os.Os;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strings.Strings;
import stdgo._internal.compress.zlib.Zlib;
import stdgo._internal.debug.dwarf.Dwarf;
final aRM64_RELOC_GOT_LOAD_PAGE21 : stdgo._internal.debug.macho.Macho_RelocTypeARM64.RelocTypeARM64 = (5 : stdgo._internal.debug.macho.Macho_RelocTypeARM64.RelocTypeARM64);
