package stdgo._internal.debug.macho;
import stdgo._internal.io.Io;
import stdgo._internal.encoding.binary.Binary;
import stdgo._internal.internal.saferio.Saferio;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.os.Os;
import stdgo._internal.bytes.Bytes;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.strings.Strings;
import stdgo._internal.compress.zlib.Zlib;
import stdgo._internal.debug.dwarf.Dwarf;
var _cpuStrings : stdgo.Slice<stdgo._internal.debug.macho.Macho_T_intName.T_intName> = (new stdgo.Slice<stdgo._internal.debug.macho.Macho_T_intName.T_intName>(6, 6, ...[(new stdgo._internal.debug.macho.Macho_T_intName.T_intName(((7u32 : stdgo._internal.debug.macho.Macho_Cpu.Cpu) : stdgo.GoUInt32), ("Cpu386" : stdgo.GoString)) : stdgo._internal.debug.macho.Macho_T_intName.T_intName), (new stdgo._internal.debug.macho.Macho_T_intName.T_intName(((16777223u32 : stdgo._internal.debug.macho.Macho_Cpu.Cpu) : stdgo.GoUInt32), ("CpuAmd64" : stdgo.GoString)) : stdgo._internal.debug.macho.Macho_T_intName.T_intName), (new stdgo._internal.debug.macho.Macho_T_intName.T_intName(((12u32 : stdgo._internal.debug.macho.Macho_Cpu.Cpu) : stdgo.GoUInt32), ("CpuArm" : stdgo.GoString)) : stdgo._internal.debug.macho.Macho_T_intName.T_intName), (new stdgo._internal.debug.macho.Macho_T_intName.T_intName(((16777228u32 : stdgo._internal.debug.macho.Macho_Cpu.Cpu) : stdgo.GoUInt32), ("CpuArm64" : stdgo.GoString)) : stdgo._internal.debug.macho.Macho_T_intName.T_intName), (new stdgo._internal.debug.macho.Macho_T_intName.T_intName(((18u32 : stdgo._internal.debug.macho.Macho_Cpu.Cpu) : stdgo.GoUInt32), ("CpuPpc" : stdgo.GoString)) : stdgo._internal.debug.macho.Macho_T_intName.T_intName), (new stdgo._internal.debug.macho.Macho_T_intName.T_intName(((16777234u32 : stdgo._internal.debug.macho.Macho_Cpu.Cpu) : stdgo.GoUInt32), ("CpuPpc64" : stdgo.GoString)) : stdgo._internal.debug.macho.Macho_T_intName.T_intName)].concat([for (i in 6 ... (6 > 6 ? 6 : 6 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.debug.macho.Macho_T_intName.T_intName)])) : stdgo.Slice<stdgo._internal.debug.macho.Macho_T_intName.T_intName>);
