package _internal.fmt_test;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.fmt.Fmt;
function testFormatString(_t:stdgo.Ref<stdgo._internal.testing.Testing_T_.T_>):Void {
        var _tests:stdgo.Slice<_internal.fmt_test.Fmt_test_T__struct_17.T__struct_17> = (new stdgo.Slice<_internal.fmt_test.Fmt_test_T__struct_17.T__struct_17>(10, 10, ...[({ _width : (-1000 : stdgo.GoInt), _prec : (-1000 : stdgo.GoInt), _flags : stdgo.Go.str()?.__copy__(), _result : ("%x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (-1000 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : stdgo.Go.str()?.__copy__(), _result : ("%.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (3 : stdgo.GoInt), _prec : (-1000 : stdgo.GoInt), _flags : stdgo.Go.str()?.__copy__(), _result : ("%3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : stdgo.Go.str()?.__copy__(), _result : ("%7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (-1000 : stdgo.GoInt), _prec : (-1000 : stdgo.GoInt), _flags : (" +-#0" : stdgo.GoString), _result : ("% +-#0x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : ("+" : stdgo.GoString), _result : ("%+7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (7 : stdgo.GoInt), _prec : (-3 : stdgo.GoInt), _flags : ("-" : stdgo.GoString), _result : ("%-7.-3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : (" " : stdgo.GoString), _result : ("% 7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : ("#" : stdgo.GoString), _result : ("%#7.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17), ({ _width : (7 : stdgo.GoInt), _prec : (3 : stdgo.GoInt), _flags : ("0" : stdgo.GoString), _result : ("%07.3x" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17)].concat([for (i in 10 ... (10 > 10 ? 10 : 10 : stdgo.GoInt).toBasic()) ({ _width : (0 : stdgo.GoInt), _prec : (0 : stdgo.GoInt), _flags : ("" : stdgo.GoString), _result : ("" : stdgo.GoString) } : _internal.fmt_test.Fmt_test_T__struct_17.T__struct_17)])) : stdgo.Slice<_internal.fmt_test.Fmt_test_T__struct_17.T__struct_17>);
        for (__2 => _test in _tests) {
            var _got = (stdgo._internal.fmt.Fmt_formatString.formatString(stdgo.Go.asInterface(_internal.fmt_test.Fmt_test__mkState._mkState(_test._width, _test._prec, _test._flags?.__copy__())), (120 : stdgo.GoInt32))?.__copy__() : stdgo.GoString);
            if (_got != (_test._result)) {
                _t.errorf(("%v: got %s" : stdgo.GoString), stdgo.Go.toInterface(stdgo.Go.asInterface(_test)), stdgo.Go.toInterface(_got));
            };
        };
    }
