package stdgo._internal.crypto.sha1_test;
import stdgo._internal.crypto.sha1.Sha1;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>(7, 7, ...[(new stdgo._internal.testing.Testing.InternalTest(("TestGolden" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testGolden) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestGoldenMarshal" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testGoldenMarshal) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestSize" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testSize) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestBlockSize" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testBlockSize) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestBlockGeneric" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testBlockGeneric) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestLargeHashes" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testLargeHashes) : stdgo._internal.testing.Testing.InternalTest), (new stdgo._internal.testing.Testing.InternalTest(("TestAllocations" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.testAllocations) : stdgo._internal.testing.Testing.InternalTest)].concat([for (i in 7 ... (7 > 7 ? 7 : 7 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>(4, 4, ...[(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkHash8Bytes" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.benchmarkHash8Bytes) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkHash320Bytes" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.benchmarkHash320Bytes) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkHash1K" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.benchmarkHash1K) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkHash8K" : stdgo.GoString), stdgo._internal.crypto.sha1.Sha1.benchmarkHash8K) : stdgo._internal.testing.Testing.InternalBenchmark)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>(2, 2, ...[(new stdgo._internal.testing.Testing.InternalExample(("ExampleNew" : stdgo.GoString), stdgo._internal.crypto.sha1_test.Sha1_test.exampleNew, ("59 7f 6a 54 00 10 f9 4c 15 d7 18 06 a9 9a 2c 87 10 e7 47 bd\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample), (new stdgo._internal.testing.Testing.InternalExample(("ExampleSum" : stdgo.GoString), stdgo._internal.crypto.sha1_test.Sha1_test.exampleSum, ("af 06 49 23 bb f2 30 15 96 aa c4 c2 73 ba 32 17 8e bc 4a 96\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample)].concat([for (i in 2 ... (2 > 2 ? 2 : 2 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo._internal.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        Sys.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo._internal.testing.internal.testdeps.Testdeps.importPath = ("crypto/sha1" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
