package stdgo._internal.encoding.asn1;
import stdgo._internal.math.big.Big;
import stdgo._internal.reflect.Reflect;
import stdgo._internal.time.Time;
import stdgo._internal.fmt.Fmt;
import stdgo._internal.unicode.utf8.Utf8;
import stdgo._internal.errors.Errors;
import stdgo._internal.unicode.utf16.Utf16;
import stdgo._internal.strings.Strings;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.sort.Sort;
import stdgo._internal.bytes.Bytes;
@:keep @:follow @:using(stdgo._internal.encoding.asn1.Asn1_T_asteriskFlag_static_extension.T_asteriskFlag_static_extension) typedef T_asteriskFlagPointer = stdgo.Pointer<stdgo._internal.encoding.asn1.Asn1_T_asteriskFlag.T_asteriskFlag>;
