package _internal.fmt_dot_test;
import stdgo._internal.fmt.Fmt;
var _examples : stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample>(17, 17, ...[
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleErrorf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleErrorf.exampleErrorf, ("user \"bueller\" (id 17) not found\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFscanf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleFscanf.exampleFscanf, ("5 true gophers\n3\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFscanln" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleFscanln.exampleFscanln, ("3: dmr, 1771, 1.618034\n3: ken, 271828, 3.141590\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSscanf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleSscanf.exampleSscanf, ("2: Kim, 22\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExamplePrint" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplePrint.examplePrint, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExamplePrintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplePrintln.examplePrintln, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExamplePrintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_examplePrintf.examplePrintf, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSprint" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleSprint.exampleSprint, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSprintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleSprintln.exampleSprintln, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleSprintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleSprintf.exampleSprintf, ("Kim is 22 years old.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFprint" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleFprint.exampleFprint, ("Kim is 22 years old.\n21 bytes written.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFprintln" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleFprintln.exampleFprintln, ("Kim is 22 years old.\n21 bytes written.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleFprintf" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleFprintf.exampleFprintf, ("Kim is 22 years old.\n21 bytes written.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("Example_printers" : stdgo.GoString), _internal.fmt_test.Fmt_test_example_printers.example_printers, ("The vector (3 4) has length 5.\nThe vector ( 3 4 ) has length 5 .\nThe vector (3 4) has length 5.\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("Example_formats" : stdgo.GoString), _internal.fmt_test.Fmt_test_example_formats.example_formats, ("23\n23\n23\nint *int\ntrue true\n42 42 2a 52 101010\n3.141592653589793 3.141592653589793 3.14 (  3.14) 3.141593e+00\n(110.7+22.5i) (110.7+22.5i) (110.70+22.50i) (1.11e+02+2.25e+01i)\n128512 128512 😀 \'😀\' U+1F600 U+1F600 \'😀\'\nfoo \"bar\" foo \"bar\" \"foo \\\"bar\\\"\" `foo \"bar\"`\nmap[dachshund:false peanut:true] map[string]bool{\"dachshund\":false, \"peanut\":true}\n{Kim 22} {Name:Kim Age:22} struct { Name string; Age int }{Name:\"Kim\", Age:22}\n&{Kim 22} 0x0\n[Kitano Kobayashi Kurosawa Miyazaki Ozu] [\"Kitano\" \"Kobayashi\" \"Kurosawa\" \"Miyazaki\" \"Ozu\"]\n[Kitano Kobayashi Kurosawa] [\"Kitano\" \"Kobayashi\" \"Kurosawa\"] []string{\"Kitano\", \"Kobayashi\", \"Kurosawa\"}\n[97 226 140 152] [97 226 140 152] a⌘ \"a⌘\" 61e28c98 61 e2 8c 98\n1973-11-29 21:33:09 +0000 UTC \"1973-11-29 21:33:09 +0000 UTC\"\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleGoStringer" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleGoStringer.exampleGoStringer, ("Person{Name: \"Warren\", Age: 31, Addr: &Address{City: \"Denver\", State: \"CO\", Country: \"U.S.A.\"}}\nPerson{Name: \"Theia\", Age: 4}\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample),
(new stdgo._internal.testing.Testing_InternalExample.InternalExample(("ExampleStringer" : stdgo.GoString), _internal.fmt_test.Fmt_test_exampleStringer.exampleStringer, ("Gopher (2)\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing_InternalExample.InternalExample)].concat([for (i in 17 ... (17 > 17 ? 17 : 17 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing_InternalExample.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing_InternalExample.InternalExample>);
