package stdgo._internal.reflect;
@:keep class Type__static_extension {
    static public function out(t:stdgo._internal.reflect.Reflect_Type_.Type_, _i:stdgo.GoInt):stdgo._internal.reflect.Reflect_Type_.Type_ return t.out(_i);
    static public function numOut(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.numOut();
    static public function numIn(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.numIn();
    static public function numField(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.numField();
    static public function len(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.len();
    static public function key(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo._internal.reflect.Reflect_Type_.Type_ return t.key();
    static public function in_(t:stdgo._internal.reflect.Reflect_Type_.Type_, _i:stdgo.GoInt):stdgo._internal.reflect.Reflect_Type_.Type_ return t.in_(_i);
    static public function fieldByNameFunc(t:stdgo._internal.reflect.Reflect_Type_.Type_, _match:stdgo.GoString -> Bool):{ var _0 : stdgo._internal.reflect.Reflect_StructField.StructField; var _1 : Bool; } return t.fieldByNameFunc(_match);
    static public function fieldByName(t:stdgo._internal.reflect.Reflect_Type_.Type_, _name:stdgo.GoString):{ var _0 : stdgo._internal.reflect.Reflect_StructField.StructField; var _1 : Bool; } return t.fieldByName(_name);
    static public function fieldByIndex(t:stdgo._internal.reflect.Reflect_Type_.Type_, _index:stdgo.Slice<stdgo.GoInt>):stdgo._internal.reflect.Reflect_StructField.StructField return t.fieldByIndex(_index);
    static public function field(t:stdgo._internal.reflect.Reflect_Type_.Type_, _i:stdgo.GoInt):stdgo._internal.reflect.Reflect_StructField.StructField return t.field(_i);
    static public function elem(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo._internal.reflect.Reflect_Type_.Type_ return t.elem();
    static public function isVariadic(t:stdgo._internal.reflect.Reflect_Type_.Type_):Bool return t.isVariadic();
    static public function chanDir(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo._internal.reflect.Reflect_ChanDir.ChanDir return t.chanDir();
    static public function bits(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.bits();
    static public function comparable_(t:stdgo._internal.reflect.Reflect_Type_.Type_):Bool return t.comparable_();
    static public function convertibleTo(t:stdgo._internal.reflect.Reflect_Type_.Type_, _u:stdgo._internal.reflect.Reflect_Type_.Type_):Bool return t.convertibleTo(_u);
    static public function assignableTo(t:stdgo._internal.reflect.Reflect_Type_.Type_, _u:stdgo._internal.reflect.Reflect_Type_.Type_):Bool return t.assignableTo(_u);
    static public function implements_(t:stdgo._internal.reflect.Reflect_Type_.Type_, _u:stdgo._internal.reflect.Reflect_Type_.Type_):Bool return t.implements_(_u);
    static public function kind(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo._internal.reflect.Reflect_Kind.Kind return t.kind();
    static public function string(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoString return t.string();
    static public function size(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoUIntptr return t.size();
    static public function pkgPath(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoString return t.pkgPath();
    static public function name(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoString return t.name();
    static public function numMethod(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.numMethod();
    static public function methodByName(t:stdgo._internal.reflect.Reflect_Type_.Type_, _0:stdgo.GoString):{ var _0 : stdgo._internal.reflect.Reflect_Method.Method; var _1 : Bool; } return t.methodByName(_0);
    static public function method(t:stdgo._internal.reflect.Reflect_Type_.Type_, _0:stdgo.GoInt):stdgo._internal.reflect.Reflect_Method.Method return t.method(_0);
    static public function fieldAlign(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.fieldAlign();
    static public function align(t:stdgo._internal.reflect.Reflect_Type_.Type_):stdgo.GoInt return t.align();
}
