package _internal.slices_test;
function exampleBinarySearchFunc():Void {
        {};
        var _people = (new stdgo.Slice<_internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559>(3, 3, ...[(new _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559(("Alice" : stdgo.GoString), (55 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559), (new _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559(("Bob" : stdgo.GoString), (24 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559), (new _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559(("Gopher" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559)])) : stdgo.Slice<_internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559>);
        var __tmp__ = stdgo._internal.slices.Slices_binarySearchFunc.binarySearchFunc(_people, (new _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559(("Bob" : stdgo.GoString), (0 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559), function(_a:_internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559, _b:_internal.slices_test.Slices_test_T_exampleBinarySearchFunc___localname___Person_559.T_exampleBinarySearchFunc___localname___Person_559):stdgo.GoInt {
            return stdgo._internal.cmp.Cmp_compare.compare(_a.name?.__copy__(), _b.name?.__copy__());
        }), _n:stdgo.GoInt = __tmp__._0, _found:Bool = __tmp__._1;
        stdgo._internal.fmt.Fmt_println.println(stdgo.Go.toInterface(("Bob:" : stdgo.GoString)), stdgo.Go.toInterface(_n), stdgo.Go.toInterface(_found));
    }
