package _internal.slices_test;
function exampleMinFunc():Void {
        {};
        var _people = (new stdgo.Slice<_internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924>(4, 4, ...[(new _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924(("Gopher" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924), (new _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924(("Bob" : stdgo.GoString), (5 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924), (new _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924(("Vera" : stdgo.GoString), (24 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924), (new _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924(("Bill" : stdgo.GoString), (5 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924)])) : stdgo.Slice<_internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924>);
        var _firstYoungest = (stdgo._internal.slices.Slices_minFunc.minFunc(_people, function(_a:_internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924, _b:_internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924):stdgo.GoInt {
            return stdgo._internal.cmp.Cmp_compare.compare(_a.age, _b.age);
        })?.__copy__() : _internal.slices_test.Slices_test_T_exampleMinFunc___localname___Person_4924.T_exampleMinFunc___localname___Person_4924);
        stdgo._internal.fmt.Fmt_println.println(stdgo.Go.toInterface(_firstYoungest.name));
    }
