package _internal.slices_test;
function exampleMaxFunc():Void {
        {};
        var _people = (new stdgo.Slice<_internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492>(4, 4, ...[(new _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492(("Gopher" : stdgo.GoString), (13 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492), (new _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492(("Alice" : stdgo.GoString), (55 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492), (new _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492(("Vera" : stdgo.GoString), (24 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492), (new _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492(("Bob" : stdgo.GoString), (55 : stdgo.GoInt)) : _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492)].concat([for (i in 4 ... (4 > 4 ? 4 : 4 : stdgo.GoInt).toBasic()) ({} : _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492)])) : stdgo.Slice<_internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492>);
        var _firstOldest = (stdgo._internal.slices.Slices_maxFunc.maxFunc(_people, function(_a:_internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492, _b:_internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492):stdgo.GoInt {
            return stdgo._internal.cmp.Cmp_compare.compare(_a.age, _b.age);
        })?.__copy__() : _internal.slices_test.Slices_test_T_exampleMaxFunc___localname___Person_4492.T_exampleMaxFunc___localname___Person_4492);
        stdgo._internal.fmt.Fmt_println.println(stdgo.Go.toInterface(_firstOldest.name));
    }
