package stdgo._internal.encoding.base64_test;
import stdgo._internal.encoding.base64.Base64;
var _tests : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>(17, 17, ...[
(new stdgo._internal.testing.Testing.InternalTest(("TestEncode" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testEncode) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEncoder" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testEncoder) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEncoderBuffering" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testEncoderBuffering) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecode" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecode) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoder" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoder) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoderBuffering" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoderBuffering) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecodeCorrupt" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecodeCorrupt) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecodeBounds" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecodeBounds) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestEncodedLen" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testEncodedLen) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecodedLen" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecodedLen) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestBig" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testBig) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestNewLineCharacters" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testNewLineCharacters) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoderIssue3577" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoderIssue3577) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoderIssue4779" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoderIssue4779) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoderIssue7733" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoderIssue7733) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoderIssue15656" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoderIssue15656) : stdgo._internal.testing.Testing.InternalTest),
(new stdgo._internal.testing.Testing.InternalTest(("TestDecoderRaw" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.testDecoderRaw) : stdgo._internal.testing.Testing.InternalTest)].concat([for (i in 17 ... (17 > 17 ? 17 : 17 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalTest)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalTest>);
var _benchmarks : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>(3, 3, ...[(new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkEncodeToString" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.benchmarkEncodeToString) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkDecodeString" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.benchmarkDecodeString) : stdgo._internal.testing.Testing.InternalBenchmark), (new stdgo._internal.testing.Testing.InternalBenchmark(("BenchmarkNewEncoding" : stdgo.GoString), stdgo._internal.encoding.base64.Base64.benchmarkNewEncoding) : stdgo._internal.testing.Testing.InternalBenchmark)].concat([for (i in 3 ... (3 > 3 ? 3 : 3 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalBenchmark)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalBenchmark>);
var _fuzzTargets : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>(0, 0, ...[].concat([for (i in 0 ... (0 > 0 ? 0 : 0 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalFuzzTarget)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalFuzzTarget>);
var _examples : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample> = (new stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>(6, 6, ...[(new stdgo._internal.testing.Testing.InternalExample(("Example" : stdgo.GoString), stdgo._internal.encoding.base64_test.Base64_test.example, ("SGVsbG8sIOS4lueVjA==\nHello, 世界\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample), (new stdgo._internal.testing.Testing.InternalExample(("ExampleEncoding_EncodeToString" : stdgo.GoString), stdgo._internal.encoding.base64_test.Base64_test.exampleEncoding_EncodeToString, ("YW55ICsgb2xkICYgZGF0YQ==\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample), (new stdgo._internal.testing.Testing.InternalExample(("ExampleEncoding_Encode" : stdgo.GoString), stdgo._internal.encoding.base64_test.Base64_test.exampleEncoding_Encode, ("SGVsbG8sIHdvcmxkIQ==\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample), (new stdgo._internal.testing.Testing.InternalExample(("ExampleEncoding_DecodeString" : stdgo.GoString), stdgo._internal.encoding.base64_test.Base64_test.exampleEncoding_DecodeString, ("\"some data with \\x00 and \\ufeff\"\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample), (new stdgo._internal.testing.Testing.InternalExample(("ExampleEncoding_Decode" : stdgo.GoString), stdgo._internal.encoding.base64_test.Base64_test.exampleEncoding_Decode, ("\"Hello, world!\"\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample), (new stdgo._internal.testing.Testing.InternalExample(("ExampleNewEncoder" : stdgo.GoString), stdgo._internal.encoding.base64_test.Base64_test.exampleNewEncoder, ("Zm9vAGJhcg==\n" : stdgo.GoString), false) : stdgo._internal.testing.Testing.InternalExample)].concat([for (i in 6 ... (6 > 6 ? 6 : 6 : stdgo.GoInt).toBasic()) ({} : stdgo._internal.testing.Testing.InternalExample)])) : stdgo.Slice<stdgo._internal.testing.Testing.InternalExample>);
function main():Void {
        var _m = stdgo._internal.testing.Testing.mainStart(stdgo.Go.asInterface((new stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps() : stdgo._internal.testing.internal.testdeps.Testdeps.TestDeps)), _tests, _benchmarks, _fuzzTargets, _examples);
        Sys.exit(_m.run());
    }
@:keep var _ = {
        try {
            stdgo._internal.testing.internal.testdeps.Testdeps.importPath = ("encoding/base64" : stdgo.GoString);
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
