package stdgo._internal.slices;
import stdgo._internal.math.Math;
import stdgo._internal.cmp.Cmp;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.strings.Strings;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.testing.Testing;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.sort.Sort;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
function _medianAdjacentCmpFunc(_data:stdgo.Slice<Dynamic>, _a:stdgo.GoInt, _swaps:stdgo.Pointer<stdgo.GoInt>, _cmp:(Dynamic, Dynamic) -> stdgo.GoInt):stdgo.GoInt throw "generic function is not supported";
