package stdgo._internal.slices;
import stdgo._internal.math.Math;
import stdgo._internal.cmp.Cmp;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.strings.Strings;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.testing.Testing;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.sort.Sort;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
function _choosePivotCmpFunc(_data:stdgo.Slice<Dynamic>, _a:stdgo.GoInt, _b:stdgo.GoInt, _cmp:(Dynamic, Dynamic) -> stdgo.GoInt):{ var _0 : stdgo.GoInt; var _1 : stdgo._internal.slices.Slices_T_sortedHint.T_sortedHint; } throw "generic function is not supported";
