package stdgo._internal.slices;
@:named @:using(stdgo._internal.slices.Slices_T_benchmarkCompactFunc_Large___localname___Large_15780_static_extension.T_benchmarkCompactFunc_Large___localname___Large_15780_static_extension) typedef T_benchmarkCompactFunc_Large___localname___Large_15780 = stdgo.GoArray<stdgo.GoUInt8>;
