package stdgo._internal.slices;
@:named @:using(stdgo._internal.slices.Slices_T_benchmarkIndexFunc_Large___localname___Large_8766_static_extension.T_benchmarkIndexFunc_Large___localname___Large_8766_static_extension) typedef T_benchmarkIndexFunc_Large___localname___Large_8766 = stdgo.GoArray<stdgo.GoUInt8>;
