package stdgo._internal.slices;
@:named @:using(stdgo._internal.slices.Slices_T_benchmarkEqualFunc_Large___localname___Large_2927_static_extension.T_benchmarkEqualFunc_Large___localname___Large_2927_static_extension) typedef T_benchmarkEqualFunc_Large___localname___Large_2927 = stdgo.GoArray<stdgo.GoUInt8>;
