package stdgo._internal.slices;
import stdgo._internal.math.Math;
import stdgo._internal.cmp.Cmp;
import stdgo._internal.unsafe.Unsafe;
import stdgo._internal.strings.Strings;
import stdgo._internal.internal.testenv.Testenv;
import stdgo._internal.testing.Testing;
import stdgo._internal.math.bits.Bits;
import stdgo._internal.math.rand.Rand;
import stdgo._internal.sort.Sort;
import stdgo._internal.strconv.Strconv;
import stdgo._internal.fmt.Fmt;
@:keep @:follow @:using(stdgo._internal.slices.Slices_T_benchmarkIndexFunc_Large___localname___Large_8766_static_extension.T_benchmarkIndexFunc_Large___localname___Large_8766_static_extension) typedef T_benchmarkIndexFunc_Large___localname___Large_8766Pointer = stdgo.Pointer<stdgo._internal.slices.Slices_T_benchmarkIndexFunc_Large___localname___Large_8766.T_benchmarkIndexFunc_Large___localname___Large_8766>;
